// The Necromancer's 72 rows: [enum, name, description, page, tier, column, kind]. All inert at N1.
const ARMY = ' Not yet built: awaits the army.';
const BONE = ' Not yet built: awaits the bone and poison missiles.';
const CURSE = ' Not yet built: awaits monster curses.';
const CORPSE = ' Not yet built: awaits usable corpses.';
const PASSIVE = ' Not yet built: awaits the system it modifies.';
module.exports = [
	// --- Summoning ---
	['RaiseSkeleton', 'Raise Skeleton', 'Raise a skeleton warrior from a corpse to fight for you. One skeleton at rank 1, one more every three ranks, eight at most.' + ARMY, 0, 0, 0, 'Active'],
	['SkeletonMastery', 'Skeleton Mastery', 'Your skeletons and skeletal mages gain life and damage with every rank.' + ARMY, 0, 0, 1, 'Passive'],
	['CommandTheDead', 'Command the Dead', 'Point at an enemy and every minion you own turns on it.' + ARMY, 0, 0, 2, 'Active'],
	['ClayGolem', 'Clay Golem', 'Shape a golem of clay: slow, tough, and its blows slow what it strikes. You keep one golem of any kind.' + ARMY, 0, 1, 0, 'Active'],
	['GolemMastery', 'Golem Mastery', 'Your golem gains life, speed and chance to hit with every rank.' + ARMY, 0, 1, 1, 'Passive'],
	['GatherTheDead', 'Gather the Dead', 'Call every minion to your side at once, through walls and across the floor.' + ARMY, 0, 1, 2, 'Active'],
	['RaiseSkeletalMage', 'Raise Skeletal Mage', 'Raise a skeletal mage from a corpse; it throws fire, cold, lightning or poison from behind your line. One at rank 1, one more every three ranks, eight at most.' + ARMY, 0, 2, 0, 'Active'],
	['SummonResist', 'Summon Resist', 'Everything you have raised resists fire, lightning and magic, more with every rank.' + ARMY, 0, 2, 1, 'Passive'],
	['DarkMending', 'Dark Mending', 'Knit your minions back together: every minion near you is healed at once.' + ARMY, 0, 2, 2, 'Active'],
	['BloodGolem', 'Blood Golem', 'A golem of blood bound to your own life: what it takes from its enemies heals you both.' + ARMY, 0, 3, 0, 'Active'],
	['BonePlating', 'Bone Plating', 'Your minions wear bone: armour for every one of them, more with every rank.' + ARMY, 0, 3, 1, 'Passive'],
	['FrenzyOfTheDead', 'Frenzy of the Dead', 'For a few seconds every minion attacks faster.' + ARMY, 0, 3, 2, 'Active'],
	['IronGolem', 'Iron Golem', 'A golem of iron that returns a share of every blow it takes to the one that struck it.' + ARMY, 0, 4, 0, 'Active'],
	['LastingBond', 'Lasting Bond', 'The Revived serve longer before they fall apart, more with every rank.' + ARMY, 0, 4, 1, 'Passive'],
	['UnholyOffering', 'Unholy Offering', 'Unmake one of your minions to heal yourself for a share of its life.' + ARMY, 0, 4, 2, 'Active'],
	['FireGolem', 'Fire Golem', 'A golem of fire: it burns what stands near it and is healed by fire.' + ARMY, 0, 5, 0, 'Active'],
	['NecroRevive', 'Revive', 'Return a dead monster to life to fight for you as it was, for a time. One at rank 1, ten at most. Paid in Essence.' + ARMY, 0, 5, 1, 'Active'],
	['ArmyOfTheDead', 'Army of the Dead', 'A host of the dead erupts at the cursor and tears at everything there for a few seconds.' + ARMY, 0, 5, 2, 'Active'],
	// --- Poison & Bone ---
	['Teeth', 'Teeth', 'A fan of barbed teeth, magic damage, one more tooth with every rank.' + BONE, 1, 0, 0, 'Active'],
	['BoneArmor', 'Bone Armor', 'A spinning shell of bone that absorbs physical damage until it is spent.' + BONE, 1, 0, 1, 'Active'],
	['PoisonDagger', 'Poison Dagger', 'Your next blows with a dagger or wand poison what they strike.' + BONE, 1, 0, 2, 'Active'],
	['CorpseExplosion', 'Corpse Explosion', 'Burst a corpse: everything near it takes a share of the dead monster\'s life as damage. Paid in Essence.' + CORPSE, 1, 1, 0, 'Active'],
	['BoneSplinters', 'Bone Splinters', 'Three quick splinters of bone in a narrow spread.' + BONE, 1, 1, 1, 'Active'],
	['Blight', 'Blight', 'A bolt that bursts into a pool of poison where it lands.' + BONE, 1, 1, 2, 'Active'],
	['BoneWall', 'Bone Wall', 'Raise a wall of bone across the cursor. Monsters must break it to pass.' + BONE, 1, 2, 0, 'Active'],
	['BoneSpikes', 'Bone Spikes', 'Spikes erupt under the cursor, magic damage, and hold what they hit for a moment.' + BONE, 1, 2, 1, 'Active'],
	['PoisonExplosion', 'Poison Explosion', 'Burst a corpse into a cloud of poison. Paid in Essence.' + CORPSE, 1, 2, 2, 'Active'],
	['BoneSpear', 'Bone Spear', 'A spear of bone that passes through everything in its line, magic damage.' + BONE, 1, 3, 0, 'Active'],
	['Decompose', 'Decompose', 'Rot an enemy where it stands: poison damage for as long as you hold the cast.' + BONE, 1, 3, 1, 'Active'],
	['Marrow', 'Marrow', 'Every bone skill deals more damage, more with every rank.' + BONE, 1, 3, 2, 'Passive'],
	['BonePrison', 'Bone Prison', 'A ring of bone closes around the target and holds it.' + BONE, 1, 4, 0, 'Active'],
	['BoneStorm', 'Bone Storm', 'A storm of bone shards circles you and cuts everything within two tiles.' + BONE, 1, 4, 1, 'Active'],
	['Virulence', 'Virulence', 'Your poisons last longer and bite deeper, more with every rank.' + BONE, 1, 4, 2, 'Passive'],
	['NecroBoneSpirit', 'Bone Spirit', 'A spirit of bone that hunts the nearest enemy and strikes it for heavy magic damage.' + BONE, 1, 5, 0, 'Active'],
	['PoisonNova', 'Poison Nova', 'A ring of poison bolts in every direction.' + BONE, 1, 5, 1, 'Active'],
	['DeathNova', 'Death Nova', 'A burst of bone and blight around you: magic damage now, poison after.' + BONE, 1, 5, 2, 'Active'],
	// --- Curses ---
	['AmplifyDamage', 'Amplify Damage', 'Cursed monsters take far more physical damage. One curse to a monster; a new one replaces the old. Paid in Essence.' + CURSE, 2, 0, 0, 'Active'],
	['CurseMastery', 'Curse Mastery', 'Your curses last longer, more with every rank.' + CURSE, 2, 0, 1, 'Passive'],
	['EssenceTap', 'Essence Tap', 'A cursed monster that dies returns Essence to you, more with every rank.' + CURSE, 2, 0, 2, 'Passive'],
	['DimVision', 'Dim Vision', 'Cursed monsters cannot see you until you are beside them. Paid in Essence.' + CURSE, 2, 1, 0, 'Active'],
	['NecroWeaken', 'Weaken', 'Cursed monsters deal a third less damage. Paid in Essence.' + CURSE, 2, 1, 1, 'Active'],
	['Frailty', 'Frailty', 'A cursed monster that falls below a sliver of its life simply dies. Paid in Essence.' + CURSE, 2, 1, 2, 'Active'],
	['NecroIronMaiden', 'Iron Maiden', 'Cursed monsters take a multiple of the melee damage they deal. Paid in Essence.' + CURSE, 2, 2, 0, 'Active'],
	['Terror', 'Terror', 'Cursed monsters run from you. Uniques do not. Paid in Essence.' + CURSE, 2, 2, 1, 'Active'],
	['Bane', 'Bane', 'Cursed monsters rot: poison damage for as long as the curse holds. Paid in Essence.' + CURSE, 2, 2, 2, 'Active'],
	['Confuse', 'Confuse', 'Cursed monsters attack whatever is nearest, friend or foe. Paid in Essence.' + CURSE, 2, 3, 0, 'Active'],
	['LifeTap', 'Life Tap', 'Blows landed on a cursed monster heal the one who struck - you and your minions alike. Paid in Essence.' + CURSE, 2, 3, 1, 'Active'],
	['WideMalice', 'Wide Malice', 'Your curses cover more ground, more with every rank.' + CURSE, 2, 3, 2, 'Passive'],
	['Attract', 'Attract', 'The cursed monster becomes the target of every monster near it. Paid in Essence.' + CURSE, 2, 4, 0, 'Active'],
	['Decrepify', 'Decrepify', 'Cursed monsters are slowed, deal less damage and take more. Paid in Essence.' + CURSE, 2, 4, 1, 'Active'],
	['DeathMark', 'Death Mark', 'Mark one monster: when it dies, it bursts as a Corpse Explosion of your rank. Paid in Essence.' + CURSE, 2, 4, 2, 'Active'],
	['LowerResist', 'Lower Resist', 'Cursed monsters lose resistance to fire, lightning, magic and poison. Paid in Essence.' + CURSE, 2, 5, 0, 'Active'],
	['SoulHarvest', 'Soul Harvest', 'Tear at every cursed monster near you: damage to each, Essence to you for each.' + CURSE, 2, 5, 1, 'Active'],
	['Doom', 'Doom', 'Cursed monsters take more damage from every source, and the curse cannot be replaced by a weaker one. Paid in Essence.' + CURSE, 2, 5, 2, 'Active'],
	// --- Passive Skills ---
	['LifeFromDeath', 'Life from Death', 'Monsters that die near you may leave a health globe.' + PASSIVE, 3, 0, 0, 'Passive'],
	['FueledByDeath', 'Fueled by Death', 'Each corpse you consume quickens your step for a few seconds.' + PASSIVE, 3, 0, 1, 'Passive'],
	['StandAlone', 'Stand Alone', 'More armour while you have no minions, less for each one you keep.' + PASSIVE, 3, 0, 2, 'Passive'],
	['SwiftHarvesting', 'Swift Harvesting', 'Faster attacks with a scythe or wand.' + PASSIVE, 3, 1, 0, 'Passive'],
	['CommanderOfTheRisenDead', 'Commander of the Risen Dead', 'Raising skeletons and mages costs less mana.' + PASSIVE, 3, 1, 1, 'Passive'],
	['ExtendedServitude', 'Extended Servitude', 'Timed minions last a quarter longer.' + PASSIVE, 3, 1, 2, 'Passive'],
	['RigorMortis', 'Rigor Mortis', 'Your bone skills slow what they hit.' + PASSIVE, 3, 2, 0, 'Passive'],
	['OverwhelmingEssence', 'Overwhelming Essence', 'Your Essence pool is larger by a fifth.' + PASSIVE, 3, 2, 1, 'Passive'],
	['DarkReaping', 'Dark Reaping', 'Your blows return a little Essence and a little mana.' + PASSIVE, 3, 2, 2, 'Passive'],
	['SpreadingMalediction', 'Spreading Malediction', 'You deal more damage for each cursed monster near you.' + PASSIVE, 3, 3, 0, 'Passive'],
	['EternalTorment', 'Eternal Torment', 'Your curses never run out; they end when the monster does.' + PASSIVE, 3, 3, 1, 'Passive'],
	['FinalService', 'Final Service', 'A blow that would kill you unmakes your minions instead, once a floor.' + PASSIVE, 3, 3, 2, 'Passive'],
	['GrislyTribute', 'Grisly Tribute', 'A share of the damage your minions deal heals you.' + PASSIVE, 3, 4, 0, 'Passive'],
	['DrawLife', 'Draw Life', 'You regenerate life faster for each monster near you.' + PASSIVE, 3, 4, 1, 'Passive'],
	['Serration', 'Serration', 'Your bone skills deal more damage the farther they have flown.' + PASSIVE, 3, 4, 2, 'Passive'],
	['AberrantAnimator', 'Aberrant Animator', 'Your minions return a share of the blows they take.' + PASSIVE, 3, 5, 0, 'Passive'],
	['BloodIsPower', 'Blood is Power', 'Losing life shortens the wait on your skills.' + PASSIVE, 3, 5, 1, 'Passive'],
	['RathmasShield', 'Rathma\'s Shield', 'When your life falls low, nothing can harm you for a few seconds. Once a floor.' + PASSIVE, 3, 5, 2, 'Passive'],
];
