/**
 * @file drlg_test.hpp
 *
 * Helpers for dungeon related tests.
 */
#pragma once

#include <gtest/gtest.h>

#include <cstdio>
#include <cstdlib>
#include <vector>

#include "engine/load_file.hpp"
#include "levels/themes.h"
#include "multi.h"
#include "options.h"
#include "player.h"
#include "quests.h"
#include "utils/paths.h"

using namespace devilution;

int GetTileCount(dungeon_type levelType)
{
	switch (levelType) {
	case DTYPE_TOWN:
		return 376;
	case DTYPE_CATHEDRAL:
		return 206;
	case DTYPE_CATACOMBS:
		return 160;
	case DTYPE_CAVES:
		return 206;
	case DTYPE_HELL:
		return 137;
	case DTYPE_NEST:
		return 166;
	case DTYPE_CRYPT:
		return 217;
	default:
		app_fatal("Invalid level type");
	}
}

std::unique_ptr<uint16_t[]> DunData;

void LoadExpectedLevelData(const char *fixture)
{
	// Set look up path to the location to load set pieces from later:
	paths::SetPrefPath(paths::BasePath() + "test/fixtures/");
	DunData = LoadFileInMem<uint16_t>(fixture);
	ASSERT_NE(DunData, nullptr) << "Unable to load test fixture " << fixture;
	ASSERT_EQ(Size(DMAXX, DMAXY), Size(SDL_SwapLE16(DunData[0]), SDL_SwapLE16(DunData[1])));
}

void TestInitGame(bool fullQuests = true, bool originalCathedral = true)
{
	Players.resize(1);
	MyPlayer = &Players[0];
	MyPlayer->pOriginalCathedral = originalCathedral;

	sgGameInitInfo.fullQuests = fullQuests ? 1 : 0;
	gbIsMultiplayer = !fullQuests;

	// Oracool: the golden maps were generated by upstream with "Randomize Quests" ON (upstream's
	// default), which culls one of Skeleton King / Poisoned Water and one quest per group from the
	// level-16 seed before any level is built. This fork ships the option OFF - every quest is on for
	// good (quests.cpp, InitQuests) - so level 3 grew the Skeleton King's set piece and its whole map
	// diverged from the golden (1314 of 1600 tiles; the standing failure since the fork changed the
	// default). The goldens encode the GENERATOR, not the fork's quest default, so the harness pins
	// upstream's value here; the fork's quest behaviour has its own tests.
	sgOptions.Gameplay.randomizeQuests.SetValue(true);

	InitQuests();
}

void TestCreateDungeon(int level, uint32_t seed, lvl_entry entry)
{
	currlevel = level;
	leveltype = GetLevelType(level);

	pMegaTiles = std::make_unique<MegaTile[]>(GetTileCount(leveltype));

	CreateDungeon(seed, entry);
	CreateThemeRooms();

	// Oracool: DRLG_TEST_DUMP=<file> writes what the generator produced, in the fixture's own .dun
	// layout (tile layer, then the transparency layer at the same offset the reader uses), so a
	// golden map can be diffed against the live generator and, once the difference is understood,
	// regenerated. See the 2026-09-07 report on the level-3 golden.
	if (const char *dump = std::getenv("DRLG_TEST_DUMP"); dump != nullptr) {
		std::vector<uint16_t> out(2 + DMAXX * DMAXY * 13 + DMAXX * 2 * DMAXY * 2, 0);
		out[0] = SDL_SwapLE16(DMAXX);
		out[1] = SDL_SwapLE16(DMAXY);
		for (int y = 0; y < DMAXY; y++)
			for (int x = 0; x < DMAXX; x++)
				out[2 + y * DMAXX + x] = SDL_SwapLE16(dungeon[x][y]);
		size_t t = 2 + DMAXX * DMAXY * 13;
		for (int y = 16; y < 16 + DMAXY * 2; y++)
			for (int x = 16; x < 16 + DMAXX * 2; x++)
				out[t++] = SDL_SwapLE16(dTransVal[x][y]);
		if (FILE *f = std::fopen(dump, "wb"); f != nullptr) {
			std::fwrite(out.data(), sizeof(uint16_t), out.size(), f);
			std::fclose(f);
		}
	}

	const uint16_t *tileLayer = &DunData[2];

	for (int y = 0; y < DMAXY; y++) {
		for (int x = 0; x < DMAXX; x++) {
			auto tileId = static_cast<uint8_t>(SDL_SwapLE16(*tileLayer));
			tileLayer++;
			ASSERT_EQ(dungeon[x][y], tileId) << "Tiles don't match at " << x << "x" << y;
		}
	}

	const uint16_t *transparentLayer = &DunData[2 + DMAXX * DMAXY * 13];

	for (int y = 16; y < 16 + DMAXY * 2; y++) {
		for (int x = 16; x < 16 + DMAXX * 2; x++) {
			auto sectorId = static_cast<uint8_t>(SDL_SwapLE16(*transparentLayer));
			transparentLayer++;
			ASSERT_EQ(dTransVal[x][y], sectorId) << "Room/region indexes don't match at " << x << "x" << y;
		}
	}
}
