#!/usr/bin/env node
/**
 * tools/GenHeroRampDye.js - builds Source/oracool/hero_recolour_data.inc: the Barbarian's and the Necromancer's colours as
 * RAMP DYES (user, 2026-09-27, chosen from rendered comparisons: "barb C, necro B, tint the plate greys", then "go with
 * your picks. necro - plate strong").
 *
 * Infravision's trick, one material at a time. The borrowed bodies are drawn from clean palette ramps, one per material
 * (OracoolPreview.DISABLED_HeroPaletteScan): the Warrior's mail and plate 240-255, trousers 184-191, gloves 168-175,
 * boots and belt 216-223, skin and hair 200-207; the Sorcerer's robe 224-239 (and the heavy tier's pure reds 136-143),
 * skin 160-175, sash and boots 208-223, plate 240-255. A dye gives a whole ramp a new hue and saturation, and every entry
 * keeps its own lightness (times a gain) - so the shading of each fold stays where it was, in any colour, green included.
 * Ramps not listed are left alone. One table serves all three armour tiers: the same ramps are the same materials on each.
 *
 * It replaces RfA-28's hand recolour (tools/GenHeroRecolour.js, v1.12.185), which sent one colour per index per tier from
 * ChatGPT's painted frames: harder to steer, and on the Necromancer's medium tier it painted the tan trim bone-yellow over
 * a black body.
 *
 * Output format is GenHeroRecolour.js's - { own, 0xRRGGBB, 8-bit fallback index } per palette index, six tables - so
 * oracool/hero_look.cpp reads it unchanged. The fallback is the nearest entry of the shared half (128-255), the same on
 * every level, which is what an 8-bit target draws.
 *
 * Usage: node tools/GenHeroRampDye.js tools/town.pal Source/oracool/hero_recolour_data.inc
 *   (tools/town.pal is the town palette, 768 bytes; gitignored - Blizzard data.)
 */
'use strict';
const fs = require('fs');

const [palettePath, outPath] = process.argv.slice(2);
if (!outPath) {
	console.error('usage: node GenHeroRampDye.js <town.pal> <out.inc>');
	process.exit(1);
}
const raw = fs.readFileSync(palettePath);
if (raw.length < 768) throw new Error(palettePath + ' is not a 768-byte palette');
const palette = [];
for (let i = 0; i < 256; i++) palette[i] = [raw[3 * i], raw[3 * i + 1], raw[3 * i + 2]];

/** [first, count, hue degrees, saturation 0-1, lightness gain] */
const Dyes = {
	// C, "north steel & moss", plate at the medium tint.
	barbarian: [
		[240, 16, 205, 0.12, 1.06], // mail and plate: cool steel
		[184, 8, 105, 0.32, 1.3], // trousers and tunic: moss green
		[168, 8, 30, 0.08, 1.25], // gloves: grey fur
		[216, 8, 28, 0.30, 0.95], // boots, belt, straps: worn leather
	],
	// B, "bone & violet", plate at the strong tint.
	necromancer: [
		[224, 16, 275, 0.38, 0.7], // robe: deep violet
		[136, 8, 275, 0.38, 0.7], // the heavy tier's pure reds: the same violet
		[160, 16, 42, 0.10, 1.35], // skin: bone
		[208, 16, 270, 0.12, 0.55], // sash and boots: near-black violet
		[240, 16, 268, 0.22, 0.92], // plate: violet-grey
	],
};

function hslToRgb(h, s, l) {
	const hue = (p, q, t) => {
		if (t < 0) t += 1;
		if (t > 1) t -= 1;
		if (t < 1 / 6) return p + (q - p) * 6 * t;
		if (t < 0.5) return q;
		if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
		return p;
	};
	l = Math.max(0, Math.min(1, l));
	const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
	const p = 2 * l - q;
	const hh = h / 360;
	const c = v => Math.round(Math.max(0, Math.min(1, v)) * 255);
	return [c(hue(p, q, hh + 1 / 3)), c(hue(p, q, hh)), c(hue(p, q, hh - 1 / 3))];
}

function nearestIndex(rgb) {
	let best = 128, bestD = Infinity;
	for (let i = 128; i < 256; i++) {
		const q = palette[i];
		const d = (q[0] - rgb[0]) ** 2 + (q[1] - rgb[1]) ** 2 + (q[2] - rgb[2]) ** 2;
		if (d < bestD) { bestD = d; best = i; }
	}
	return best;
}

function table(dyes) {
	const entries = [];
	for (let i = 0; i < 256; i++) entries[i] = { own: 0, rgb: [0, 0, 0], fallback: i };
	for (const [first, count, h, s, gain] of dyes) {
		for (let i = first; i < first + count; i++) {
			const [r, g, b] = palette[i];
			const lightness = (Math.max(r, g, b) + Math.min(r, g, b)) / 2 / 255;
			const rgb = hslToRgb(h, s, lightness * gain);
			entries[i] = { own: 1, rgb, fallback: nearestIndex(rgb) };
		}
	}
	return entries;
}

const hex = ([r, g, b]) => '0x' + [r, g, b].map(v => v.toString(16).toUpperCase().padStart(2, '0')).join('');
let out = '// GENERATED by tools/GenHeroRampDye.js - the ramp dyes (2026-09-27). Do not edit by hand: change the dyes there and\n'
	+ '// re-run it. { own, 0xRRGGBB, 8-bit fallback index } per palette index; one dye serves all three armour tiers.\n\n';
for (const [hero, name] of [['barbarian', 'Barbarian'], ['necromancer', 'Necromancer']]) {
	const entries = table(Dyes[hero]);
	for (const tier of ['Light', 'Medium', 'Heavy']) {
		out += `constexpr HeroRecolourEntry ${name}${tier}Recolour[256] = {\n`;
		for (let i = 0; i < 256; i += 4) {
			out += '\t' + entries.slice(i, i + 4).map(e => `{ ${e.own}, ${e.own ? hex(e.rgb) : '0x000000'}, ${e.fallback} }`).join(', ') + ',\n';
		}
		out += '};\n\n';
	}
	console.log(hero + ': ' + entries.filter(e => e.own).length + ' entries dyed');
}
fs.writeFileSync(outPath, out);
