#!/usr/bin/env node
/**
 * tools/GenHeroRecolour.js - builds Source/oracool/hero_recolour_data.inc from RfA-28's hand recolour (batch 59).
 *
 * Input: `hero_recolour_votes.json` (tools/), made by pairing every pixel of the 24 reference frames with the same
 * pixel of ChatGPT's recolour: for each hero, armour tier and town-palette index, how many pixels of that index were
 * painted which colour. It holds palette indices and colours only - no pixels of the original sprites.
 *
 * Output: for each hero x tier, the colour every index takes - the colour the MOST pixels of that index were painted
 * (on unseen frames that reproduces the hand recolour to a mean of 8 RGB units; a context-aware pass tested worse,
 * 2026-09-26). An index the reference frames never show borrows from the nearest shown index of its own 16-entry
 * palette ramp, scaled by the two entries' brightness, so a weapon or an animation the frames did not cover still
 * lands in the right material. A ramp with nothing shown is left alone (the original colour).
 *
 * Usage: node tools/GenHeroRecolour.js <votes.json> <town_palette.txt> <out.inc>
 *   town_palette.txt is `oracool_sprite_export warrior <dir> --dump-palette` output: "index r g b" per line.
 */
'use strict';
const fs = require('fs');

const [votesPath, palettePath, outPath] = process.argv.slice(2);
if (!outPath) {
	console.error('usage: node GenHeroRecolour.js <votes.json> <town_palette.txt> <out.inc>');
	process.exit(1);
}
const votes = JSON.parse(fs.readFileSync(votesPath, 'utf8').replace(/^﻿/, ''));
const palette = [];
if (palettePath.toLowerCase().endsWith('.pal')) {
	// tools/town.pal: 256 RGB triples
	const raw = fs.readFileSync(palettePath);
	for (let i = 0; i < 256; i++) palette[i] = [raw[3 * i], raw[3 * i + 1], raw[3 * i + 2]];
} else {
	for (const line of fs.readFileSync(palettePath, 'utf8').split(/\r?\n/)) {
		const p = line.trim().split(/\s+/).map(Number);
		if (p.length >= 4 && !Number.isNaN(p[0])) palette[p[0]] = [p[1], p[2], p[3]];
	}
}
if (palette.length < 256) throw new Error('palette has ' + palette.length + ' entries');

const lum = ([r, g, b]) => 0.299 * r + 0.587 * g + 0.114 * b;
const rgbOf = hex => [parseInt(hex.slice(1, 3), 16), parseInt(hex.slice(3, 5), 16), parseInt(hex.slice(5, 7), 16)];
const clamp = v => Math.max(0, Math.min(255, Math.round(v)));
// The 8-bit fallback: the nearest entry of the shared half (128-255), which is the same on every level.
function nearestIndex(rgb) {
	let best = 128, bestD = Infinity;
	for (let i = 128; i < 256; i++) {
		const q = palette[i];
		const d = (q[0] - rgb[0]) ** 2 + (q[1] - rgb[1]) ** 2 + (q[2] - rgb[2]) ** 2;
		if (d < bestD) { bestD = d; best = i; }
	}
	return best;
}

const heroes = ['barbarian', 'necromancer'];
const tiers = ['light', 'medium', 'heavy'];
let out = '// GENERATED by tools/GenHeroRecolour.js from RfA-28 batch 59 (the hand recolour of 24 reference frames).\n'
	+ '// Do not edit by hand: change the recolour, re-run the generator. { own, 0xRRGGBB, 8-bit fallback index } per palette index.\n\n';
const report = [];
for (const hero of heroes) {
	for (const tier of tiers) {
		const table = votes[`${hero}-${tier}`];
		if (!table) throw new Error(`no votes for ${hero}-${tier}`);
		const shown = new Map(); // index -> rgb
		for (const [idx, entry] of Object.entries(table)) shown.set(Number(idx), rgbOf(entry.colour));
		const rows = [];
		let direct = 0, borrowed = 0;
		for (let i = 0; i < 256; i++) {
			let rgb = shown.get(i);
			if (rgb) direct++;
			if (!rgb && i >= 128) {
				// nearest shown index in the same 16-entry ramp
				const base = i & ~15;
				let j = -1;
				for (let d = 1; d < 16 && j < 0; d++) {
					for (const c of [i - d, i + d]) {
						if (c >= base && c < base + 16 && shown.has(c)) { j = c; break; }
					}
				}
				if (j >= 0) {
					const from = shown.get(j);
					const scale = lum(palette[i]) / Math.max(1, lum(palette[j]));
					rgb = from.map(v => clamp(v * scale));
					borrowed++;
				}
			}
			// Index 0 (the outline and the shadow) and any index painted its own colour stay untouched.
			if (rgb && (i === 0 || (rgb[0] === palette[i][0] && rgb[1] === palette[i][1] && rgb[2] === palette[i][2])))
				rgb = undefined;
			if (!rgb) {
				rows.push('{ 0, 0x000000, ' + i + ' }');
				continue;
			}
			const hex = '0x' + rgb.map(v => v.toString(16).padStart(2, '0')).join('').toUpperCase();
			rows.push(`{ 1, ${hex}, ${nearestIndex(rgb)} }`);
		}
		const name = hero[0].toUpperCase() + hero.slice(1) + tier[0].toUpperCase() + tier.slice(1) + 'Recolour';
		out += `constexpr HeroRecolourEntry ${name}[256] = {\n`;
		for (let r = 0; r < 256; r += 4) out += '\t' + rows.slice(r, r + 4).join(', ') + ',\n';
		out += '};\n\n';
		report.push(`${hero}-${tier}: ${direct} indices from the recolour, ${borrowed} borrowed along their ramp`);
	}
}
fs.writeFileSync(outPath, out);
console.log(report.join('\n'));
