// LevskiCubeSheet - builds Levski's Cube's animated sheet (user, 2026-10-01: "animated idle state, opening sequence,
// opened idle state, ... closing sequence when i walk away") from ChatGPT's green-screen stills in
//   Resources\02. Oracooll Assets\01. Used\levski-cube\green-background\{closed_idle,opening,opened_idle}\
// and writes
//   Packaging\resources\oracool_assets\objects\levski_cube.png   one row of frames, FrameW x FrameH, real alpha
//   Source\oracool\levski_cube_frames.inc                        the frame counts, for the game's state machine
//
// The stills are "not ideal" (the user's words): every state was drawn at its own scale and offset, the opened frames are
// cropped at the sides and the top, and some carry slivers of their neighbours. So each frame is
//   1. keyed off the green (a fringe pixel keeps its colour with the green spilled out of it),
//   2. cleaned of slivers (a piece under 12px wide, under 150 pixels or three times taller than wide) and white smears,
//   3. measured on the pedestal's BASE - the widest row in the body's lower 40 rows (the slab is a diamond, its foot a
//      point) - and scaled so that base is BaseWidth wide, centred, its foot on the frame's bottom row.
// The base is the one part every still draws the same; the cube above it grows and shrinks as the states say.
//
// Not used: the closing stills (the game plays the opening backwards - user, 2026-10-01: "we can reuse opening sequence
// for closing by reversing it"), and opened idle 02 and 04, which are cut off halfway down the panel.
// The pink panel is not measured here: the game draws its own over the opened frames (levski_roar.cpp).
//
// Usage: tools\build_levski_cube_sheet.cmd  (compiles and runs this from the repository root)
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Text;

static class LevskiCubeSheet
{
	const int FrameW = 128;
	const int FrameH = 192;
	const int BaseWidth = 90; // the painting's base in the game, so the Cube keeps its footprint

	static readonly string[] States = { "closed_idle", "opening", "opened_idle" };
	static readonly HashSet<string> Skipped = new HashSet<string> { "cube_opened_idle_02.png", "cube_opened_idle_04.png" };

	static int Main(string[] args)
	{
		string src = args[0], outPng = args[1], outInc = args[2], preview = args.Length > 3 ? args[3] : null;
		var frames = new List<Bitmap>();
		var counts = new List<int>();
		foreach (string state in States) {
			string[] files = Directory.GetFiles(Path.Combine(src, state), "*.png");
			Array.Sort(files, StringComparer.Ordinal);
			int n = 0;
			foreach (string file in files) {
				if (Skipped.Contains(Path.GetFileName(file)))
					continue;
				frames.Add(BuildFrame(file));
				n++;
			}
			counts.Add(n);
		}
		var sheet = new Bitmap(FrameW * frames.Count, FrameH, PixelFormat.Format32bppArgb);
		using (Graphics g = Graphics.FromImage(sheet)) {
			g.Clear(Color.Transparent);
			for (int i = 0; i < frames.Count; i++)
				g.DrawImageUnscaled(frames[i], i * FrameW, 0);
		}
		sheet.Save(outPng, ImageFormat.Png);
		Console.WriteLine("{0}: {1} frames of {2}x{3} ({4})", outPng, frames.Count, FrameW, FrameH, string.Join("+", counts));

		var inc = new StringBuilder();
		inc.Append("// Generated by tools/LevskiCubeSheet.cs - do not edit. Levski's Cube's frames (levski_cube.png).\n");
		inc.AppendFormat("// {0} x {1} each: closed idle, opening (played backwards to close), opened idle.\n", FrameW, FrameH);
		inc.AppendFormat("constexpr int LevskiCubeFrameWidth = {0};\n", FrameW);
		inc.AppendFormat("constexpr int LevskiCubeClosedIdleFrames = {0};\n", counts[0]);
		inc.AppendFormat("constexpr int LevskiCubeOpeningFrames = {0};\n", counts[1]);
		inc.AppendFormat("constexpr int LevskiCubeOpenedIdleFrames = {0};\n", counts[2]);
		File.WriteAllText(outInc, inc.ToString().Replace("\r\n", "\n"));

		if (preview != null) {
			// Every frame at 2x on a dusk ground: the check the numbers cannot give.
			var p = new Bitmap(FrameW * 2 * 12, FrameH * 2 * 3, PixelFormat.Format32bppArgb);
			using (Graphics g = Graphics.FromImage(p)) {
				g.Clear(Color.FromArgb(255, 58, 50, 44));
				g.InterpolationMode = InterpolationMode.NearestNeighbor;
				g.PixelOffsetMode = PixelOffsetMode.Half;
				for (int i = 0; i < frames.Count; i++)
					g.DrawImage(frames[i], (i % 12) * FrameW * 2, (i / 12) * FrameH * 2, FrameW * 2, FrameH * 2);
			}
			p.Save(preview, ImageFormat.Png);
		}
		return 0;
	}

	static bool IsGreen(int r, int g, int b) { return g - Math.Max(r, b) > 90; }

	static Bitmap BuildFrame(string path)
	{
		Bitmap srcBmp;
		using (var loaded = new Bitmap(path))
			srcBmp = loaded.Clone(new Rectangle(0, 0, loaded.Width, loaded.Height), PixelFormat.Format32bppArgb);
		int w = srcBmp.Width, h = srcBmp.Height;
		int[] px = Read(srcBmp);
		bool[] solid = new bool[w * h];
		for (int i = 0; i < px.Length; i++) {
			int r = (px[i] >> 16) & 255, g = (px[i] >> 8) & 255, b = px[i] & 255;
			if (IsGreen(r, g, b)) { px[i] = 0; continue; }
			// A fringe: the green spilled out, never more green than its other two channels.
			int cap = Math.Max(r, b);
			if (g > cap) g = cap;
			px[i] = unchecked((int)0xFF000000) | (r << 16) | (g << 8) | b;
			solid[i] = true;
		}
		// Components, 8-connected: drop slivers and the white bars.
		int[] label = new int[w * h];
		var stack = new Stack<int>();
		int next = 0;
		int biggest = 0, biggestCount = 0;
		for (int start = 0; start < solid.Length; start++) {
			if (!solid[start] || label[start] != 0) continue;
			next++;
			var members = new List<int>();
			int minX = w, maxX = -1, minY = h, maxY = -1;
			long bright = 0;
			stack.Push(start); label[start] = next;
			while (stack.Count > 0) {
				int at = stack.Pop();
				members.Add(at);
				int x = at % w, y = at / w;
				minX = Math.Min(minX, x); maxX = Math.Max(maxX, x);
				minY = Math.Min(minY, y); maxY = Math.Max(maxY, y);
				int c = px[at];
				int lo = Math.Min((c >> 16) & 255, Math.Min((c >> 8) & 255, c & 255));
				bright += lo;
				for (int dy = -1; dy <= 1; dy++)
					for (int dx = -1; dx <= 1; dx++) {
						int nx = x + dx, ny = y + dy;
						if (nx < 0 || ny < 0 || nx >= w || ny >= h) continue;
						int n = ny * w + nx;
						if (solid[n] && label[n] == 0) { label[n] = next; stack.Push(n); }
					}
			}
			int bw = maxX - minX + 1, bh = maxY - minY + 1;
			bool sliver = bw < 12 || members.Count < 150 || bh > 3 * bw; // a thin bar or a crumb of a neighbour
			if (!sliver && members.Count > biggestCount) { biggestCount = members.Count; biggest = next; }
			bool whiteBar = bright / members.Count > 200; // every channel high: a white smear, not art
			if (sliver || whiteBar)
				foreach (int m in members) { solid[m] = false; px[m] = 0; }
		}
		// The base: the bottom 12 rows of the BODY - the largest piece - so a crumb below it measures nothing.
		int bottom = -1;
		for (int i = solid.Length - 1; i >= 0 && bottom < 0; i--) if (solid[i] && label[i] == biggest) bottom = i / w;
		// The slab is an isometric diamond, so its foot is a point: the base is its WIDEST row in the body's lower 40 rows.
		int left = w, right = -1;
		for (int y = Math.Max(0, bottom - 39); y <= bottom; y++) {
			int rowL = w, rowR = -1;
			for (int x = 0; x < w; x++)
				if (solid[y * w + x] && label[y * w + x] == biggest) { rowL = Math.Min(rowL, x); rowR = Math.Max(rowR, x); }
			if (rowR - rowL > right - left) { left = rowL; right = rowR; }
		}
		double scale = (double)BaseWidth / (right - left + 1);
		double centre = (left + right + 1) / 2.0;
		Write(srcBmp, px);

		var frame = new Bitmap(FrameW, FrameH, PixelFormat.Format32bppPArgb);
		using (Graphics g = Graphics.FromImage(frame)) {
			g.Clear(Color.Transparent);
			g.InterpolationMode = InterpolationMode.HighQualityBicubic;
			g.PixelOffsetMode = PixelOffsetMode.HighQuality;
			g.CompositingMode = CompositingMode.SourceCopy;
			float dx = (float)(FrameW / 2.0 - centre * scale);
			float dy = (float)(FrameH - (bottom + 1) * scale);
			g.DrawImage(srcBmp, new RectangleF(dx, dy, (float)(w * scale), (float)(h * scale)),
			    new RectangleF(0, 0, w, h), GraphicsUnit.Pixel);
		}
		srcBmp.Dispose();
		// Binary alpha: the game's sprites have no partial transparency. Half and over stays, un-premultiplied.
		var outBmp = frame.Clone(new Rectangle(0, 0, FrameW, FrameH), PixelFormat.Format32bppArgb);
		frame.Dispose();
		int[] o = Read(outBmp);
		for (int i = 0; i < o.Length; i++) {
			int a = (o[i] >> 24) & 255;
			if (a < 128) { o[i] = 0; continue; }
			o[i] = o[i] | unchecked((int)0xFF000000);
		}
		Write(outBmp, o);
		return outBmp;
	}

	static int[] Read(Bitmap b)
	{
		var data = b.LockBits(new Rectangle(0, 0, b.Width, b.Height), ImageLockMode.ReadOnly, PixelFormat.Format32bppArgb);
		var px = new int[b.Width * b.Height];
		for (int y = 0; y < b.Height; y++)
			System.Runtime.InteropServices.Marshal.Copy(data.Scan0 + y * data.Stride, px, y * b.Width, b.Width);
		b.UnlockBits(data);
		return px;
	}

	static void Write(Bitmap b, int[] px)
	{
		var data = b.LockBits(new Rectangle(0, 0, b.Width, b.Height), ImageLockMode.WriteOnly, PixelFormat.Format32bppArgb);
		for (int y = 0; y < b.Height; y++)
			System.Runtime.InteropServices.Marshal.Copy(px, y * b.Width, data.Scan0 + y * data.Stride, b.Width);
		b.UnlockBits(data);
	}
}
