/**
 * @file inv.h
 *
 * Interface of player inventory.
 */
#pragma once

#include <array>
#include <cstdint>

#include "engine/palette.h"
#include "engine/point.hpp"
#include "inv_iterators.hpp"
#include "items.h"
#include "player.h"

namespace devilution {

/**
 * @brief Forward declaration, not an include of spelldat.h.
 *
 * CanUseScroll and CanUseStaff below name SpellID, and this header did not say where it comes from -
 * it got away with that in Debug, where every translation unit reaching inv.h happened to have seen
 * spelldat.h first. The Release build's include order does not, and the fork's first Release build
 * failed here.
 *
 * Including spelldat.h fixes the symptom and creates a cycle: spelldat.h pulls in effects.h, which
 * comes back round to this header, so on the second entry the include guard hands spelldat.h an
 * empty file and its own SpellID goes undefined. A scoped enum with a fixed underlying type is a
 * complete type once declared, which is all a by-value parameter needs - so the declaration is
 * enough, and it adds no edge to the include graph.
 */
enum class SpellID : int16_t;

#define INV_SLOT_SIZE_PX 28
#define INV_SLOT_HALF_SIZE_PX (INV_SLOT_SIZE_PX / 2)
/** @brief Oracool V1: 10x7 with the new 320x660 window; see oracool/inventory_layout.h. */
constexpr Size InventorySizeInSlots { 10, 7 };
#define INV_ROW_SLOT_SIZE InventorySizeInSlots.width
constexpr Size InventorySlotSizeInPixels { INV_SLOT_SIZE_PX };

enum inv_item : int8_t {
	// clang-format off
	INVITEM_HEAD       = 0,
	INVITEM_RING_LEFT  = 1,
	INVITEM_RING_RIGHT = 2,
	INVITEM_AMULET     = 3,
	INVITEM_HAND_LEFT  = 4,
	INVITEM_HAND_RIGHT = 5,
	INVITEM_CHEST      = 6,
	// Oracool: the six new worn slots, in inv_body_loc order.
	INVITEM_SHOULDERS  = 7,
	INVITEM_BRACERS    = 8,
	INVITEM_GLOVES     = 9,
	INVITEM_WAIST      = 10,
	INVITEM_LEGS       = 11,
	INVITEM_BOOTS      = 12,
	// Derived rather than written as a literal: items.cpp's cursor-target lookup splits this same
	// index space with `cii >= NUM_INVLOC ? InvList[cii - NUM_INVLOC] : InvBody[cii]`, so the two
	// enums must agree on where the backpack starts or every inventory index is off by six.
	INVITEM_INV_FIRST  = NUM_INVLOC,
	// Oracool V1: 70 backpack cells (was 40), so everything after it shifts up by 30.
	INVITEM_INV_LAST   = INVITEM_INV_FIRST + InventoryGridCells - 1,
	INVITEM_BELT_FIRST = INVITEM_INV_LAST + 1,
	INVITEM_BELT_LAST  = INVITEM_BELT_FIRST + MaxBeltItems - 1,
	// clang-format on
};
static_assert(INVITEM_BELT_LAST <= INT8_MAX, "inv_item no longer fits in an int8_t");
static_assert(INVITEM_INV_FIRST == NUM_INVLOC, "inv_item and inv_body_loc disagree on the equipment range");

/**
 * identifiers for each of the inventory squares
 * @see InvRect
 */
enum inv_xy_slot : uint8_t {
	// clang-format off
	SLOTXY_HEAD           = 0,
	SLOTXY_EQUIPPED_FIRST = SLOTXY_HEAD,
	SLOTXY_RING_LEFT      = 1,
	SLOTXY_RING_RIGHT     = 2,
	SLOTXY_AMULET         = 3,
	SLOTXY_HAND_LEFT      = 4,
	SLOTXY_HAND_RIGHT     = 5,
	SLOTXY_CHEST          = 6,
	// Oracool: the six new worn slots. These indices MUST stay parallel to inv_body_loc - InvRect
	// is generated by walking inv_body_loc and asking inventory_layout.h for each slot's rect, so
	// a mismatch here would silently hit-test the wrong slot rather than fail to compile.
	SLOTXY_SHOULDERS      = 7,
	SLOTXY_BRACERS        = 8,
	SLOTXY_GLOVES         = 9,
	SLOTXY_WAIST          = 10,
	SLOTXY_LEGS           = 11,
	SLOTXY_BOOTS          = 12,
	SLOTXY_EQUIPPED_LAST  = SLOTXY_BOOTS,

	// regular inventory
	SLOTXY_INV_FIRST      = SLOTXY_EQUIPPED_LAST + 1,
	SLOTXY_INV_ROW1_FIRST = SLOTXY_INV_FIRST,
	SLOTXY_INV_ROW1_LAST  = SLOTXY_INV_FIRST + InventorySizeInSlots.width - 1,
	SLOTXY_INV_LAST       = SLOTXY_INV_FIRST + InventoryGridCells - 1,

	// belt items
	SLOTXY_BELT_FIRST     = SLOTXY_INV_LAST + 1,
	SLOTXY_BELT_LAST      = SLOTXY_BELT_FIRST + MaxBeltItems - 1,
	NUM_XY_SLOTS          = SLOTXY_BELT_LAST + 1
	// clang-format on
};
static_assert(NUM_XY_SLOTS <= UINT8_MAX + 1, "inv_xy_slot no longer fits in a uint8_t");

/**
 * @brief Whether @p slot is the leftmost cell of a backpack row (or of the belt).
 *
 * Oracool V1: replaces the old per-row SLOTXY_INV_ROW*_FIRST constants. Those enumerated all
 * four rows explicitly, which stopped scaling the moment the grid became seven rows deep -
 * every caller would have had to list three more. A modulo test says the same thing for any
 * number of rows.
 */
constexpr bool IsAtInvRowStart(int slot)
{
	if (slot == SLOTXY_BELT_FIRST)
		return true;
	if (slot < SLOTXY_INV_FIRST || slot > SLOTXY_INV_LAST)
		return false;
	return (slot - SLOTXY_INV_FIRST) % InventorySizeInSlots.width == 0;
}

/** @brief Whether @p slot is the rightmost cell of a backpack row (or of the belt). */
constexpr bool IsAtInvRowEnd(int slot)
{
	if (slot == SLOTXY_BELT_LAST)
		return true;
	if (slot < SLOTXY_INV_FIRST || slot > SLOTXY_INV_LAST)
		return false;
	return (slot - SLOTXY_INV_FIRST) % InventorySizeInSlots.width == InventorySizeInSlots.width - 1;
}

/** @brief Slot index of the leftmost cell of the backpack's last row. */
constexpr int SlotXyInvLastRowFirst = SLOTXY_INV_LAST - InventorySizeInSlots.width + 1;

enum item_color : uint8_t {
	// clang-format off
	ICOL_YELLOW = PAL16_YELLOW + 5,
	ICOL_WHITE  = PAL16_GRAY   + 5,
	ICOL_BLUE   = PAL16_BLUE   + 5,
	ICOL_RED    = PAL16_RED    + 5,
	// clang-format on
};

extern DVL_API_FOR_TEST bool invflag;
/**
 * @brief Panel-relative rect of every inventory slot. Generated in inv.cpp from
 * oracool/inventory_layout.h - see the comment there for why it is no longer a literal table.
 */
extern DVL_API_FOR_TEST const std::array<Rectangle, NUM_XY_SLOTS> InvRect;
/** @brief Oracool Tabbed Inventory: currently displayed backpack page (0 = original backpack). */
extern DVL_API_FOR_TEST int ActiveInventoryTab;
/**
 * @brief Oracool Tabbed Inventory: set by CheckInvHLight whenever the mouse is over an item in
 * an extra tab. pcursinvitem itself stays -1 for extra-tab items (legacy identify/drag/repair
 * code assumes tab-1 indices), but DrawInfoBox's "clear the info panel" condition also keys off
 * pcursinvitem == -1 - without this flag it would immediately wipe the info text CheckInvHLight
 * had just populated for an extra-tab item, exactly like it does for hovering nothing at all.
 */
extern DVL_API_FOR_TEST bool ActiveTabItemHovered;
/** @brief Whether Tabbed Inventory's UI/interaction should be active right now. */
bool TabbedInventoryEnabled();
/**
 * @brief Oracool Tabbed Inventory accessors: read/write the InvGrid cell, InvList item, or
 * item count for whichever backpack page ActiveInventoryTab currently selects (tab 0 = the
 * original, untouched InvGrid/InvList/_pNumInv; 1-9 = InvTabGrid/InvTabList/_pNumInvTab).
 * Exposed here (rather than kept file-local to inv.cpp) so tests can exercise tab isolation
 * directly.
 */
int8_t &GetActiveInvGridCell(Player &player, int cellIndex);
Item &GetActiveInvListItem(Player &player, int listIndex);
int &GetActiveNumInv(Player &player);
/** @brief Tab-aware equivalent of Player::RemoveInvItem; see that function for the compaction rules. */
void RemoveActiveInvItem(Player &player, int iv);
/** @brief Tab-index-parameterized equivalent of RemoveActiveInvItem; see that function for the rationale. */
void RemoveExtraTabItem(Player &player, int tabIndex, int iv);
/**
 * @brief Removes the first item matching the given identity from InvList or any extra tab.
 * @return true if a match was found and removed.
 */
bool RemoveMatchingInventoryOrExtraTabItem(Player &player, const Item &item);
/** @brief Tab-aware equivalent of AddItemToInvGrid; never network-syncs for an extra tab. */
void AddItemToActiveInvGrid(Player &player, int invGridIndex, int invListIndex, Size itemSize);
/** @brief Hit-tests the Tabbed Inventory tab buttons; switches ActiveInventoryTab and returns true if cursorPosition landed on one. */
bool CheckInventoryTabClick(Point cursorPosition);

void InvDrawSlotBack(const Surface &out, Point targetPosition, Size size, const Item &item);
/**
 * @brief Checks whether the given item can be placed on the belt. Takes item size as well as characteristics into account. Items
 * that cannot be placed on the belt have to be placed in the inventory instead.
 * @param item The item to be checked.
 * @return 'True' in case the item can be placed on the belt and 'False' otherwise.
 */
bool CanBePlacedOnBelt(const Item &item);

/**
 * @brief Function type which performs an operation on the given item.
 */
using ItemFunc = void (*)(Item &);

void CloseInventory();
void CloseStash();
void FreeInvGFX();
void InitInv();

/**
 * @brief Render the inventory panel to the given buffer.
 */
void DrawInv(const Surface &out);

/**
 * @brief Draws the inventory's gold readout. No-op unless the inventory is open.
 *
 * Separate from DrawInv, and called from scrollrt just BEFORE the orbs, because the mana orb
 * overlaps the band this sits in and is meant to cover it - see the definition for the geometry.
 */
void DrawInventoryFooter(const Surface &out);

void DrawInvBelt(const Surface &out);

/**
 * @brief Removes equipment from the specified location on the player's body.
 * @param player The player from which equipment will be removed.
 * @param bodyLocation The location from which equipment will be removed.
 * @param hiPri Priority of the network message to sync player equipment.
 */
void RemoveEquipment(Player &player, inv_body_loc bodyLocation, bool hiPri);

/**
 * @brief Single-player: leaves a 0-durability item equipped but inactive (CalcSelfItems skips
 * its stat bonuses) instead of destroying it, so it can be repaired at Griswold. Multiplayer:
 * unchanged vanilla behavior - calls RemoveEquipment exactly as before. Callers should call this
 * instead of RemoveEquipment at every durability-reaches-zero site.
 */
void BreakOrRemoveEquipment(Player &player, inv_body_loc bodyLocation, bool hiPri);

/**
 * @brief Checks whether or not auto-equipping behavior is enabled for the given player and item.
 * @param player The player to check.
 * @param item The item to check.
 * @return 'True' if auto-equipping behavior is enabled for the player and item and 'False' otherwise.
 */
bool AutoEquipEnabled(const Player &player, const Item &item);

/**
 * @brief Automatically attempts to equip the specified item in the most appropriate location in the player's body.
 * @note On success, this will broadcast an equipment_change event to let other players know about the equipment change.
 * @param player The player whose inventory will be checked for compatibility with the item.
 * @param item The item to equip.
 * @param persistItem Indicates whether or not the item should be persisted in the player's body. Pass 'False' to check
 * whether the player can equip the item but you don't want the item to actually be equipped. 'True' by default.
 * @return 'True' if the item was equipped and 'False' otherwise.
 */
bool AutoEquip(Player &player, const Item &item, bool persistItem = true);

/**
 * @brief Checks whether the given item can be placed on the specified player's inventory.
 * If 'persistItem' is 'True', the item is also placed in the inventory.
 * @param player The player whose inventory will be checked.
 * @param item The item to be checked.
 * @param persistItem Pass 'True' to actually place the item in the inventory. The default is 'False'.
 * @return 'True' in case the item can be placed on the player's inventory and 'False' otherwise.
 */
bool AutoPlaceItemInInventory(Player &player, const Item &item, bool persistItem = false);

/**
 * @brief Checks whether the given item can be placed on the specified player's inventory slot.
 * If 'persistItem' is 'True', the item is also placed in the inventory slot.
 * @param player The player whose inventory will be checked.
 * @param slotIndex The 0-based index of the slot to put the item on.
 * @param item The item to be checked.
 * @param persistItem Pass 'True' to actually place the item in the inventory slot. The default is 'False'.
 * @return 'True' in case the item can be placed on the specified player's inventory slot and 'False' otherwise.
 */
bool AutoPlaceItemInInventorySlot(Player &player, int slotIndex, const Item &item, bool persistItem);

/**
 * @brief The TOP-LEFT grid cell of active-tab list item @p iv (1-based), or -1 if not found.
 *
 * Exported for the test suite. This is the arithmetic the right-click equip swap rests on - the
 * displaced item is placed at the cell the equipped item vacated - and it is easy to get backwards,
 * because AddItemToInvGrid stores the positive list index at an item's BOTTOM-left cell while every
 * placement helper takes a top-left anchor. Getting it wrong places the displaced item a row or two
 * low, which fails silently and sends it to the far end of the bag instead.
 */
DVL_API_FOR_TEST int ActiveInvAnchorSlotOf(Player &player, int iv);

/**
 * @brief Whether the backpack item at @p listIndex on the DISPLAYED tab is the one under the cursor.
 *
 * Exported because getting this wrong is invisible: the socket rings and the hover outline are the
 * only things that read it, so a wrong answer looks like missing art rather than like a bug. It was
 * wrong for every extra tab until 1.11.081 - see the definition for why pcursinvitem alone cannot
 * answer it.
 */
DVL_API_FOR_TEST bool IsActiveInvItemHovered(int listIndex);

/**
 * @brief Oracool Tabbed Inventory fallback: tries every extra tab (2-10) for an area big enough
 * for item, once AutoPlaceItemInInventory (tab 1 only) has already failed. Never touches
 * ActiveInventoryTab - the displayed page stays whatever it already was.
 */
bool AutoPlaceItemInExtraTabs(Player &player, const Item &item, bool persistItem = false);

/**
 * @brief Checks whether the given item can be placed on the specified player's belt. Returns 'True' when the item can be placed
 * on belt slots and the player has at least one empty slot in his belt.
 * If 'persistItem' is 'True', the item is also placed in the belt.
 * @param player The player on whose belt will be checked.
 * @param item The item to be checked.
 * @param persistItem Pass 'True' to actually place the item in the belt. The default is 'False'.
 * @return 'True' in case the item can be placed on the player's belt and 'False' otherwise.
 */
bool AutoPlaceItemInBelt(Player &player, const Item &item, bool persistItem = false);

/**
 * @brief Calculate the maximum aditional gold that may fit in the user's inventory
 */
/**
 * @brief Free gold capacity across the backpack, in gold.
 *
 * int64_t because it does not fit in an int: MaxGold is 100,000,000 and the grid is 70 cells, so an
 * empty backpack answers 7,000,000,000. Callers comparing it against a cost must keep the
 * comparison in 64 bits - see StoreGoldFit.
 */
int64_t RoomForGold();

/**
 * @return The leftover amount that didn't fit, if any
 */
int AddGoldToInventory(Player &player, int value);
bool GoldAutoPlace(Player &player, Item &goldStack);
void CheckInvSwap(Player &player, inv_body_loc bLoc);
void inv_update_rem_item(Player &player, inv_body_loc iv);
void CheckInvSwap(Player &player, const Item &item, int invGridIndex);
void CheckInvRemove(Player &player, int invGridIndex);
void TransferItemToStash(Player &player, int location);
/**
 * @brief Oracool Tabbed Inventory: Ctrl+Click-to-stash equivalent of TransferItemToStash for an
 * item hovered in an extra tab (which has no pcursinvitem encoding - see CheckInvHLight). Hit-tests
 * the mouse against the active tab's grid directly instead of going through pcursinvitem. Returns
 * true if an extra-tab item was under the cursor (whether or not the transfer itself succeeded).
 */
bool TryTransferHoveredActiveTabItemToStash(Player &player);
/**
 * @brief Oracool: true for the single frame between a mouse-down hit on the sort button and the
 * corresponding mouse-up, purely for click-feedback color (the sort itself already runs
 * immediately on mouse-down, unlike the Reset Stats button's press-then-release model). Cleared in
 * diablo.cpp's LeftMouseUp, matching resetStatsButtonDown's own clearing pattern.
 */
extern bool inventorySortButtonDown;
/**
 * @brief Oracool: repacks the backpack (tab 1) and every extra inventory tab, most valuable item
 * first, filling tab 1 before spilling into tab 2 and so on. Gold and quest items (see
 * CanItemEnterExtraTab) are left exactly where they are - only genuinely relocatable items are
 * cleared and re-placed. Equipped items and the belt are untouched. Single-player only.
 */
void SortInventoryBySellValue(Player &player);
/**
 * @brief Hit-tests the inventory sort button and runs SortInventoryBySellValue if clicked.
 * @return true if the button was clicked (whether or not anything actually moved).
 */
bool CheckInventorySortButtonClick(Point cursorPosition);
void CheckInvItem(bool isShiftHeld = false, bool isCtrlHeld = false);

/**
 * @brief Picks up (or, with @p automaticMove, auto-moves) whatever sits under @p cursorPosition.
 *
 * Oracool: exported for RightMouseDown - a right-click inside the inventory window routes here
 * with automaticMove=true, which is the exact machinery shift-click uses: backpack equipment
 * auto-equips, a worn item auto-stashes into the backpack.
 */
void CheckInvCut(Player &player, Point cursorPosition, bool automaticMove, bool dropItem);

/**
 * Check for interactions with belt
 */
void CheckInvScrn(bool isShiftHeld, bool isCtrlHeld);
void InvGetItem(Player &player, int ii);

/**
 * @brief Returns the first free space that can take an item preferencing tiles in front of the current position
 *
 * The search starts with the adjacent tile in the desired direction and alternates sides until it ends up checking the
 * opposite tile, before finally checking the origin tile
 *
 * @param origin center tile of the search space
 * @param facing direction of the adjacent tile to check first
 * @return the first valid point or an empty optional
 */
std::optional<Point> FindAdjacentPositionForItem(Point origin, Direction facing);
void AutoGetItem(Player &player, Item *itemPointer, int ii);

/**
 * @brief Searches for a dropped item with the same type/createInfo/seed
 * @param iseed The value used to initialise the RNG when generating the item
 * @param idx The overarching type of the target item
 * @param ci Flags used to describe the specific subtype of the target item
 * @return An index into ActiveItems or -1 if no matching item was found
 */
int FindGetItem(uint32_t iseed, _item_indexes idx, uint16_t ci);
void SyncGetItem(Point position, uint32_t iseed, _item_indexes idx, uint16_t ci);

/**
 * @brief Checks if the tile has room for an item
 * @param position tile coordinates
 * @return True if the space is free of obstructions, false if blocked
 */
bool CanPut(Point position);

int ClampDurability(const Item &item, int durability);
int16_t ClampToHit(const Item &item, int16_t toHit);
uint8_t ClampMaxDam(const Item &item, uint8_t maxDam);
int SyncDropItem(Point position, _item_indexes idx, uint16_t icreateinfo, int iseed, int id, int dur, int mdur, int ch, int mch, int ivalue, uint32_t ibuff, int toHit, int maxDam);
int SyncDropEar(Point position, uint16_t icreateinfo, uint32_t iseed, uint8_t cursval, string_view heroname);
int8_t CheckInvHLight();
bool CanUseScroll(Player &player, SpellID spell);
void ConsumeStaffCharge(Player &player);
bool CanUseStaff(Player &player, SpellID spellId);
Item &GetInventoryItem(Player &player, int location);
bool UseInvItem(int cii);

/**
 * @brief Opens the stack-split dialog for the stackable consumable at inventory-or-belt
 * index cii, if it has more than one unit. Otherwise does nothing.
 *
 * @return Whether the dialog was opened.
 */
bool TryStartStackSplit(int cii);
void DoTelekinesis();
int CalculateGold(Player &player);

/**
 * @brief Gets the size, in inventory cells, of the given item.
 * @param item The item whose size is to be determined.
 * @return The size, in inventory cells, of the item.
 */
Size GetInventorySize(const Item &item);

/**
 * @brief Checks whether the player has an inventory item matching the predicate.
 */
template <typename Predicate>
bool HasInventoryItem(Player &player, Predicate &&predicate)
{
	const InventoryPlayerItemsRange items { player };
	return std::find_if(items.begin(), items.end(), std::forward<Predicate>(predicate)) != items.end();
}

/**
 * @brief Checks whether the player has a belt item matching the predicate.
 */
template <typename Predicate>
bool HasBeltItem(Player &player, Predicate &&predicate)
{
	const BeltPlayerItemsRange items { player };
	return std::find_if(items.begin(), items.end(), std::forward<Predicate>(predicate)) != items.end();
}

/**
 * @brief Checks whether the player has an inventory or a belt item matching the predicate.
 */
template <typename Predicate>
bool HasInventoryOrBeltItem(Player &player, Predicate &&predicate)
{
	return HasInventoryItem(player, predicate) || HasBeltItem(player, predicate);
}

/**
 * @brief Checks whether the player has an inventory item with the given ID (IDidx).
 */
inline bool HasInventoryItemWithId(Player &player, _item_indexes id)
{
	return HasInventoryItem(player, [id](const Item &item) {
		return item.IDidx == id;
	});
}

/**
 * @brief Checks whether the player has a belt item with the given ID (IDidx).
 */
inline bool HasBeltItemWithId(Player &player, _item_indexes id)
{
	return HasBeltItem(player, [id](const Item &item) {
		return item.IDidx == id;
	});
}

/**
 * @brief Checks whether the player has an inventory or a belt item with the given ID (IDidx).
 */
inline bool HasInventoryOrBeltItemWithId(Player &player, _item_indexes id)
{
	return HasInventoryItemWithId(player, id) || HasBeltItemWithId(player, id);
}

/**
 * @brief Removes the first inventory item matching the predicate.
 *
 * @return Whether an item was found and removed.
 */
template <typename Predicate>
bool RemoveInventoryItem(Player &player, Predicate &&predicate)
{
	const InventoryPlayerItemsRange items { player };
	const auto it = std::find_if(items.begin(), items.end(), std::forward<Predicate>(predicate));
	if (it == items.end())
		return false;
	// Oracool Tabbed Inventory: InventoryPlayerItemsRange now flattens InvList and every extra
	// tab into one iteration (containerIndex() 0 = InvList, 1..9 = InvTabList[0..8]), so removal
	// has to route to whichever container the match actually came from.
	if (it.containerIndex() == 0) {
		player.RemoveInvItem(static_cast<int>(it.index()));
	} else {
		RemoveExtraTabItem(player, static_cast<int>(it.containerIndex() - 1), static_cast<int>(it.index()));
	}
	return true;
}

/**
 * @brief Removes the first belt item matching the predicate.
 *
 * @return Whether an item was found and removed.
 */
template <typename Predicate>
bool RemoveBeltItem(Player &player, Predicate &&predicate)
{
	const BeltPlayerItemsRange items { player };
	const auto it = std::find_if(items.begin(), items.end(), std::forward<Predicate>(predicate));
	if (it == items.end())
		return false;
	player.RemoveSpdBarItem(static_cast<int>(it.index()));
	return true;
}

/**
 * @brief Removes the first inventory or belt item matching the predicate.
 *
 * @return Whether an item was found and removed.
 */
template <typename Predicate>
bool RemoveInventoryOrBeltItem(Player &player, Predicate &&predicate)
{
	return RemoveInventoryItem(player, predicate) || RemoveBeltItem(player, predicate);
}

/**
 * @brief Removes the first inventory item with the given id (IDidx).
 *
 * @return Whether an item was found and removed.
 */
inline bool RemoveInventoryItemById(Player &player, _item_indexes id)
{
	return RemoveInventoryItem(player, [id](const Item &item) {
		return item.IDidx == id;
	});
}

/**
 * @brief Removes the first belt item with the given id (IDidx).
 *
 * @return Whether an item was found and removed.
 */
inline bool RemoveBeltItemById(Player &player, _item_indexes id)
{
	return RemoveBeltItem(player, [id](const Item &item) {
		return item.IDidx == id;
	});
}

/**
 * @brief Removes the first inventory or belt item with the given id (IDidx).
 *
 * @return Whether an item was found and removed.
 */
inline bool RemoveInventoryOrBeltItemById(Player &player, _item_indexes id)
{
	return RemoveInventoryItemById(player, id) || RemoveBeltItemById(player, id);
}

/**
 * @brief Decrements a stackable consumable's count by one, removing the inventory
 * slot only when the count reaches zero (or the item isn't a stackable consumable).
 */
/**
 * @brief tabIdx selects an Oracool Tabbed Inventory extra tab (0-8) instead of InvList - pass -1
 * (the default) for the original InvList-only behavior.
 */
void DecrementOrRemoveInvItem(Player &player, int invIndex, int tabIdx = -1);

/**
 * @brief Decrements a stackable consumable's count by one, removing the belt slot
 * only when the count reaches zero (or the item isn't a stackable consumable).
 */
void DecrementOrRemoveSpdBarItem(Player &player, int spdIndex);

/**
 * @brief Belt Mod: refills an already-empty belt slot by pulling one or more matching
 * stackable-consumable stacks out of inventory (scan order, capped at Item::MaxStackCount),
 * removing any inventory stack it fully drains. No-op if nothing in inventory matches.
 *
 * @param spdIndex Index of the belt slot to refill; must already be empty.
 * @param idx Base item of the consumable that previously occupied the slot.
 * @param identified Identified state of the consumable that previously occupied the slot.
 */
void RefillBeltSlotFromInventory(Player &player, int spdIndex, _item_indexes idx, bool identified);

/**
 * @brief Finds the first inventory item matching the predicate and decrements its
 * stack count by one, removing the slot only when the count reaches zero.
 *
 * @return Whether a matching item was found.
 */
template <typename Predicate>
bool DecrementOrRemoveInventoryItem(Player &player, Predicate &&predicate)
{
	const InventoryPlayerItemsRange items { player };
	const auto it = std::find_if(items.begin(), items.end(), std::forward<Predicate>(predicate));
	if (it == items.end())
		return false;
	// Oracool Tabbed Inventory: see the equivalent comment in RemoveInventoryItem above.
	if (it.containerIndex() == 0) {
		DecrementOrRemoveInvItem(player, static_cast<int>(it.index()));
	} else {
		DecrementOrRemoveInvItem(player, static_cast<int>(it.index()), static_cast<int>(it.containerIndex() - 1));
	}
	return true;
}

/**
 * @brief Finds the first belt item matching the predicate and decrements its stack
 * count by one, removing the slot only when the count reaches zero.
 *
 * @return Whether a matching item was found.
 */
template <typename Predicate>
bool DecrementOrRemoveBeltItem(Player &player, Predicate &&predicate)
{
	const BeltPlayerItemsRange items { player };
	const auto it = std::find_if(items.begin(), items.end(), std::forward<Predicate>(predicate));
	if (it == items.end())
		return false;
	DecrementOrRemoveSpdBarItem(player, static_cast<int>(it.index()));
	return true;
}

/**
 * @brief Finds the first inventory or belt item matching the predicate and
 * decrements its stack count by one, removing the slot only when the count
 * reaches zero.
 *
 * @return Whether a matching item was found.
 */
template <typename Predicate>
bool DecrementOrRemoveInventoryOrBeltItem(Player &player, Predicate &&predicate)
{
	return DecrementOrRemoveInventoryItem(player, predicate) || DecrementOrRemoveBeltItem(player, predicate);
}

/**
 * @brief Removes the first inventory or belt scroll with the player's current spell.
 */
void ConsumeScroll(Player &player);

/* data */

} // namespace devilution
