/**
 * @file itemdat.h
 *
 * Interface of all item data.
 */
#pragma once

#include <cstdint>

#include "objdat.h"
#include "spelldat.h"
#include "utils/attributes.h"
#include "utils/stdcompat/string_view.hpp"

namespace devilution {

/** @todo add missing values and apply */
enum _item_indexes : int16_t { // TODO defines all indexes in AllItemsList
	IDI_GOLD,
	IDI_WARRIOR,
	IDI_WARRSHLD,
	IDI_WARRCLUB,
	IDI_ROGUE,
	IDI_SORCERER,
	IDI_CLEAVER,
	IDI_FIRSTQUEST = IDI_CLEAVER,
	IDI_SKCROWN,
	IDI_INFRARING,
	IDI_ROCK,
	IDI_OPTAMULET,
	IDI_TRING,
	IDI_BANNER,
	IDI_HARCREST,
	IDI_STEELVEIL,
	IDI_GLDNELIX,
	IDI_ANVIL,
	IDI_MUSHROOM,
	IDI_BRAIN,
	IDI_FUNGALTM,
	IDI_SPECELIX,
	IDI_BLDSTONE,
	IDI_MAPOFDOOM,
	IDI_LASTQUEST = IDI_MAPOFDOOM,
	IDI_EAR,
	IDI_HEAL,
	IDI_MANA,
	IDI_IDENTIFY,
	IDI_PORTAL,
	IDI_ARMOFVAL,
	IDI_FULLHEAL,
	IDI_FULLMANA,
	IDI_GRISWOLD,
	IDI_LGTFORGE,
	IDI_LAZSTAFF,
	IDI_RESURRECT,
	IDI_OIL,
	IDI_SHORTSTAFF,
	IDI_BARDSWORD,
	IDI_BARDDAGGER,
	IDI_RUNEBOMB,
	IDI_THEODORE,
	IDI_AURIC,
	IDI_NOTE1,
	IDI_NOTE2,
	IDI_NOTE3,
	IDI_FULLNOTE,
	IDI_BROWNSUIT,
	IDI_GREYSUIT,
	IDI_BOOK1 = 114,
	IDI_BOOK2,
	IDI_BOOK3,
	IDI_BOOK4,
	IDI_BARBARIAN = 139,
	IDI_RUNEOFSTONE = 165,
	IDI_SORCERER_DIABLO,
	IDI_ARENAPOT,

	// Oracool: user request - one test item per new worn type, the leather tier of each.
	//
	// Named rather than left as anonymous IDROP_REGULAR rows because IsItemAvailable() rejects
	// anything past IDI_LAST outright, so an unnamed entry at the end of AllItemsList would exist
	// in the table and never be generated by anything. Appended after IDI_ARENAPOT so no existing
	// index moves - these are positional, and every save stores them.
	IDI_ORACOOL_SHOULDERS,
	IDI_ORACOOL_BRACERS,
	IDI_ORACOOL_GLOVES,
	IDI_ORACOOL_BELT,
	IDI_ORACOOL_LEGS,
	IDI_ORACOOL_BOOTS,

	// Oracool: user request - a new ILOC_HELM item, deliberately NOT part of the leather set above.
	// Unlike those six, ILOC_HELM already exists in vanilla Diablo (Cap/Skull Cap/Helm/Full
	// Helm/Great Helm all share it), so this is an ordinary new item at an ordinary slot - no new
	// ILOC_*/SLOTXY_*/paperdoll plumbing required, just a table row plus its own icon.
	IDI_ORACOOL_HELM,

	// Oracool: user request - "ship every item you harvest from these files... name them,
	// categorize them... give them adequate stats and make them part of the game." Two armor-
	// slot items (no Oracool item previously existed at ILOC_ARMOR/ILOC_ONEHAND-shield) plus a
	// full eight-tier progression across all nine worn/armor/shield slots, sourced from eight
	// green-screen composite sheets ("Iron Set", "Steel Set", etc.). Iron tier has no separate
	// helm entry - IDI_ORACOOL_HELM above already fills that role; its icon was re-sourced from
	// the matching Iron Set sheet for visual consistency with the rest of that tier instead of
	// duplicating the item. Tier order (Iron < Steel < Crusader < Bone < Royal < Obsidian <
	// Infernal < Diamond) and every stat are a judgment call, not a balance pass - see the dev
	// report for the formula.
	IDI_ORACOOL_LEATHER_ARMOR,
	IDI_ORACOOL_LEATHER_SHIELD,

	IDI_ORACOOL_IRON_GLOVES,
	IDI_ORACOOL_IRON_SHOULDERS,
	IDI_ORACOOL_IRON_BRACERS,
	IDI_ORACOOL_IRON_BELT,
	IDI_ORACOOL_IRON_LEGS,
	IDI_ORACOOL_IRON_BOOTS,
	IDI_ORACOOL_IRON_ARMOR,
	IDI_ORACOOL_IRON_SHIELD,
	IDI_ORACOOL_STEEL_GLOVES,
	IDI_ORACOOL_STEEL_SHOULDERS,
	IDI_ORACOOL_STEEL_BRACERS,
	IDI_ORACOOL_STEEL_BELT,
	IDI_ORACOOL_STEEL_LEGS,
	IDI_ORACOOL_STEEL_BOOTS,
	IDI_ORACOOL_STEEL_ARMOR,
	IDI_ORACOOL_STEEL_SHIELD,
	IDI_ORACOOL_STEEL_HELM,
	IDI_ORACOOL_CRUSADER_GLOVES,
	IDI_ORACOOL_CRUSADER_SHOULDERS,
	IDI_ORACOOL_CRUSADER_BRACERS,
	IDI_ORACOOL_CRUSADER_BELT,
	IDI_ORACOOL_CRUSADER_LEGS,
	IDI_ORACOOL_CRUSADER_BOOTS,
	IDI_ORACOOL_CRUSADER_ARMOR,
	IDI_ORACOOL_CRUSADER_SHIELD,
	IDI_ORACOOL_CRUSADER_HELM,
	IDI_ORACOOL_BONE_GLOVES,
	IDI_ORACOOL_BONE_SHOULDERS,
	IDI_ORACOOL_BONE_BRACERS,
	IDI_ORACOOL_BONE_BELT,
	IDI_ORACOOL_BONE_LEGS,
	IDI_ORACOOL_BONE_BOOTS,
	IDI_ORACOOL_BONE_ARMOR,
	IDI_ORACOOL_BONE_SHIELD,
	IDI_ORACOOL_BONE_HELM,
	IDI_ORACOOL_ROYAL_GLOVES,
	IDI_ORACOOL_ROYAL_SHOULDERS,
	IDI_ORACOOL_ROYAL_BRACERS,
	IDI_ORACOOL_ROYAL_BELT,
	IDI_ORACOOL_ROYAL_LEGS,
	IDI_ORACOOL_ROYAL_BOOTS,
	IDI_ORACOOL_ROYAL_ARMOR,
	IDI_ORACOOL_ROYAL_SHIELD,
	IDI_ORACOOL_ROYAL_HELM,
	IDI_ORACOOL_OBSIDIAN_GLOVES,
	IDI_ORACOOL_OBSIDIAN_SHOULDERS,
	IDI_ORACOOL_OBSIDIAN_BRACERS,
	IDI_ORACOOL_OBSIDIAN_BELT,
	IDI_ORACOOL_OBSIDIAN_LEGS,
	IDI_ORACOOL_OBSIDIAN_BOOTS,
	IDI_ORACOOL_OBSIDIAN_ARMOR,
	IDI_ORACOOL_OBSIDIAN_SHIELD,
	IDI_ORACOOL_OBSIDIAN_HELM,
	IDI_ORACOOL_INFERNAL_GLOVES,
	IDI_ORACOOL_INFERNAL_SHOULDERS,
	IDI_ORACOOL_INFERNAL_BRACERS,
	IDI_ORACOOL_INFERNAL_BELT,
	IDI_ORACOOL_INFERNAL_LEGS,
	IDI_ORACOOL_INFERNAL_BOOTS,
	IDI_ORACOOL_INFERNAL_ARMOR,
	IDI_ORACOOL_INFERNAL_SHIELD,
	IDI_ORACOOL_INFERNAL_HELM,
	IDI_ORACOOL_DIAMOND_GLOVES,
	IDI_ORACOOL_DIAMOND_SHOULDERS,
	IDI_ORACOOL_DIAMOND_BRACERS,
	IDI_ORACOOL_DIAMOND_BELT,
	IDI_ORACOOL_DIAMOND_LEGS,
	IDI_ORACOOL_DIAMOND_BOOTS,
	IDI_ORACOOL_DIAMOND_ARMOR,
	IDI_ORACOOL_DIAMOND_SHIELD,
	IDI_ORACOOL_DIAMOND_HELM,

	IDI_ORACOOL_RUBY_GLOVES,
	IDI_ORACOOL_RUBY_SHOULDERS,
	IDI_ORACOOL_RUBY_BRACERS,
	IDI_ORACOOL_RUBY_BELT,
	IDI_ORACOOL_RUBY_LEGS,
	IDI_ORACOOL_RUBY_BOOTS,
	IDI_ORACOOL_RUBY_ARMOR,
	IDI_ORACOOL_RUBY_SHIELD,
	IDI_ORACOOL_RUBY_HELM,
	IDI_ORACOOL_ONYX_GLOVES,
	IDI_ORACOOL_ONYX_SHOULDERS,
	IDI_ORACOOL_ONYX_BRACERS,
	IDI_ORACOOL_ONYX_BELT,
	IDI_ORACOOL_ONYX_LEGS,
	IDI_ORACOOL_ONYX_BOOTS,
	IDI_ORACOOL_ONYX_ARMOR,
	IDI_ORACOOL_ONYX_SHIELD,
	IDI_ORACOOL_ONYX_HELM,
	IDI_ORACOOL_GLACIAL_GLOVES,
	IDI_ORACOOL_GLACIAL_SHOULDERS,
	IDI_ORACOOL_GLACIAL_BRACERS,
	IDI_ORACOOL_GLACIAL_BELT,
	IDI_ORACOOL_GLACIAL_LEGS,
	IDI_ORACOOL_GLACIAL_BOOTS,
	IDI_ORACOOL_GLACIAL_ARMOR,
	IDI_ORACOOL_GLACIAL_SHIELD,
	IDI_ORACOOL_GLACIAL_HELM,
	IDI_ORACOOL_CYBORG_GLOVES,
	IDI_ORACOOL_CYBORG_SHOULDERS,
	IDI_ORACOOL_CYBORG_BRACERS,
	IDI_ORACOOL_CYBORG_BELT,
	IDI_ORACOOL_CYBORG_LEGS,
	IDI_ORACOOL_CYBORG_BOOTS,
	IDI_ORACOOL_CYBORG_ARMOR,
	IDI_ORACOOL_CYBORG_SHIELD,
	IDI_ORACOOL_CYBORG_HELM,
	IDI_ORACOOL_FALLEN_GLOVES,
	IDI_ORACOOL_FALLEN_SHOULDERS,
	IDI_ORACOOL_FALLEN_BRACERS,
	IDI_ORACOOL_FALLEN_BELT,
	IDI_ORACOOL_FALLEN_LEGS,
	IDI_ORACOOL_FALLEN_BOOTS,
	IDI_ORACOOL_FALLEN_ARMOR,
	IDI_ORACOOL_FALLEN_SHIELD,
	IDI_ORACOOL_FALLEN_HELM,
	IDI_ORACOOL_SERAPHIC_GLOVES,
	IDI_ORACOOL_SERAPHIC_SHOULDERS,
	IDI_ORACOOL_SERAPHIC_BRACERS,
	IDI_ORACOOL_SERAPHIC_BELT,
	IDI_ORACOOL_SERAPHIC_LEGS,
	IDI_ORACOOL_SERAPHIC_BOOTS,
	IDI_ORACOOL_SERAPHIC_ARMOR,
	IDI_ORACOOL_SERAPHIC_SHIELD,
	IDI_ORACOOL_SERAPHIC_HELM,
	IDI_ORACOOL_SPECTRAL_GLOVES,
	IDI_ORACOOL_SPECTRAL_SHOULDERS,
	IDI_ORACOOL_SPECTRAL_BRACERS,
	IDI_ORACOOL_SPECTRAL_BELT,
	IDI_ORACOOL_SPECTRAL_LEGS,
	IDI_ORACOOL_SPECTRAL_BOOTS,
	IDI_ORACOOL_SPECTRAL_ARMOR,
	IDI_ORACOOL_SPECTRAL_SHIELD,
	IDI_ORACOOL_SPECTRAL_HELM,
	// Megaplan Phase 1: the five socketable gems. Appended so no existing index moves (positional,
	// stored by every save); excluded from the droppable-item pool for the same save-format reason
	// as the product lines (see GetItemIndexForDroppableItem) and dropped via their own hook.
	IDI_ORACOOL_GEM_RUBY,
	IDI_ORACOOL_GEM_SAPPHIRE,
	IDI_ORACOOL_GEM_TOPAZ,
	IDI_ORACOOL_GEM_EMERALD,
	IDI_ORACOOL_GEM_SKULL,
	// Phase 1 charms: passives that work from the backpack (the first CharmActiveCap of them -
	// see oracool/charms.h). Same append/pool-exclusion/own-hook contract as the gems above.
	IDI_ORACOOL_CHARM_VIGOR,
	IDI_ORACOOL_CHARM_EMBERS,
	IDI_ORACOOL_CHARM_STORMS,
	IDI_ORACOOL_CHARM_FORTUNE,
	// Phase 1 runes: socketables like the gems, smaller alone - their real power is runeWORDS
	// (oracool/runewords.h): the right sequence in a fully socketed plain item transforms it.
	IDI_ORACOOL_RUNE_EL,
	IDI_ORACOOL_RUNE_TIR,
	IDI_ORACOOL_RUNE_RAL,
	IDI_ORACOOL_RUNE_ORT,
	IDI_ORACOOL_RUNE_SOL,
	// Phase 1 Magic/Gold Find charms. APPENDED after the runes rather than beside their siblings,
	// because these indices are positional save format - inserting would renumber every rune in
	// every save. IsOracoolCharmIdx covers both islands.
	IDI_ORACOOL_CHARM_LUCK,
	IDI_ORACOOL_CHARM_GREED,
	// The gem quality ladder (Gems.png, 2026-08-16): Diablo II's seven types in five qualities.
	// The five above are the NORMAL quality of their type and keep their indices - these are the
	// thirty that complete the set, appended for the same positional-save-format reason as every
	// other block here. oracool/gems.h owns the (type, quality) -> index table; nothing outside it
	// should assume this list's order.
	IDI_ORACOOL_GEM_AMETHYST_CHIPPED,
	IDI_ORACOOL_GEM_AMETHYST_FLAWED,
	IDI_ORACOOL_GEM_AMETHYST_NORMAL,
	IDI_ORACOOL_GEM_AMETHYST_FLAWLESS,
	IDI_ORACOOL_GEM_AMETHYST_PERFECT,
	IDI_ORACOOL_GEM_DIAMOND_CHIPPED,
	IDI_ORACOOL_GEM_DIAMOND_FLAWED,
	IDI_ORACOOL_GEM_DIAMOND_NORMAL,
	IDI_ORACOOL_GEM_DIAMOND_FLAWLESS,
	IDI_ORACOOL_GEM_DIAMOND_PERFECT,
	IDI_ORACOOL_GEM_EMERALD_CHIPPED,
	IDI_ORACOOL_GEM_EMERALD_FLAWED,
	IDI_ORACOOL_GEM_EMERALD_FLAWLESS,
	IDI_ORACOOL_GEM_EMERALD_PERFECT,
	IDI_ORACOOL_GEM_RUBY_CHIPPED,
	IDI_ORACOOL_GEM_RUBY_FLAWED,
	IDI_ORACOOL_GEM_RUBY_FLAWLESS,
	IDI_ORACOOL_GEM_RUBY_PERFECT,
	IDI_ORACOOL_GEM_SAPPHIRE_CHIPPED,
	IDI_ORACOOL_GEM_SAPPHIRE_FLAWED,
	IDI_ORACOOL_GEM_SAPPHIRE_FLAWLESS,
	IDI_ORACOOL_GEM_SAPPHIRE_PERFECT,
	IDI_ORACOOL_GEM_TOPAZ_CHIPPED,
	IDI_ORACOOL_GEM_TOPAZ_FLAWED,
	IDI_ORACOOL_GEM_TOPAZ_FLAWLESS,
	IDI_ORACOOL_GEM_TOPAZ_PERFECT,
	IDI_ORACOOL_GEM_SKULL_CHIPPED,
	IDI_ORACOOL_GEM_SKULL_FLAWED,
	IDI_ORACOOL_GEM_SKULL_FLAWLESS,
	IDI_ORACOOL_GEM_SKULL_PERFECT,
	// Sockets v2: the other 28 Diablo II runes. GENERATED by tools/GenRunes.ps1 together with their
	// icon ids, CEL frame sizes, cut specs and effect rows - one walk, one order. Appended here
	// because item indices are positional save format: the five that shipped in v1.7.8 cannot move.
#include "oracool/runes_enum.inc"
	// Salvage: the seven materials the Levski recipes break gear down into. GENERATED by
	// tools/GenSalvageMaterials.ps1 in one walk with their icons, frame sizes and table rows.
	// Appended, like everything before them, because item indices are positional save format.
#include "oracool/salvage_enum.inc"
	// Charms of Salvaging: one per salvage tier. Same generator, same walk, appended after the
	// materials so both families stay contiguous and the CEL frame order matches the ICURS order.
#include "oracool/salvage_charm_enum.inc"
	IDI_LAST = IDI_ORACOOL_CHARM_SALVAGE_ETHEREAL_IMBUEITIES,
	IDI_NONE = -1,
};

/**
 * @brief Whether @p i is one of Oracool's own added item indexes (the six worn types plus any
 * other custom item appended after them, currently just IDI_ORACOOL_HELM).
 *
 * Used by loadsave.cpp's save-remap guard, which needs this exact range for a completely
 * different reason (these ids must NOT be treated as Hellfire-exclusive) than the one this header
 * comment might suggest - see IsOracoolItemIdx's caller in loadsave.cpp for that story.
 * items.cpp's DebugSpawnItem bounds its own direct-match loop to the same range for a third
 * reason (IDROP_NEVER items are structurally unreachable through the normal random-reroll
 * search); kept as one named range here instead of three hand-copied bounds so the three call
 * sites can't quietly drift apart the next time this range grows - which it just did, from
 * IDI_ORACOOL_HELM to IDI_ORACOOL_DIAMOND_HELM, adding the leather armor/shield items and the
 * eight-tier set expansion in one jump.
 */
constexpr bool IsOracoolItemIdx(int i)
{
	return i >= IDI_ORACOOL_SHOULDERS && i <= IDI_ORACOOL_SPECTRAL_HELM;
}

/** @brief Phase 1: whether @p i is a socketable gem. Same pool-exclusion contract as the range
 * above - a gem never joins the seeded recreation pool. Two islands: the original five (which are
 * the normal quality of their type) and the thirty appended with the quality ladder. */
constexpr bool IsOracoolGemIdx(int i)
{
	return (i >= IDI_ORACOOL_GEM_RUBY && i <= IDI_ORACOOL_GEM_SKULL)
	    || (i >= IDI_ORACOOL_GEM_AMETHYST_CHIPPED && i <= IDI_ORACOOL_GEM_SKULL_PERFECT);
}

/**
 * @brief Whether @p i is a Charm of Salvaging - one per salvage tier, appended after the seven
 * materials, so one contiguous island.
 *
 * These are charms in every structural sense and IsOracoolCharmIdx below includes them, which is
 * deliberate: the CharmActiveCap rule then applies to them too, so at most three salvage tiers can
 * be armed at once and a salvage charm competes for the same three live slots as a stat charm.
 * They carry no stat bonus - their whole effect happens at PICKUP time (oracool/salvage.cpp), not
 * in the stat sheet, so ApplyCharmToTotals leaves them inert by finding no row for them.
 */
constexpr bool IsOracoolSalvageCharmIdx(int i)
{
	return i >= IDI_ORACOOL_CHARM_SALVAGE_WHITE_SCALES && i <= IDI_ORACOOL_CHARM_SALVAGE_ETHEREAL_IMBUEITIES;
}

/** @brief Phase 1: whether @p i is a charm. Three islands now - see the enum's append-only note. */
constexpr bool IsOracoolCharmIdx(int i)
{
	return (i >= IDI_ORACOOL_CHARM_VIGOR && i <= IDI_ORACOOL_CHARM_FORTUNE)
	    || i == IDI_ORACOOL_CHARM_LUCK || i == IDI_ORACOOL_CHARM_GREED
	    || IsOracoolSalvageCharmIdx(i);
}

/** @brief Whether @p i is a rune. Socketable like a gem; see oracool/runewords.h. Two islands, for
 * the same reason the gems and charms have two: the five that shipped in v1.7.8 keep their indices
 * because item indices are positional save format, and the other 28 are appended at the end. */
constexpr bool IsOracoolRuneIdx(int i)
{
	return (i >= IDI_ORACOOL_RUNE_EL && i <= IDI_ORACOOL_RUNE_SOL)
	    || (i >= IDI_ORACOOL_RUNE_ELD && i <= IDI_ORACOOL_RUNE_ZOD);
}

/**
 * @brief Whether @p i is one of the seven salvage materials.
 *
 * ONE island, unlike the gems, charms and runes: these arrived together and nothing has been
 * appended after them, so the range is contiguous and stays that way as long as new families are
 * appended rather than inserted - which positional save format requires anyway.
 *
 * Materials are NOT socketable. They share ICLASS_MISC/IMISC_NONE with the runes because that is
 * what makes them stack and sort through the same code, but nothing routes them to a socket: the
 * socket paths test IsOracoolGemIdx || IsOracoolRuneIdx, and this is neither.
 */
constexpr bool IsOracoolSalvageIdx(int i)
{
	return i >= IDI_ORACOOL_SALVAGE_WHITE_SCALES && i <= IDI_ORACOOL_SALVAGE_ETHEREAL_IMBUEITIES;
}

/**
 * @brief Whether @p i is ANY id this fork appended to the vanilla+Hellfire table - the worn/tier
 * lines, the gems, the charms, the runes, and whatever is appended after them (the enum's tail is
 * append-only and contiguously Oracool's from IDI_ORACOOL_SHOULDERS to IDI_LAST by construction).
 *
 * This is the predicate the save-remap guards in loadsave.cpp want: every appended id must pass
 * through the Diablo/Spawn remaps AS ITSELF, because none of them exist in the vanilla numbering
 * and the "Hellfire exclusive" bands there would otherwise map them to -1 - the empty-slot marker,
 * which destroys the item at save time. That exact bug shipped once for the worn types (see
 * RemapItemIdxToDiablo's comment) and then AGAIN for the gems/charms/runes, because the remaps
 * tested the narrower IsOracoolItemIdx while the enum grew past it (external audit, 2026-08-17).
 * A whole-tail range cannot be outgrown by appending.
 */
constexpr bool IsOracoolAddedIdx(int i)
{
	return i >= IDI_ORACOOL_SHOULDERS && i <= IDI_LAST;
}

enum item_drop_rate : uint8_t {
	IDROP_NEVER,
	IDROP_REGULAR,
	IDROP_DOUBLE,
};

enum item_class : uint8_t {
	ICLASS_NONE,
	ICLASS_WEAPON,
	ICLASS_ARMOR,
	ICLASS_MISC,
	ICLASS_GOLD,
	ICLASS_QUEST,
};

enum item_equip_type : int8_t {
	ILOC_NONE,
	ILOC_ONEHAND,
	ILOC_TWOHAND,
	ILOC_ARMOR,
	ILOC_HELM,
	ILOC_RING,
	ILOC_AMULET,
	ILOC_UNEQUIPABLE,
	/** @brief Goes in the potion belt. NOT the worn waist slot - that is ILOC_WAIST below. */
	ILOC_BELT,
	// Oracool: user request - six new worn slots. ILOC_WAIST is named for the body part rather
	// than the item precisely because ILOC_BELT above already means "stackable thing that goes in
	// the potion belt"; a slot called ILOC_BELT would read as that and be wrong every time.
	ILOC_SHOULDERS,
	ILOC_BRACERS,
	ILOC_GLOVES,
	ILOC_WAIST,
	ILOC_LEGS,
	ILOC_BOOTS,
	ILOC_INVALID = -1,
};

/** @brief Whether @p loc is one of the six worn slots Oracool added (see ILOC_SHOULDERS above). */
constexpr bool IsOracoolEquipLocation(item_equip_type loc)
{
	return loc >= ILOC_SHOULDERS && loc <= ILOC_BOOTS;
}

/// Item graphic IDs; frame_num-11 of objcurs.cel.
///
/// Oracool: widened from uint8_t. Sheets 1 and 2 already use ids 0-228 of the 0-255 a byte
/// offers, and the six new worn types need roughly a hundred icons between them. Runtime only -
/// saves store the AllItemsList index and rebuild the item from its seed, so nothing on disk
/// carries a cursor id except the ear-name packing, which is unaffected.
enum item_cursor_graphic : uint16_t {
	// clang-format off
	ICURS_POTION_OF_FULL_MANA         = 0,
	ICURS_SCROLL_OF                   = 1,
	ICURS_GOLD_SMALL                  = 4,
	ICURS_GOLD_MEDIUM                 = 5,
	ICURS_GOLD_LARGE                  = 6,
	ICURS_RING_OF_TRUTH               = 10,
	ICURS_RING                        = 12,
	ICURS_SPECTRAL_ELIXIR             = 15,
	ICURS_ARENA_POTION                = 16,
	ICURS_GOLDEN_ELIXIR               = 17,
	ICURS_EMPYREAN_BAND               = 18,
	ICURS_EAR_SORCERER                = 19,
	ICURS_EAR_WARRIOR                 = 20,
	ICURS_EAR_ROGUE                   = 21,
	ICURS_BLOOD_STONE                 = 25,
	// Oracool Phase 1: three unused vanilla icons (sheet frames 37-39), claimed for the gems -
	// found by contact-sheeting the whole cursor sheet. A glossy red orb, a cut blue gem, and an
	// amber crystal, all original Diablo art.
	ICURS_ORACOOL_RED_ORB             = 26,
	ICURS_ORACOOL_BLUE_GEM            = 27,
	ICURS_ORACOOL_AMBER_CRYSTAL       = 28,
	ICURS_OIL                         = 30,
	ICURS_ELIXIR_OF_VITALITY          = 31,
	ICURS_POTION_OF_HEALING           = 32,
	ICURS_POTION_OF_FULL_REJUVENATION = 33,
	ICURS_ELIXIR_OF_MAGIC             = 34,
	ICURS_POTION_OF_FULL_HEALING      = 35,
	ICURS_ELIXIR_OF_DEXTERITY         = 36,
	ICURS_POTION_OF_REJUVENATION      = 37,
	ICURS_ELIXIR_OF_STRENGTH          = 38,
	ICURS_POTION_OF_MANA              = 39,
	ICURS_BRAIN                       = 40,
	ICURS_OPTIC_AMULET                = 44,
	ICURS_AMULET                      = 45,
	ICURS_DAGGER                      = 51,
	ICURS_BLADE                       = 56,
	ICURS_BASTARD_SWORD               = 57,
	ICURS_MACE                        = 59,
	ICURS_LONG_SWORD                  = 60,
	ICURS_BROAD_SWORD                 = 61,
	ICURS_FALCHION                    = 62,
	ICURS_MORNING_STAR                = 63,
	ICURS_SHORT_SWORD                 = 64,
	ICURS_CLAYMORE                    = 65,
	ICURS_CLUB                        = 66,
	ICURS_SABRE                       = 67,
	ICURS_SPIKED_CLUB                 = 70,
	ICURS_SCIMITAR                    = 72,
	ICURS_FULL_HELM                   = 75,
	ICURS_MAGIC_ROCK                  = 76,
	ICURS_THE_UNDEAD_CROWN            = 78,
	ICURS_HELM                        = 82,
	ICURS_BUCKLER                     = 83,
	ICURS_VIEL_OF_STEEL               = 85,
	ICURS_BOOK_GREY                   = 86,
	ICURS_BOOK_RED                    = 87,
	ICURS_BOOK_BLUE                   = 88,
	ICURS_BLACK_MUSHROOM              = 89,
	ICURS_SKULL_CAP                   = 90,
	ICURS_CAP                         = 91,
	ICURS_HARLEQUIN_CREST             = 93,
	ICURS_CROWN                       = 95,
	ICURS_MAP_OF_THE_STARS            = 96,
	ICURS_FUNGAL_TOME                 = 97,
	ICURS_GREAT_HELM                  = 98,
	ICURS_BATTLE_AXE                  = 101,
	ICURS_HUNTERS_BOW                 = 102,
	ICURS_FIELD_PLATE                 = 103,
	ICURS_SMALL_SHIELD                = 105,
	ICURS_CLEAVER                     = 106,
	ICURS_STUDDED_LEATHER_ARMOR       = 107,
	ICURS_SHORT_STAFF                 = 109,
	ICURS_TWO_HANDED_SWORD            = 110,
	ICURS_CHAIN_MAIL                  = 111,
	ICURS_SMALL_AXE                   = 112,
	ICURS_KITE_SHIELD                 = 113,
	ICURS_SCALE_MAIL                  = 114,
	ICURS_SHORT_BOW                   = 118,
	ICURS_LONG_BATTLE_BOW             = 119,
	ICURS_LONG_WAR_BOW                = 120,
	ICURS_WAR_HAMMER                  = 121,
	ICURS_MAUL                        = 122,
	ICURS_LONG_STAFF                  = 123,
	ICURS_WAR_STAFF                   = 124,
	ICURS_TAVERN_SIGN                 = 126,
	ICURS_HARD_LEATHER_ARMOR          = 127,
	ICURS_RAGS                        = 128,
	ICURS_QUILTED_ARMOR               = 129,
	ICURS_FLAIL                       = 131,
	ICURS_TOWER_SHIELD                = 132,
	ICURS_COMPOSITE_BOW               = 133,
	ICURS_GREAT_SWORD                 = 134,
	ICURS_LEATHER_ARMOR               = 135,
	ICURS_SPLINT_MAIL                 = 136,
	ICURS_ROBE                        = 137,
	ICURS_ANVIL_OF_FURY               = 140,
	ICURS_BROAD_AXE                   = 141,
	ICURS_LARGE_AXE                   = 142,
	ICURS_GREAT_AXE                   = 143,
	ICURS_AXE                         = 144,
	ICURS_LARGE_SHIELD                = 147,
	ICURS_GOTHIC_SHIELD               = 148,
	ICURS_CLOAK                       = 149,
	ICURS_CAPE                        = 150,
	ICURS_FULL_PLATE_MAIL             = 151,
	ICURS_GOTHIC_PLATE                = 152,
	ICURS_BREAST_PLATE                = 153,
	ICURS_RING_MAIL                   = 154,
	ICURS_STAFF_OF_LAZARUS            = 155,
	ICURS_ARKAINES_VALOR              = 157,
	ICURS_SHORT_WAR_BOW               = 165,
	ICURS_COMPOSITE_STAFF             = 166,
	ICURS_SHORT_BATTLE_BOW            = 167,
	ICURS_GOLD                        = 168,
	ICURS_AURIC_AMULET                = 180,
	ICURS_RUNE_BOMB                   = 187,
	ICURS_THEODORE                    = 188,
	ICURS_TORN_NOTE_1                 = 189,
	ICURS_TORN_NOTE_2                 = 190,
	ICURS_TORN_NOTE_3                 = 191,
	ICURS_RECONSTRUCTED_NOTE          = 192,
	ICURS_RUNE_OF_FIRE                = 193,
	ICURS_GREATER_RUNE_OF_FIRE        = 194,
	ICURS_RUNE_OF_LIGHTNING           = 195,
	ICURS_GREATER_RUNE_OF_LIGHTNING   = 196,
	ICURS_RUNE_OF_STONE               = 197,
	ICURS_GREY_SUIT                   = 198,
	ICURS_BROWN_SUIT                  = 199,
	ICURS_BOVINE                      = 226,

	// Oracool: our own icon sheet (data\inv\oracool_items.cel, shipped in oracool.mpq). Ids
	// continue past the 229 vanilla item graphics - sheet 1 holds 0-167 and Hellfire's sheet 2
	// holds 168-228. cursor.cpp static_asserts that this first value really is where sheet 3
	// begins, since the arithmetic depends on three table sizes and CURSOR_FIRSTITEM.
	ICURS_ORACOOL_FIRST               = 229,
	ICURS_ORACOOL_SHOULDERS           = 229,
	ICURS_ORACOOL_BRACERS             = 230,
	ICURS_ORACOOL_GLOVES              = 231,
	ICURS_ORACOOL_BELT                = 232,
	ICURS_ORACOOL_LEGS                = 233,
	ICURS_ORACOOL_BOOTS               = 234,
	ICURS_ORACOOL_HELM                = 235,
	ICURS_ORACOOL_LEATHER_ARMOR       = 236,
	ICURS_ORACOOL_LEATHER_SHIELD      = 237,
	ICURS_ORACOOL_IRON_GLOVES           = 238,
	ICURS_ORACOOL_IRON_SHOULDERS        = 239,
	ICURS_ORACOOL_IRON_BRACERS          = 240,
	ICURS_ORACOOL_IRON_BELT             = 241,
	ICURS_ORACOOL_IRON_LEGS             = 242,
	ICURS_ORACOOL_IRON_BOOTS            = 243,
	ICURS_ORACOOL_IRON_ARMOR            = 244,
	ICURS_ORACOOL_IRON_SHIELD           = 245,
	ICURS_ORACOOL_STEEL_GLOVES          = 246,
	ICURS_ORACOOL_STEEL_SHOULDERS       = 247,
	ICURS_ORACOOL_STEEL_BRACERS         = 248,
	ICURS_ORACOOL_STEEL_BELT            = 249,
	ICURS_ORACOOL_STEEL_LEGS            = 250,
	ICURS_ORACOOL_STEEL_BOOTS           = 251,
	ICURS_ORACOOL_STEEL_ARMOR           = 252,
	ICURS_ORACOOL_STEEL_SHIELD          = 253,
	ICURS_ORACOOL_STEEL_HELM            = 254,
	ICURS_ORACOOL_CRUSADER_GLOVES       = 255,
	ICURS_ORACOOL_CRUSADER_SHOULDERS    = 256,
	ICURS_ORACOOL_CRUSADER_BRACERS      = 257,
	ICURS_ORACOOL_CRUSADER_BELT         = 258,
	ICURS_ORACOOL_CRUSADER_LEGS         = 259,
	ICURS_ORACOOL_CRUSADER_BOOTS        = 260,
	ICURS_ORACOOL_CRUSADER_ARMOR        = 261,
	ICURS_ORACOOL_CRUSADER_SHIELD       = 262,
	ICURS_ORACOOL_CRUSADER_HELM         = 263,
	ICURS_ORACOOL_BONE_GLOVES           = 264,
	ICURS_ORACOOL_BONE_SHOULDERS        = 265,
	ICURS_ORACOOL_BONE_BRACERS          = 266,
	ICURS_ORACOOL_BONE_BELT             = 267,
	ICURS_ORACOOL_BONE_LEGS             = 268,
	ICURS_ORACOOL_BONE_BOOTS            = 269,
	ICURS_ORACOOL_BONE_ARMOR            = 270,
	ICURS_ORACOOL_BONE_SHIELD           = 271,
	ICURS_ORACOOL_BONE_HELM             = 272,
	ICURS_ORACOOL_ROYAL_GLOVES          = 273,
	ICURS_ORACOOL_ROYAL_SHOULDERS       = 274,
	ICURS_ORACOOL_ROYAL_BRACERS         = 275,
	ICURS_ORACOOL_ROYAL_BELT            = 276,
	ICURS_ORACOOL_ROYAL_LEGS            = 277,
	ICURS_ORACOOL_ROYAL_BOOTS           = 278,
	ICURS_ORACOOL_ROYAL_ARMOR           = 279,
	ICURS_ORACOOL_ROYAL_SHIELD          = 280,
	ICURS_ORACOOL_ROYAL_HELM            = 281,
	ICURS_ORACOOL_OBSIDIAN_GLOVES       = 282,
	ICURS_ORACOOL_OBSIDIAN_SHOULDERS    = 283,
	ICURS_ORACOOL_OBSIDIAN_BRACERS      = 284,
	ICURS_ORACOOL_OBSIDIAN_BELT         = 285,
	ICURS_ORACOOL_OBSIDIAN_LEGS         = 286,
	ICURS_ORACOOL_OBSIDIAN_BOOTS        = 287,
	ICURS_ORACOOL_OBSIDIAN_ARMOR        = 288,
	ICURS_ORACOOL_OBSIDIAN_SHIELD       = 289,
	ICURS_ORACOOL_OBSIDIAN_HELM         = 290,
	ICURS_ORACOOL_INFERNAL_GLOVES       = 291,
	ICURS_ORACOOL_INFERNAL_SHOULDERS    = 292,
	ICURS_ORACOOL_INFERNAL_BRACERS      = 293,
	ICURS_ORACOOL_INFERNAL_BELT         = 294,
	ICURS_ORACOOL_INFERNAL_LEGS         = 295,
	ICURS_ORACOOL_INFERNAL_BOOTS        = 296,
	ICURS_ORACOOL_INFERNAL_ARMOR        = 297,
	ICURS_ORACOOL_INFERNAL_SHIELD       = 298,
	ICURS_ORACOOL_INFERNAL_HELM         = 299,
	ICURS_ORACOOL_DIAMOND_GLOVES        = 300,
	ICURS_ORACOOL_DIAMOND_SHOULDERS     = 301,
	ICURS_ORACOOL_DIAMOND_BRACERS       = 302,
	ICURS_ORACOOL_DIAMOND_BELT          = 303,
	ICURS_ORACOOL_DIAMOND_LEGS          = 304,
	ICURS_ORACOOL_DIAMOND_BOOTS         = 305,
	ICURS_ORACOOL_DIAMOND_ARMOR         = 306,
	ICURS_ORACOOL_DIAMOND_SHIELD        = 307,
	ICURS_ORACOOL_DIAMOND_HELM          = 308,
	ICURS_ORACOOL_RUBY_GLOVES                 = 309,
	ICURS_ORACOOL_RUBY_SHOULDERS              = 310,
	ICURS_ORACOOL_RUBY_BRACERS                = 311,
	ICURS_ORACOOL_RUBY_BELT                   = 312,
	ICURS_ORACOOL_RUBY_LEGS                   = 313,
	ICURS_ORACOOL_RUBY_BOOTS                  = 314,
	ICURS_ORACOOL_RUBY_ARMOR                  = 315,
	ICURS_ORACOOL_RUBY_SHIELD                 = 316,
	ICURS_ORACOOL_RUBY_HELM                   = 317,
	ICURS_ORACOOL_ONYX_GLOVES                 = 318,
	ICURS_ORACOOL_ONYX_SHOULDERS              = 319,
	ICURS_ORACOOL_ONYX_BRACERS                = 320,
	ICURS_ORACOOL_ONYX_BELT                   = 321,
	ICURS_ORACOOL_ONYX_LEGS                   = 322,
	ICURS_ORACOOL_ONYX_BOOTS                  = 323,
	ICURS_ORACOOL_ONYX_ARMOR                  = 324,
	ICURS_ORACOOL_ONYX_SHIELD                 = 325,
	ICURS_ORACOOL_ONYX_HELM                   = 326,
	ICURS_ORACOOL_GLACIAL_GLOVES              = 327,
	ICURS_ORACOOL_GLACIAL_SHOULDERS           = 328,
	ICURS_ORACOOL_GLACIAL_BRACERS             = 329,
	ICURS_ORACOOL_GLACIAL_BELT                = 330,
	ICURS_ORACOOL_GLACIAL_LEGS                = 331,
	ICURS_ORACOOL_GLACIAL_BOOTS               = 332,
	ICURS_ORACOOL_GLACIAL_ARMOR               = 333,
	ICURS_ORACOOL_GLACIAL_SHIELD              = 334,
	ICURS_ORACOOL_GLACIAL_HELM                = 335,
	ICURS_ORACOOL_CYBORG_GLOVES               = 336,
	ICURS_ORACOOL_CYBORG_SHOULDERS            = 337,
	ICURS_ORACOOL_CYBORG_BRACERS              = 338,
	ICURS_ORACOOL_CYBORG_BELT                 = 339,
	ICURS_ORACOOL_CYBORG_LEGS                 = 340,
	ICURS_ORACOOL_CYBORG_BOOTS                = 341,
	ICURS_ORACOOL_CYBORG_ARMOR                = 342,
	ICURS_ORACOOL_CYBORG_SHIELD               = 343,
	ICURS_ORACOOL_CYBORG_HELM                 = 344,
	ICURS_ORACOOL_FALLEN_GLOVES               = 345,
	ICURS_ORACOOL_FALLEN_SHOULDERS            = 346,
	ICURS_ORACOOL_FALLEN_BRACERS              = 347,
	ICURS_ORACOOL_FALLEN_BELT                 = 348,
	ICURS_ORACOOL_FALLEN_LEGS                 = 349,
	ICURS_ORACOOL_FALLEN_BOOTS                = 350,
	ICURS_ORACOOL_FALLEN_ARMOR                = 351,
	ICURS_ORACOOL_FALLEN_SHIELD               = 352,
	ICURS_ORACOOL_FALLEN_HELM                 = 353,
	ICURS_ORACOOL_SERAPHIC_GLOVES             = 354,
	ICURS_ORACOOL_SERAPHIC_SHOULDERS          = 355,
	ICURS_ORACOOL_SERAPHIC_BRACERS            = 356,
	ICURS_ORACOOL_SERAPHIC_BELT               = 357,
	ICURS_ORACOOL_SERAPHIC_LEGS               = 358,
	ICURS_ORACOOL_SERAPHIC_BOOTS              = 359,
	ICURS_ORACOOL_SERAPHIC_ARMOR              = 360,
	ICURS_ORACOOL_SERAPHIC_SHIELD             = 361,
	ICURS_ORACOOL_SERAPHIC_HELM               = 362,
	ICURS_ORACOOL_SPECTRAL_GLOVES             = 363,
	ICURS_ORACOOL_SPECTRAL_SHOULDERS          = 364,
	ICURS_ORACOOL_SPECTRAL_BRACERS            = 365,
	ICURS_ORACOOL_SPECTRAL_BELT               = 366,
	ICURS_ORACOOL_SPECTRAL_LEGS               = 367,
	ICURS_ORACOOL_SPECTRAL_BOOTS              = 368,
	ICURS_ORACOOL_SPECTRAL_ARMOR              = 369,
	ICURS_ORACOOL_SPECTRAL_SHIELD             = 370,
	ICURS_ORACOOL_SPECTRAL_HELM               = 371,
	// The gem icons, cut from the user's own gem sheet (Oracool.MPQ\item-gems-v1.png).
	ICURS_ORACOOL_GEM_RUBY                    = 372,
	ICURS_ORACOOL_GEM_SAPPHIRE                = 373,
	ICURS_ORACOOL_GEM_TOPAZ                   = 374,
	ICURS_ORACOOL_GEM_EMERALD                 = 375,
	ICURS_ORACOOL_GEM_SKULL                   = 376,
	// The rune icons, cut from the user's 33-rune D2 sheet (Oracool.MPQ\item-runes-v1.png).
	ICURS_ORACOOL_RUNE_EL                     = 377,
	ICURS_ORACOOL_RUNE_TIR                    = 378,
	ICURS_ORACOOL_RUNE_RAL                    = 379,
	ICURS_ORACOOL_RUNE_ORT                    = 380,
	ICURS_ORACOOL_RUNE_SOL                    = 381,
	// The gem quality ladder (Gems.png). The five above (372-376) keep their numbers and are
	// re-cut from this same sheet's normal-quality row, so an item already in a save still points
	// at the right picture - _iCurs is stored per item, which is why these append rather than
	// renumbering the block.
	ICURS_ORACOOL_GEM_AMETHYST_CHIPPED        = 382,
	ICURS_ORACOOL_GEM_AMETHYST_FLAWED         = 383,
	ICURS_ORACOOL_GEM_AMETHYST_NORMAL         = 384,
	ICURS_ORACOOL_GEM_AMETHYST_FLAWLESS       = 385,
	ICURS_ORACOOL_GEM_AMETHYST_PERFECT        = 386,
	ICURS_ORACOOL_GEM_DIAMOND_CHIPPED         = 387,
	ICURS_ORACOOL_GEM_DIAMOND_FLAWED          = 388,
	ICURS_ORACOOL_GEM_DIAMOND_NORMAL          = 389,
	ICURS_ORACOOL_GEM_DIAMOND_FLAWLESS        = 390,
	ICURS_ORACOOL_GEM_DIAMOND_PERFECT         = 391,
	ICURS_ORACOOL_GEM_EMERALD_CHIPPED         = 392,
	ICURS_ORACOOL_GEM_EMERALD_FLAWED          = 393,
	ICURS_ORACOOL_GEM_EMERALD_FLAWLESS        = 394,
	ICURS_ORACOOL_GEM_EMERALD_PERFECT         = 395,
	ICURS_ORACOOL_GEM_RUBY_CHIPPED            = 396,
	ICURS_ORACOOL_GEM_RUBY_FLAWED             = 397,
	ICURS_ORACOOL_GEM_RUBY_FLAWLESS           = 398,
	ICURS_ORACOOL_GEM_RUBY_PERFECT            = 399,
	ICURS_ORACOOL_GEM_SAPPHIRE_CHIPPED        = 400,
	ICURS_ORACOOL_GEM_SAPPHIRE_FLAWED         = 401,
	ICURS_ORACOOL_GEM_SAPPHIRE_FLAWLESS       = 402,
	ICURS_ORACOOL_GEM_SAPPHIRE_PERFECT        = 403,
	ICURS_ORACOOL_GEM_TOPAZ_CHIPPED           = 404,
	ICURS_ORACOOL_GEM_TOPAZ_FLAWED            = 405,
	ICURS_ORACOOL_GEM_TOPAZ_FLAWLESS          = 406,
	ICURS_ORACOOL_GEM_TOPAZ_PERFECT           = 407,
	ICURS_ORACOOL_GEM_SKULL_CHIPPED           = 408,
	ICURS_ORACOOL_GEM_SKULL_FLAWED            = 409,
	ICURS_ORACOOL_GEM_SKULL_FLAWLESS          = 410,
	ICURS_ORACOOL_GEM_SKULL_PERFECT           = 411,
	// The fifteen item sets' 94 icons, 412..505. GENERATED by tools/GenItemSets.ps1 together with
	// the CEL frame order and the width/height tables in cursor.cpp, because a CEL stores no names
	// and no sizes - a frame's position in the file is the only thing that ties it to an id here.
#include "oracool/item_sets_curs.inc"
	// The 143 expansion uniques' icons, 506 onward. GENERATED by tools/GenUniqueItems.ps1 in the
	// same one-walk-one-order pass as their table rows; each unique reaches its frame through
	// IPL_INVCURS, and its inventory footprint follows the frame through InvItemWidth3/Height3.
#include "oracool/unique_items_curs.inc"
	// Sockets v2: the 28 new rune frames, appended after the uniques so the CEL's frame order and
	// these ids stay in step. GENERATED by tools/GenRunes.ps1.
#include "oracool/runes_curs.inc"
	// Salvage material frames, after the runes - same one-generator rule.
#include "oracool/salvage_curs.inc"
	// The seven Charm of Salvaging frames, after the materials - same one-generator rule. Grouped
	// by family, never interleaved: the CEL stores frames in file order and nothing else ties a
	// frame to an id, so a charm spec sitting between two material specs would silently shift
	// every id after it.
#include "oracool/salvage_charm_curs.inc"
	ICURS_ORACOOL_LAST                = ICURS_ORACOOL_CHARM_SALVAGE_ETHEREAL_IMBUEITIES,
	// clang-format on
};

enum class ItemType : int8_t {
	Misc,
	Sword,
	Axe,
	Bow,
	Mace,
	Shield,
	LightArmor,
	Helm,
	MediumArmor,
	HeavyArmor,
	Staff,
	Gold,
	Ring,
	Amulet,
	// Oracool: user request - the six new worn slots. Appended rather than inserted: ItemType is
	// written into the tiered-item save extension, so renumbering the existing values would
	// silently reinterpret every stored item.
	Shoulders,
	Bracers,
	Gloves,
	Belt,
	Legs,
	Boots,
	None = -1,
};

/** @brief Whether @p type is one of the six item types Oracool added (see the enum above). */
constexpr bool IsOracoolItemType(ItemType type)
{
	return type >= ItemType::Shoulders && type <= ItemType::Boots;
}

string_view ItemTypeToString(ItemType itemType);

enum unique_base_item : int8_t {
	UITYPE_NONE,
	UITYPE_SHORTBOW,
	UITYPE_LONGBOW,
	UITYPE_HUNTBOW,
	UITYPE_COMPBOW,
	UITYPE_WARBOW,
	UITYPE_BATTLEBOW,
	UITYPE_DAGGER,
	UITYPE_FALCHION,
	UITYPE_CLAYMORE,
	UITYPE_BROADSWR,
	UITYPE_SABRE,
	UITYPE_SCIMITAR,
	UITYPE_LONGSWR,
	UITYPE_BASTARDSWR,
	UITYPE_TWOHANDSWR,
	UITYPE_GREATSWR,
	UITYPE_CLEAVER,
	UITYPE_LARGEAXE,
	UITYPE_BROADAXE,
	UITYPE_SMALLAXE,
	UITYPE_BATTLEAXE,
	UITYPE_GREATAXE,
	UITYPE_MACE,
	UITYPE_MORNSTAR,
	UITYPE_SPIKCLUB,
	UITYPE_MAUL,
	UITYPE_WARHAMMER,
	UITYPE_FLAIL,
	UITYPE_LONGSTAFF,
	UITYPE_SHORTSTAFF,
	UITYPE_COMPSTAFF,
	UITYPE_QUARSTAFF,
	UITYPE_WARSTAFF,
	UITYPE_SKULLCAP,
	UITYPE_HELM,
	UITYPE_GREATHELM,
	UITYPE_CROWN,
	UITYPE_38,
	UITYPE_RAGS,
	UITYPE_STUDARMOR,
	UITYPE_CLOAK,
	UITYPE_ROBE,
	UITYPE_CHAINMAIL,
	UITYPE_LEATHARMOR,
	UITYPE_BREASTPLATE,
	UITYPE_CAPE,
	UITYPE_PLATEMAIL,
	UITYPE_FULLPLATE,
	UITYPE_BUCKLER,
	UITYPE_SMALLSHIELD,
	UITYPE_LARGESHIELD,
	UITYPE_KITESHIELD,
	UITYPE_GOTHSHIELD,
	UITYPE_RING,
	UITYPE_55,
	UITYPE_AMULET,
	UITYPE_SKCROWN,
	UITYPE_INFRARING,
	UITYPE_OPTAMULET,
	UITYPE_TRING,
	UITYPE_HARCREST,
	UITYPE_MAPOFDOOM,
	UITYPE_ELIXIR,
	UITYPE_ARMOFVAL,
	UITYPE_STEELVEIL,
	UITYPE_GRISWOLD,
	UITYPE_LGTFORGE,
	UITYPE_LAZSTAFF,
	UITYPE_BOVINE,
	UITYPE_INVALID = -1,
};

enum class ItemSpecialEffect : uint32_t {
	// clang-format off
	None                   = 0,
	RandomStealLife        = 1 << 1,
	RandomArrowVelocity    = 1 << 2,
	FireArrows             = 1 << 3,
	FireDamage             = 1 << 4,
	LightningDamage        = 1 << 5,
	DrainLife              = 1 << 6,
	MultipleArrows         = 1 << 9,
	Knockback              = 1 << 11,
	StealMana3             = 1 << 13,
	StealMana5             = 1 << 14,
	StealLife3             = 1 << 15,
	StealLife5             = 1 << 16,
	QuickAttack            = 1 << 17,
	FastAttack             = 1 << 18,
	FasterAttack           = 1 << 19,
	FastestAttack          = 1 << 20,
	FastHitRecovery        = 1 << 21,
	FasterHitRecovery      = 1 << 22,
	FastestHitRecovery     = 1 << 23,
	FastBlock              = 1 << 24,
	LightningArrows        = 1 << 25,
	Thorns                 = 1 << 26,
	NoMana                 = 1 << 27,
	HalfTrapDamage         = 1 << 28,
	TripleDemonDamage      = 1 << 30,
	ZeroResistance         = 1U << 31,
	// clang-format on
};
use_enum_as_flags(ItemSpecialEffect);

enum class ItemSpecialEffectHf : uint8_t {
	// clang-format off
	None               = 0,
	Devastation        = 1 << 0,
	Decay              = 1 << 1,
	Peril              = 1 << 2,
	Jesters            = 1 << 3,
	Doppelganger       = 1 << 4,
	ACAgainstDemons    = 1 << 5,
	ACAgainstUndead    = 1 << 6,
	// clang-format on
};
use_enum_as_flags(ItemSpecialEffectHf);

enum item_misc_id : int8_t {
	IMISC_NONE,
	IMISC_USEFIRST,
	IMISC_FULLHEAL,
	IMISC_HEAL,
	IMISC_0x4, // Unused
	IMISC_0x5, // Unused
	IMISC_MANA,
	IMISC_FULLMANA,
	IMISC_0x8, // Unused
	IMISC_0x9, // Unused
	IMISC_ELIXSTR,
	IMISC_ELIXMAG,
	IMISC_ELIXDEX,
	IMISC_ELIXVIT,
	IMISC_0xE,  // Unused
	IMISC_0xF,  // Unused
	IMISC_0x10, // Unused
	IMISC_0x11, // Unused
	IMISC_REJUV,
	IMISC_FULLREJUV,
	IMISC_USELAST,
	IMISC_SCROLL,
	IMISC_SCROLLT,
	IMISC_STAFF,
	IMISC_BOOK,
	IMISC_RING,
	IMISC_AMULET,
	IMISC_UNIQUE,
	IMISC_0x1C, // Unused
	IMISC_OILFIRST,
	IMISC_OILOF, /* oils are beta or hellfire only */
	IMISC_OILACC,
	IMISC_OILMAST,
	IMISC_OILSHARP,
	IMISC_OILDEATH,
	IMISC_OILSKILL,
	IMISC_OILBSMTH,
	IMISC_OILFORT,
	IMISC_OILPERM,
	IMISC_OILHARD,
	IMISC_OILIMP,
	IMISC_OILLAST,
	IMISC_MAPOFDOOM,
	IMISC_EAR,
	IMISC_SPECELIX,
	IMISC_0x2D, // Unused
	IMISC_RUNEFIRST,
	IMISC_RUNEF,
	IMISC_RUNEL,
	IMISC_GR_RUNEL,
	IMISC_GR_RUNEF,
	IMISC_RUNES,
	IMISC_RUNELAST,
	IMISC_AURIC,
	IMISC_NOTE,
	IMISC_ARENAPOT,
	IMISC_INVALID = -1,
};

struct ItemData {
	enum item_drop_rate iRnd;
	enum item_class iClass;
	enum item_equip_type iLoc;
	enum item_cursor_graphic iCurs;
	enum ItemType itype;
	enum unique_base_item iItemId;
	const char *iName;
	const char *iSName;
	uint8_t iMinMLvl;
	uint8_t iDurability;
	uint8_t iMinDam;
	uint8_t iMaxDam;
	uint8_t iMinAC;
	uint8_t iMaxAC;
	uint8_t iMinStr;
	uint8_t iMinMag;
	uint8_t iMinDex;
	ItemSpecialEffect iFlags; // ItemSpecialEffect as bit flags
	enum item_misc_id iMiscId;
	SpellID iSpell;
	bool iUsable;
	uint16_t iValue;
};

enum item_effect_type : int8_t {
	IPL_TOHIT,
	IPL_TOHIT_CURSE,
	IPL_DAMP,
	IPL_DAMP_CURSE,
	IPL_TOHIT_DAMP,
	IPL_TOHIT_DAMP_CURSE,
	IPL_ACP,
	IPL_ACP_CURSE,
	IPL_FIRERES,
	IPL_LIGHTRES,
	IPL_MAGICRES,
	IPL_ALLRES,
	IPL_SPLLVLADD = 14,
	IPL_CHARGES,
	IPL_FIREDAM,
	IPL_LIGHTDAM,
	IPL_STR = 19,
	IPL_STR_CURSE,
	IPL_MAG,
	IPL_MAG_CURSE,
	IPL_DEX,
	IPL_DEX_CURSE,
	IPL_VIT,
	IPL_VIT_CURSE,
	IPL_ATTRIBS,
	IPL_ATTRIBS_CURSE,
	IPL_GETHIT_CURSE,
	IPL_GETHIT,
	IPL_LIFE,
	IPL_LIFE_CURSE,
	IPL_MANA,
	IPL_MANA_CURSE,
	IPL_DUR,
	IPL_DUR_CURSE,
	IPL_INDESTRUCTIBLE,
	IPL_LIGHT,
	IPL_LIGHT_CURSE,
	IPL_MULT_ARROWS = 41, /* only used in hellfire */
	IPL_FIRE_ARROWS,
	IPL_LIGHT_ARROWS,
	IPL_INVCURS,
	IPL_THORNS,
	IPL_NOMANA,
	IPL_FIREBALL = 50, /* only used in hellfire */
	IPL_ABSHALFTRAP = 52,
	IPL_KNOCKBACK,
	IPL_STEALMANA = 55,
	IPL_STEALLIFE,
	IPL_TARGAC,
	IPL_FASTATTACK,
	IPL_FASTRECOVER,
	IPL_FASTBLOCK,
	IPL_DAMMOD,
	IPL_RNDARROWVEL,
	IPL_SETDAM,
	IPL_SETDUR,
	IPL_NOMINSTR,
	IPL_SPELL,
	IPL_ONEHAND = 68,
	IPL_3XDAMVDEM,
	IPL_ALLRESZERO,
	IPL_DRAINLIFE = 72,
	IPL_RNDSTEALLIFE,
	IPL_SETAC = 75,
	IPL_ADDACLIFE,
	IPL_ADDMANAAC,
	IPL_AC_CURSE = 79,
	IPL_LASTDIABLO = IPL_AC_CURSE,
	IPL_FIRERES_CURSE,
	IPL_LIGHTRES_CURSE,
	IPL_MAGICRES_CURSE,
	IPL_DEVASTATION = 84,
	IPL_DECAY,
	IPL_PERIL,
	IPL_JESTERS,
	IPL_CRYSTALLINE,
	IPL_DOPPELGANGER,
	IPL_ACDEMON,
	IPL_ACUNDEAD,
	IPL_MANATOLIFE,
	IPL_LIFETOMANA,
	/**
	 * @brief Oracool: percentage bonus to gold dropped by monsters.
	 *
	 * Appended AFTER IPL_LIFETOMANA rather than before IPL_INVALID, which is explicitly -1 and so
	 * is not the enum's last value. That keeps every existing power's number exactly where it was -
	 * they are persisted inside items - and it is why this could be added without a renumbering.
	 *
	 * Note the two bounds that had to move with it: loadsave.cpp's IsOracoolAffixTypeValid, which
	 * capped at IPL_LIFETOMANA and would have loaded this one as invalid, and the item format
	 * version for the new field it writes.
	 */
	IPL_GOLDFIND,
	IPL_INVALID = -1,
};

enum goodorevil : uint8_t {
	GOE_ANY,
	GOE_EVIL,
	GOE_GOOD,
};

enum class AffixItemType : uint8_t {
	// clang-format off
	None      = 0,
	Misc      = 1 << 0,
	Bow       = 1 << 1,
	Staff     = 1 << 2,
	Weapon    = 1 << 3,
	Shield    = 1 << 4,
	Armor     = 1 << 5,
	// clang-format on
};
use_enum_as_flags(AffixItemType);

struct ItemPower {
	item_effect_type type = IPL_INVALID;
	int param1 = 0;
	int param2 = 0;
};

struct PLStruct {
	const char *PLName;
	ItemPower power;
	int8_t PLMinLvl;
	AffixItemType PLIType; // AffixItemType as bit flags
	enum goodorevil PLGOE;
	bool PLDouble;
	bool PLOk;
	int minVal;
	int maxVal;
	int multVal;
};

struct UniqueItem {
	const char *UIName;
	enum unique_base_item UIItemId;
	int8_t UIMinLvl;
	uint8_t UINumPL;
	int UIValue;
	/**
	 * @brief SEVEN slots, not vanilla's six (2026-08-17). Twenty-six of the expansion uniques carry
	 * six live affixes, and the sprite delivery put each one's icon on IPL_INVCURS - which needs a
	 * slot of its own. Vanilla's rows are aggregate-initialised with six entries, so the seventh is
	 * zero (IPL_INVALID) for all of them and nothing about their behaviour moves.
	 */
	ItemPower powers[7];
};

/**
 * @brief Ceiling on the unique table, and on everything indexed by a unique's id.
 *
 * Vanilla had 87 uniques and wrote 128 into three separate places - a std::bitset, the
 * UniqueItemFlags array, and a `% 128` wrap in CheckUnique - none of which named each other. The
 * 250-unique expansion took the table to 230 and all three broke at once, as a bitset assertion
 * inside UnPackItem rather than as anything mentioning uniques.
 *
 * They all derive from this now, and the static_assert beside the table's definition is what keeps
 * the number honest: adding uniques past this bound is a compile error, not a corrupted read.
 *
 * NOTE the related ceiling in _unique_items' underlying type (items.h). Widening this without
 * widening that would silently truncate every id past 127.
 */
constexpr size_t MaxUniqueItems = 512;

extern DVL_API_FOR_TEST const ItemData AllItemsList[];
extern DVL_API_FOR_TEST const PLStruct ItemPrefixes[];
extern DVL_API_FOR_TEST const PLStruct ItemSuffixes[];
extern const UniqueItem UniqueItems[];
/** @brief Rows in UniqueItems, including the UITYPE_INVALID sentinel that terminates it. */
extern DVL_API_FOR_TEST const size_t UniqueItemCount;

} // namespace devilution
