/**
 * @file spelldat.cpp
 *
 * Implementation of all spell data.
 */
#include "spelldat.h"
#include "utils/language.h"

namespace devilution {

namespace {
const auto Fire = SpellDataFlags::Fire;
const auto Lightning = SpellDataFlags::Lightning;
const auto Magic = SpellDataFlags::Magic;
const auto Cold = SpellDataFlags::Cold;
const auto Targeted = SpellDataFlags::Targeted;
const auto AllowedInTown = SpellDataFlags::AllowedInTown;
} // namespace

/** Data related to each spell ID. */
const SpellData SpellsData[] = {
	// clang-format off
// id                           sNameText,                         sSFX,      bookCost10,  staffCost10,  sManaCost, flags,                  sBookLvl,  sStaffLvl,  minInt, { sMissiles[2]                                         }   sManaAdj,  sMinMana,  sStaffMin,  sStaffMax
/*SpellID::Null*/             { nullptr,                           SFX_NONE,           0,            0,          0, Fire,                          0,          0,       0, { MissileID::Null,                 MissileID::Null,    },         0,         0,         40,         80 },
/*SpellID::Firebolt*/         { P_("spell", "Firebolt"),           IS_CAST2,         100,            5,          6, Fire | Targeted,               1,          1,      15, { MissileID::Firebolt,             MissileID::Null,    },         1,         3,         40,         80 },
/*SpellID::Healing*/          { P_("spell", "Healing"),            IS_CAST8,         100,            5,          5, Magic | AllowedInTown,         1,          1,      17, { MissileID::Healing,              MissileID::Null,    },         3,         1,         20,         40 },
/*SpellID::Lightning*/        { P_("spell", "Lightning"),          IS_CAST4,         300,           15,         10, Lightning | Targeted,          4,          3,      20, { MissileID::LightningControl,     MissileID::Null,    },         1,         6,         20,         60 },
/*SpellID::Flash*/            { P_("spell", "Flash"),              IS_CAST4,         750,           50,         30, Lightning,                     5,          4,      33, { MissileID::FlashBottom,          MissileID::FlashTop },         2,        16,         20,         40 },
/*SpellID::Identify*/         { P_("spell", "Identify"),           IS_CAST6,           0,           10,         13, Magic | AllowedInTown,        -1,         -1,      23, { MissileID::Identify,             MissileID::Null,    },         2,         1,          8,         12 },
/*SpellID::FireWall*/         { P_("spell", "Fire Wall"),          IS_CAST2,         600,           40,         28, Fire | Targeted,               3,          2,      27, { MissileID::FireWallControl,      MissileID::Null,    },         2,        16,          8,         16 },
/*SpellID::TownPortal*/       { P_("spell", "Town Portal"),        IS_CAST6,         300,           20,         35, Magic | Targeted,              3,          3,      20, { MissileID::TownPortal,           MissileID::Null,    },         3,        18,          8,         12 },
/*SpellID::StoneCurse*/       { P_("spell", "Stone Curse"),        IS_CAST2,        1200,           80,         60, Magic | Targeted,              6,          5,      51, { MissileID::StoneCurse,           MissileID::Null,    },         3,        40,          8,         16 },
/*SpellID::Infravision*/      { P_("spell", "Infravision"),        IS_CAST8,           0,           60,         40, Magic,                         6,         -1,      36, { MissileID::Infravision,          MissileID::Null,    },         5,        20,          0,          0 },
/*SpellID::Phasing*/          { P_("spell", "Phasing"),            IS_CAST2,         350,           20,         12, Magic,                         7,          6,      39, { MissileID::Phasing,              MissileID::Null,    },         2,         4,         40,         80 },
/*SpellID::ManaShield*/       { P_("spell", "Mana Shield"),        IS_CAST2,        1600,          120,         33, Magic,                         6,          5,      25, { MissileID::ManaShield,           MissileID::Null,    },         0,        33,          4,         10 },
/*SpellID::Fireball*/         { P_("spell", "Fireball"),           IS_CAST2,         800,           30,         16, Fire | Targeted,               8,          7,      48, { MissileID::Fireball,             MissileID::Null,    },         1,        10,         40,         80 },
/*SpellID::Guardian*/         { P_("spell", "Guardian"),           IS_CAST2,        1400,           95,         50, Fire | Targeted,               9,          8,      61, { MissileID::Guardian,             MissileID::Null,    },         2,        30,         16,         32 },
/*SpellID::ChainLightning*/   { P_("spell", "Chain Lightning"),    IS_CAST2,        1100,           75,         30, Lightning,                     8,          7,      54, { MissileID::ChainLightning,       MissileID::Null,    },         1,        18,         20,         60 },
/*SpellID::FlameWave*/        { P_("spell", "Flame Wave"),         IS_CAST2,        1000,           65,         35, Fire | Targeted,               9,          8,      54, { MissileID::FlameWaveControl,     MissileID::Null,    },         3,        20,         20,         40 },
/*SpellID::DoomSerpents*/     { P_("spell", "Doom Serpents"),      IS_CAST2,           0,            0,          0, Lightning,                     9,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         0,         40,         80 },
/*SpellID::BloodRitual*/      { P_("spell", "Blood Ritual"),       IS_CAST2,           0,            0,          0, Magic,                        11,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         0,         40,         80 },
/*SpellID::Nova*/             { P_("spell", "Nova"),               IS_CAST4,        2100,          130,         60, Magic,                        14,         10,      87, { MissileID::Nova,                 MissileID::Null,    },         3,        35,         16,         32 },
/*SpellID::Invisibility*/     { P_("spell", "Invisibility"),       IS_CAST2,           0,            0,          0, Magic,                         7,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         0,         40,         80 },
/*SpellID::Inferno*/          { P_("spell", "Inferno"),            IS_CAST2,         200,           10,         11, Fire | Targeted,               3,          2,      20, { MissileID::InfernoControl,       MissileID::Null,    },         1,         6,         20,         40 },
/*SpellID::Golem*/            { P_("spell", "Golem"),              IS_CAST2,        1800,          110,        100, Fire | Targeted,              11,          9,      81, { MissileID::Golem,                MissileID::Null,    },         6,        60,         16,         32 },
/*SpellID::Rage*/             { P_("spell", "Rage"),               IS_CAST8,           0,            0,         15, Magic,                        -1,         -1,       0, { MissileID::Rage,                 MissileID::Null,    },         1,         1,          0,          0 },
/*SpellID::Teleport*/         { P_("spell", "Teleport"),           IS_CAST6,        2000,          125,         35, Magic | Targeted,             14,         12,     105, { MissileID::Teleport,             MissileID::Null,    },         3,        15,         16,         32 },
/*SpellID::Apocalypse*/       { P_("spell", "Apocalypse"),         IS_CAST2,        3000,          200,        150, Fire,                         19,         15,     149, { MissileID::Apocalypse,           MissileID::Null,    },         6,        90,          8,         12 },
/*SpellID::Etherealize*/      { P_("spell", "Etherealize"),        IS_CAST2,        2600,          160,        100, Magic,                        15,         -1,      93, { MissileID::Etherealize,          MissileID::Null,    },         0,       100,          2,          6 },
/*SpellID::ItemRepair*/       { P_("spell", "Item Repair"),        IS_CAST6,           0,            0,          0, Magic | AllowedInTown,        -1,         -1,     255, { MissileID::ItemRepair,           MissileID::Null,    },         0,         0,         40,         80 },
/*SpellID::StaffRecharge*/    { P_("spell", "Staff Recharge"),     IS_CAST6,           0,            0,          0, Magic | AllowedInTown,        -1,         -1,     255, { MissileID::StaffRecharge,        MissileID::Null,    },         0,         0,         40,         80 },
/*SpellID::TrapDisarm*/       { P_("spell", "Trap Disarm"),        IS_CAST6,           0,            0,          0, Magic,                        -1,         -1,     255, { MissileID::TrapDisarm,           MissileID::Null,    },         0,         0,         40,         80 },
/*SpellID::Elemental*/        { P_("spell", "Elemental"),          IS_CAST2,        1050,           70,         35, Fire,                          8,          6,      68, { MissileID::Elemental,            MissileID::Null,    },         2,        20,         20,         60 },
/*SpellID::ChargedBolt*/      { P_("spell", "Charged Bolt"),       IS_CAST2,         100,            5,          6, Lightning | Targeted,          1,          1,      25, { MissileID::ChargedBolt,          MissileID::Null,    },         1,         6,         40,         80 },
/*SpellID::HolyBolt*/         { P_("spell", "Holy Bolt"),          IS_CAST2,         100,            5,          7, Magic | Targeted,              1,          1,      20, { MissileID::HolyBolt,             MissileID::Null,    },         1,         3,         40,         80 },
/*SpellID::Resurrect*/        { P_("spell", "Resurrect"),          IS_CAST8,         400,           25,         20, Magic | AllowedInTown,         5,          5,      30, { MissileID::Resurrect,            MissileID::Null,    },         0,        20,          4,         10 },
/*SpellID::Telekinesis*/      { P_("spell", "Telekinesis"),        IS_CAST2,         250,           20,         15, Magic,                         2,          2,      33, { MissileID::Telekinesis,          MissileID::Null,    },         2,         8,         20,         40 },
/*SpellID::HealOther*/        { P_("spell", "Heal Other"),         IS_CAST8,         100,            5,          5, Magic | AllowedInTown,         1,          1,      17, { MissileID::HealOther,            MissileID::Null,    },         3,         1,         20,         40 },
/*SpellID::BloodStar*/        { P_("spell", "Blood Star"),         IS_CAST2,        2750,          180,         25, Magic,                        14,         13,      70, { MissileID::BloodStar,            MissileID::Null,    },         2,        14,         20,         60 },
/*SpellID::BoneSpirit*/       { P_("spell", "Bone Spirit"),        IS_CAST2,        1150,           80,         24, Magic,                         9,          7,      34, { MissileID::BoneSpirit,           MissileID::Null,    },         1,        12,         20,         60 },
/*SpellID::Mana*/             { P_("spell", "Mana"),               IS_CAST8,         100,            5,        255, Magic | AllowedInTown,         2,          5,      17, { MissileID::Mana,                 MissileID::Null,    },         3,         1,         12,         24 },
/*SpellID::Magi*/             { P_("spell", "the Magi"),           IS_CAST8,       10000,           20,        255, Magic | AllowedInTown,        12,         20,      45, { MissileID::Magi,                 MissileID::Null,    },         3,         1,         15,         30 },
/*SpellID::Jester*/           { P_("spell", "the Jester"),         IS_CAST8,       10000,           20,        255, Magic | Targeted,              8,          4,      30, { MissileID::Jester,               MissileID::Null,    },         3,         1,         15,         30 },
/*SpellID::LightningWall*/    { P_("spell", "Lightning Wall"),     IS_CAST4,         600,           40,         28, Lightning | Targeted,          3,          2,      27, { MissileID::LightningWallControl, MissileID::Null,    },         2,        16,          8,         16 },
/*SpellID::Immolation*/       { P_("spell", "Immolation"),         IS_CAST2,        2100,          130,         60, Fire,                         14,         10,      87, { MissileID::Immolation,           MissileID::Null,    },         3,        35,         16,         32 },
/*SpellID::Warp*/             { P_("spell", "Warp"),               IS_CAST6,         300,           20,         35, Magic,                         3,          3,      25, { MissileID::Warp,                 MissileID::Null,    },         3,        18,          8,         12 },
/*SpellID::Reflect*/          { P_("spell", "Reflect"),            IS_CAST6,         300,           20,         35, Magic,                         3,          3,      25, { MissileID::Reflect,              MissileID::Null,    },         3,        15,          8,         12 },
/*SpellID::Berserk*/          { P_("spell", "Berserk"),            IS_CAST6,         300,           20,         35, Magic | Targeted,              3,          3,      35, { MissileID::Berserk,              MissileID::Null,    },         3,        15,          8,         12 },
/*SpellID::RingOfFire*/       { P_("spell", "Ring of Fire"),       IS_CAST2,         600,           40,         28, Fire,                          5,          5,      27, { MissileID::RingOfFire,           MissileID::Null,    },         2,        16,          8,         16 },
/*SpellID::Search*/           { P_("spell", "Search"),             IS_CAST6,         300,           20,         15, Magic,                         1,          3,      25, { MissileID::Search,               MissileID::Null,    },         1,         1,          8,         12 },
/*SpellID::RuneOfFire*/       { P_("spell", "Rune of Fire"),       IS_CAST8,         800,           30,        255, Magic | Targeted,             10,         -1,      48, { MissileID::RuneOfFire,           MissileID::Null,    },         1,        10,         40,         80 },
/*SpellID::RuneOfLight*/      { P_("spell", "Rune of Light"),      IS_CAST8,         800,           30,        255, Magic | Targeted,             10,         -1,      48, { MissileID::RuneOfLight,          MissileID::Null,    },         1,        10,         40,         80 },
/*SpellID::RuneOfNova*/       { P_("spell", "Rune of Nova"),       IS_CAST8,         800,           30,        255, Magic | Targeted,             10,         -1,      48, { MissileID::RuneOfNova,           MissileID::Null,    },         1,        10,         40,         80 },
/*SpellID::RuneOfImmolation*/ { P_("spell", "Rune of Immolation"), IS_CAST8,         800,           30,        255, Magic | Targeted,             10,         -1,      48, { MissileID::RuneOfImmolation,     MissileID::Null,    },         1,        10,         40,         80 },
/*SpellID::RuneOfStone*/      { P_("spell", "Rune of Stone"),      IS_CAST8,         800,           30,        255, Magic | Targeted,             10,         -1,      48, { MissileID::RuneOfStone,          MissileID::Null,    },         1,        10,         40,         80 },
// Oracool: the Paladin's Charge. sBookLvl AND sStaffLvl are both -1 on purpose - it is earned at
// character level 12 (oracool/paladin_skills.h), never found, and items.cpp walks this table looking
// for droppable spells, so a level here would put "Book of Charge" in the loot pool. minInt 0 for the
// same reason: the gate is the level, not Magic. No missile - the dash and the swing are driven by
// oracool/furious_charge.cpp, which CheckPlrSpell intercepts before the normal cast path. sManaCost
// 10 matches the table in paladin_skills.h and is here only so the Abilities window can price it.
/*SpellID::Charge*/           { P_("spell", "Charge"),             IS_CAST2,           0,            0,         10, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,        10,          0,          0 },
// The Paladin's other six, every field reasoned exactly as Charge's above: -1/-1 so no book or staff
// can carry them, minInt 0 because the gate is character level, no missile because their mechanics
// live outside the cast path (the melee three in oracool/paladin_melee.cpp, the thrown three in
// oracool/paladin_ranged.cpp).
// sManaCost mirrors oracool/paladin_skills.cpp's table and exists here only so the Abilities window
// and the mana check can price the row - that file stays the one place the numbers are decided.
/*SpellID::Zeal*/             { P_("spell", "Zeal"),               IS_CAST2,           0,            0,          2, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::HammerOfFaith*/    { P_("spell", "Hammer of Faith"),    IS_CAST2,           0,            0,          5, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         5,          0,          0 },
/*SpellID::BlessedShield*/    { P_("spell", "Blessed Shield"),     IS_CAST2,           0,            0,         10, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,        10,          0,          0 },
/*SpellID::FistOfTheHeavens*/ { P_("spell", "Fist of the Heavens"), IS_CAST2,          0,            0,         15, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,        15,          0,          0 },
/*SpellID::ShieldBash*/       { P_("spell", "Shield Bash"),        IS_CAST2,           0,            0,          3, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         3,          0,          0 },
/*SpellID::BlessedHammer*/    { P_("spell", "Blessed Hammer"),     IS_CAST2,           0,            0,          8, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         8,          0,          0 },
// Oracool, Round 1: Ice Bolt. Firebolt's numbers almost exactly - it is the cold twin of the spell
// you cast a thousand times, and the brief says so in as many words - with two deliberate
// differences.
//
// sBookLvl and sStaffLvl are BOTH -1, like every tree skill this fork has added: cold is earned on
// the Sorceress's page, not found in a book, and a droppable id would also move the loot tables for
// every seed (see MAX_ITEM_SPELLS's note). minInt 0 for the same reason - the tree's own gate is
// what says who may cast it.
/*SpellID::IceBolt*/          { P_("spell", "Ice Bolt"),           IS_CAST2,           0,            0,          6, Cold | Targeted,              -1,         -1,       0, { MissileID::IceBolt,              MissileID::Null,    },         1,         3,          0,          0 },
// Oracool, Round 2: the rest of the cold page. Same rules as Ice Bolt - earned on the tree, never
// found, so -1/-1 and minInt 0. Mana costs climb the page the way the fire line's do (Firebolt 6,
// Fireball 16, Flame Wave 35); the armours are priced like Mana Shield's neighbours, one cast for a
// long effect. The three armours are NOT Targeted: they land on the caster wherever the cursor is.
/*SpellID::IceBlast*/         { P_("spell", "Ice Blast"),          IS_CAST2,           0,            0,         10, Cold | Targeted,              -1,         -1,       0, { MissileID::IceBlast,             MissileID::Null,    },         1,         5,          0,          0 },
/*SpellID::GlacialSpike*/     { P_("spell", "Glacial Spike"),      IS_CAST2,           0,            0,         16, Cold | Targeted,              -1,         -1,       0, { MissileID::GlacialSpike,         MissileID::Null,    },         1,         8,          0,          0 },
/*SpellID::FrostNova*/        { P_("spell", "Frost Nova"),         IS_CAST2,           0,            0,         14, Cold,                         -1,         -1,       0, { MissileID::FrostNova,            MissileID::Null,    },         1,         7,          0,          0 },
/*SpellID::Blizzard*/         { P_("spell", "Blizzard"),           IS_CAST2,           0,            0,         28, Cold | Targeted,              -1,         -1,       0, { MissileID::Blizzard,             MissileID::Null,    },         1,        14,          0,          0 },
/*SpellID::FrozenOrb*/        { P_("spell", "Frozen Orb"),         IS_CAST2,           0,            0,         30, Cold | Targeted,              -1,         -1,       0, { MissileID::FrozenOrb,            MissileID::Null,    },         1,        15,          0,          0 },
/*SpellID::FrozenArmor*/      { P_("spell", "Frozen Armor"),       IS_CAST2,           0,            0,         12, Cold | AllowedInTown,         -1,         -1,       0, { MissileID::ColdArmor,            MissileID::Null,    },         0,        12,          0,          0 },
/*SpellID::ShiverArmor*/      { P_("spell", "Shiver Armor"),       IS_CAST2,           0,            0,         14, Cold | AllowedInTown,         -1,         -1,       0, { MissileID::ColdArmor,            MissileID::Null,    },         0,        14,          0,          0 },
/*SpellID::ChillingArmor*/    { P_("spell", "Chilling Armor"),     IS_CAST2,           0,            0,         16, Cold | AllowedInTown,         -1,         -1,       0, { MissileID::ColdArmor,            MissileID::Null,    },         0,        16,          0,          0 },
// Oracool, Round 3: the bow skills. MissileID::Null in both slots on purpose - these are SHOT, not
// cast (oracool/rogue_arrows.h), exactly as Zeal is swung. The MagicType names the element for the
// book colour and the cast animation, which a bow skill never plays; mana climbs the page. Targeted,
// so the well and the cursor treat them as something aimed. No book, no staff, no minInt - earned.
/*SpellID::MagicArrow*/       { P_("spell", "Magic Arrow"),        IS_CAST2,           0,            0,          2, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         1,          0,          0 },
/*SpellID::FireArrow*/        { P_("spell", "Fire Arrow"),         IS_CAST2,           0,            0,          3, Fire | Targeted,              -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::ColdArrow*/        { P_("spell", "Cold Arrow"),         IS_CAST2,           0,            0,          3, Cold | Targeted,              -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::MultipleShot*/     { P_("spell", "Multiple Shot"),      IS_CAST2,           0,            0,          4, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         3,          0,          0 },
/*SpellID::ExplodingArrow*/   { P_("spell", "Exploding Arrow"),    IS_CAST2,           0,            0,          5, Fire | Targeted,              -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         3,          0,          0 },
/*SpellID::IceArrow*/         { P_("spell", "Ice Arrow"),          IS_CAST2,           0,            0,          5, Cold | Targeted,              -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         3,          0,          0 },
/*SpellID::GuidedArrow*/      { P_("spell", "Guided Arrow"),       IS_CAST2,           0,            0,          6, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         4,          0,          0 },
/*SpellID::Strafe*/           { P_("spell", "Strafe"),             IS_CAST2,           0,            0,          8, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         5,          0,          0 },
/*SpellID::ImmolationArrow*/  { P_("spell", "Immolation Arrow"),   IS_CAST2,           0,            0,          8, Fire | Targeted,              -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         5,          0,          0 },
/*SpellID::FreezingArrow*/    { P_("spell", "Freezing Arrow"),     IS_CAST2,           0,            0,          9, Cold | Targeted,              -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         6,          0,          0 },
// Oracool, Round 4: the melee skills, swung through oracool/melee_skills.h. Priced like Zeal's
// neighbours - a few mana a swing, charged when the blow lands. The two leaps are priced higher
// because they move the character, which the others do not.
/*SpellID::Bash*/             { P_("spell", "Bash"),               IS_CAST2,           0,            0,          2, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         1,          0,          0 },
/*SpellID::Leap*/             { P_("spell", "Leap"),               IS_CAST2,           0,            0,          6, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         4,          0,          0 },
/*SpellID::DoubleSwing*/      { P_("spell", "Double Swing"),       IS_CAST2,           0,            0,          3, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::Stun*/             { P_("spell", "Stun"),               IS_CAST2,           0,            0,          3, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::LeapAttack*/       { P_("spell", "Leap Attack"),        IS_CAST2,           0,            0,          8, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         5,          0,          0 },
/*SpellID::Concentrate*/      { P_("spell", "Concentrate"),        IS_CAST2,           0,            0,          4, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::Frenzy*/           { P_("spell", "Frenzy"),             IS_CAST2,           0,            0,          5, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         3,          0,          0 },
/*SpellID::Whirlwind*/        { P_("spell", "Whirlwind"),          IS_CAST2,           0,            0,          8, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         5,          0,          0 },
/*SpellID::BerserkBlow*/         { P_("spell", "Berserk"),            IS_CAST2,           0,            0,          6, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         4,          0,          0 },
/*SpellID::SweepingReed*/     { P_("spell", "Sweeping Reed"),      IS_CAST2,           0,            0,          3, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::BreakingCurrent*/  { P_("spell", "Breaking Current"),   IS_CAST2,           0,            0,          3, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::VaultingStrike*/   { P_("spell", "Vaulting Strike"),    IS_CAST2,           0,            0,          8, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         5,          0,          0 },
/*SpellID::WheelOfHeaven*/    { P_("spell", "Wheel of Heaven"),    IS_CAST2,           0,            0,          6, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         4,          0,          0 },
/*SpellID::SevenReeds*/       { P_("spell", "Seven Reeds"),        IS_CAST2,           0,            0,          6, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         4,          0,          0 },
/*SpellID::OpenPalm*/         { P_("spell", "Open Palm"),          IS_CAST2,           0,            0,          2, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         1,          0,          0 },
/*SpellID::HundredFists*/     { P_("spell", "Hundred Fists"),      IS_CAST2,           0,            0,          6, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         4,          0,          0 },
/*SpellID::RadiantPalm*/      { P_("spell", "Radiant Palm"),       IS_CAST2,           0,            0,          5, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                 MissileID::Null,    },         0,         3,          0,          0 },
	// Oracool, Round 6: the cries. Untargeted, one shared missile that calls CastWarcry.
/*SpellID::Howl*/             { P_("spell", "Howl"),                IS_CAST2,           0,            0,          4, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::Taunt*/            { P_("spell", "Taunt"),               IS_CAST2,           0,            0,          3, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::Shout*/            { P_("spell", "Shout"),               IS_CAST2,           0,            0,          6, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::BattleCry*/        { P_("spell", "Battle Cry"),          IS_CAST2,           0,            0,          5, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::BattleOrders*/     { P_("spell", "Battle Orders"),       IS_CAST2,           0,            0,          7, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::WarCry*/           { P_("spell", "War Cry"),             IS_CAST2,           0,            0,          8, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::BattleCommand*/    { P_("spell", "Battle Command"),      IS_CAST2,           0,            0,         10, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::Lullaby*/          { P_("spell", "Lullaby"),             IS_CAST2,           0,            0,          6, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::SoundShock*/       { P_("spell", "Sound Shock"),         IS_CAST2,           0,            0,          4, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::BardShout*/        { P_("spell", "Shout"),               IS_CAST2,           0,            0,          5, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::Daze*/             { P_("spell", "Daze"),                IS_CAST2,           0,            0,          4, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::TempleBell*/       { P_("spell", "Temple Bell"),         IS_CAST2,           0,            0,          5, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::PurifyingBreath*/  { P_("spell", "Purifying Breath"),    IS_CAST2,           0,            0,          5, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::Tranquility*/      { P_("spell", "Tranquility"),         IS_CAST2,           0,            0,          8, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::InnerSight*/       { P_("spell", "Inner Sight"),         IS_CAST2,           0,            0,          5, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::SlowMissiles*/     { P_("spell", "Slow Missiles"),       IS_CAST2,           0,            0,          5, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::Vengeance*/        { P_("spell", "Vengeance"),           IS_CAST2,           0,            0,          6, Magic,                        -1,         -1,       0, { MissileID::Warcry,               MissileID::Null,    },         0,         2,          0,          0 },
	// Oracool, Round 7: the javelin page - six thrusts (melee latch) and two thrown bolts.
/*SpellID::Jab*/              { P_("spell", "Jab"),                 IS_CAST2,           0,            0,          2, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::PowerStrike*/      { P_("spell", "Power Strike"),        IS_CAST2,           0,            0,          3, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::Impale*/           { P_("spell", "Impale"),              IS_CAST2,           0,            0,          4, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::ChargedStrike*/    { P_("spell", "Charged Strike"),      IS_CAST2,           0,            0,          4, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::Fend*/             { P_("spell", "Fend"),                IS_CAST2,           0,            0,          5, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::LightningStrike*/  { P_("spell", "Lightning Strike"),    IS_CAST2,           0,            0,          6, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::LightningBoltSkill*/ { P_("spell", "Lightning Bolt"),      IS_CAST2,           0,            0,          5, Lightning | Targeted,         -1,         -1,       0, { MissileID::LightningControl,    MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::LightningFury*/    { P_("spell", "Lightning Fury"),      IS_CAST2,           0,            0,          9, Lightning,                    -1,         -1,       0, { MissileID::Nova,                MissileID::Null,    },         0,         2,          0,          0 },
	// Oracool, Round 8: the Paladin's last three.
/*SpellID::Sacrifice*/        { P_("spell", "Sacrifice"),           IS_CAST2,           0,            0,          4, Magic | Targeted,             -1,         -1,       0, { MissileID::Null,                MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::HolyBoltSkill*/    { P_("spell", "Holy Bolt"),           IS_CAST2,           0,            0,          5, Magic | Targeted,             -1,         -1,       0, { MissileID::HolyBolt,            MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::Conversion*/       { P_("spell", "Conversion"),          IS_CAST2,           0,            0,          8, Magic | Targeted,             -1,         -1,       0, { MissileID::Warcry,              MissileID::Null,    },         0,         2,          0,          0 },
	// Oracool, Round 9: the corpse cries.
/*SpellID::FindPotion*/       { P_("spell", "Find Potion"),         IS_CAST2,           0,            0,          2, Magic | Targeted,             -1,         -1,       0, { MissileID::Warcry,              MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::FindItem*/         { P_("spell", "Find Item"),           IS_CAST2,           0,            0,          3, Magic | Targeted,             -1,         -1,       0, { MissileID::Warcry,              MissileID::Null,    },         0,         2,          0,          0 },
/*SpellID::GrimWard*/         { P_("spell", "Grim Ward"),           IS_CAST2,           0,            0,          5, Magic | Targeted,             -1,         -1,       0, { MissileID::Warcry,              MissileID::Null,    },         0,         2,          0,          0 },
	// clang-format on
};

} // namespace devilution
