#include "oracool/charms.h"

#include <fmt/format.h>

#include <algorithm>
#include <vector>

#include "items.h"
#include "oracool/salvage.h"
#include "oracool/signets.h"
#include "oracool/stat_sheet.h"
#include "player.h"
#include "utils/language.h"

namespace devilution::oracool {

namespace {

struct CharmData {
	uint16_t idx;
	int hitPoints; // whole HP
	int fireRes;
	int lightningRes;
	int allRes; // all four schools (the Mourning Token)
	int toHit;
	int magicFind;
	int goldFind;
};

constexpr CharmData Charms[] = {
	{ IDI_ORACOOL_CHARM_VIGOR, 20, 0, 0, 0, 0, 0, 0 },
	{ IDI_ORACOOL_CHARM_EMBERS, 0, 15, 0, 0, 0, 0, 0 },
	{ IDI_ORACOOL_CHARM_STORMS, 0, 0, 15, 0, 0, 0, 0 },
	{ IDI_ORACOOL_CHARM_FORTUNE, 0, 0, 0, 0, 12, 0, 0 },
	{ IDI_ORACOOL_CHARM_LUCK, 0, 0, 0, 0, 0, 15, 0 },
	{ IDI_ORACOOL_CHARM_GREED, 0, 0, 0, 0, 0, 0, 30 },
	// Phase 4's encounter rewards. Deliberately BIG and NARROW: each is worth clearly more than any
	// ordinary charm in its one stat and offers nothing else, so choosing to carry one costs a
	// slot of the three-charm cap rather than merely filling it. That is what makes three signature
	// charms a decision instead of an inventory rule.
	//
	// The Mourning Token is "+18% to all resistances" (its generated row). It was spelled as fire and lightning only,
	// with no magic or cold, and its line printed the fire half alone (round 11 audit, v1.12.236) - so it has its own
	// all-resist column now.
	{ IDI_ORACOOL_CHARM_CHAPEL, 60, 0, 0, 0, 0, 0, 0 },
	{ IDI_ORACOOL_CHARM_MOURNING, 0, 0, 0, 18, 0, 0, 0 },
	{ IDI_ORACOOL_CHARM_VAULT, 0, 0, 0, 0, 0, 40, 0 },
};

const CharmData *FindCharm(uint16_t charmIdx)
{
	for (const CharmData &charm : Charms) {
		if (charm.idx == charmIdx)
			return &charm;
	}
	return nullptr;
}

/**
 * @brief Which stat a growing charm grows. GENERATED names, matched to the table below.
 *
 * An enum rather than a field name string, so adding a growing charm that grows something new is a
 * compile error here rather than a charm that silently grows nothing.
 */
enum class GrowingStat : uint8_t {
	TRIALS,
	DEEDS,
	LEGEND,
};

struct GrowingCharmData {
	uint16_t idx;
	GrowingStat stat;
	int base;
	int perMilestone;
	const char *lineFragment;
};

/** GENERATED by tools/GenGrowingCharms.ps1 - do not edit by hand. */
constexpr GrowingCharmData GrowingCharms[] = {
#include "oracool/growing_charms_growth.inc"
};

const GrowingCharmData *FindGrowingCharm(uint16_t charmIdx)
{
	for (const GrowingCharmData &charm : GrowingCharms) {
		if (charm.idx == charmIdx)
			return &charm;
	}
	return nullptr;
}

/**
 * @brief What @p charm is worth to @p player right now.
 *
 * base + perMilestone x claimed. The growth belongs to the CHARACTER, not the object, so two copies
 * of the same charm are worth the same - which is the trade that let this phase cost no per-item
 * state and no format bump. See tools/GenGrowingCharms.ps1.
 */
int GrowingCharmValue(const Player &player, const GrowingCharmData &charm)
{
	int claimed = 0;
	for (int i = 0; i < MilestoneCount; i++) {
		if (IsMilestoneClaimed(player, static_cast<Milestone>(i)))
			claimed++;
	}
	return charm.base + charm.perMilestone * claimed;
}

} // namespace

void ApplyCharmToTotals(const Player &player, uint16_t charmIdx, ItemBonusTotals &totals)
{
	if (const GrowingCharmData *growing = FindGrowingCharm(charmIdx); growing != nullptr) {
		const int value = GrowingCharmValue(player, *growing);
		switch (growing->stat) {
		case GrowingStat::TRIALS:
			totals.hitPoints += value << 6; // whole HP, like the fixed charms
			break;
		case GrowingStat::DEEDS:
			totals.fireResist += value;
			totals.lightningResist += value;
			totals.magicResist += value;
			totals.coldResist += value;
			break;
		case GrowingStat::LEGEND:
			totals.magicFind += value;
			break;
		}
		return;
	}

	const CharmData *charm = FindCharm(charmIdx);
	if (charm == nullptr)
		return;
	totals.hitPoints += charm->hitPoints << 6;
	totals.fireResist += charm->fireRes + charm->allRes;
	totals.lightningResist += charm->lightningRes + charm->allRes;
	totals.magicResist += charm->allRes;
	totals.coldResist += charm->allRes;
	totals.bonusToHit += charm->toHit;
	totals.magicFind += charm->magicFind;
	totals.goldFind += charm->goldFind;
}

std::string CharmEffectLine(const Player &player, uint16_t charmIdx)
{
	// Charms of Salvaging carry no stat row - their effect fires at pickup time - so they answer
	// from salvage.cpp's tables instead of the CharmData table below.
	if (IsOracoolSalvageCharmIdx(charmIdx))
		return std::string(_(SalvageCharmEffectLine(charmIdx)));
	if (const GrowingCharmData *growing = FindGrowingCharm(charmIdx); growing != nullptr) {
		// The CURRENT value and the rate, both, because a charm whose worth changes silently is a
		// charm the player cannot compare against the fixed one sitting beside it.
		return fmt::format(fmt::runtime(_("+{:d} {:s} - grows +{:d} per milestone")),
		    GrowingCharmValue(player, *growing), _(growing->lineFragment), growing->perMilestone);
	}
	const CharmData *charm = FindCharm(charmIdx);
	if (charm == nullptr)
		return {};
	if (charm->hitPoints > 0)
		return fmt::format(fmt::runtime(_("+{:d} life while in your backpack")), charm->hitPoints);
	if (charm->allRes > 0)
		return fmt::format(fmt::runtime(_("+{:d}% to all resistances while in your backpack")), charm->allRes);
	if (charm->fireRes > 0)
		return fmt::format(fmt::runtime(_("+{:d}% fire resist while in your backpack")), charm->fireRes);
	if (charm->lightningRes > 0)
		return fmt::format(fmt::runtime(_("+{:d}% lightning resist while in your backpack")), charm->lightningRes);
	if (charm->magicFind > 0)
		return fmt::format(fmt::runtime(_("{:+d}% chance a plain weapon or armor found is Rare")), charm->magicFind); // the affix's own words (round 16)
	if (charm->goldFind > 0)
		return fmt::format(fmt::runtime(_("+{:d}% gold from monsters")), charm->goldFind);
	return fmt::format(fmt::runtime(_("+{:d}% to hit while in your backpack")), charm->toHit);
}

namespace {

struct CharmSlot {
	int tab; // -1 the main backpack, else the extra page
	int index;
	int key; // the anchor cell, in reading order
	uint16_t idx;
};

/**
 * @brief The hero's charms in READING order: page 1 first, then pages 2-10, and on each page by where the charm sits (its
 * anchor cell, row by row). It was list order, which every removal reshuffles - the last item swaps into the hole - so
 * using up a scroll could change which three charms were live without the grid moving (round 33 audit). A record with no
 * anchor (not placed on a grid) follows the placed ones in list order.
 */
std::vector<CharmSlot> CharmsInReadingOrder(const Player &player)
{
	std::vector<CharmSlot> slots;
	const auto anchorOf = [](const int8_t *grid, int index) {
		for (int cell = 0; cell < InventoryGridCells; cell++) {
			if (grid[cell] == index + 1)
				return cell;
		}
		return InventoryGridCells + index;
	};
	for (int i = 0; i < player._pNumInv; i++) {
		const Item &item = player.InvList[i];
		if (!item.isEmpty() && IsOracoolCharmIdx(item.IDidx))
			slots.push_back({ -1, i, anchorOf(player.InvGrid, i), static_cast<uint16_t>(item.IDidx) });
	}
	for (int tab = 0; tab < Player::NumExtraInventoryTabs; tab++) {
		for (int i = 0; i < player._pNumInvTab[tab]; i++) {
			const Item &item = player.InvTabList[tab][i];
			if (!item.isEmpty() && IsOracoolCharmIdx(item.IDidx))
				slots.push_back({ tab, i, anchorOf(player.InvTabGrid[tab].data(), i), static_cast<uint16_t>(item.IDidx) });
		}
	}
	std::stable_sort(slots.begin(), slots.end(), [](const CharmSlot &a, const CharmSlot &b) {
		return a.tab != b.tab ? a.tab < b.tab : a.key < b.key;
	});
	return slots;
}

} // namespace

void ForEachActiveCharm(const Player &player, void (*visit)(uint16_t charmIdx, void *context), void *context)
{
	const std::vector<CharmSlot> slots = CharmsInReadingOrder(player);
	for (size_t i = 0; i < slots.size() && i < static_cast<size_t>(CharmActiveCap); i++)
		visit(slots[i].idx, context);
}

int CharmActiveState(const Player &player, const Item &item)
{
	for (int i = 0; i < player._pNumInv; i++) {
		if (&player.InvList[i] == &item)
			return IsCharmActive(player, -1, i) ? 1 : 0;
	}
	for (int tab = 0; tab < Player::NumExtraInventoryTabs; tab++) {
		for (int i = 0; i < player._pNumInvTab[tab]; i++) {
			if (&player.InvTabList[tab][i] == &item)
				return IsCharmActive(player, tab, i) ? 1 : 0;
		}
	}
	return -1;
}

bool IsCharmActive(const Player &player, int tabIndex, int invListIndex)
{
	const std::vector<CharmSlot> slots = CharmsInReadingOrder(player);
	const int tab = tabIndex < 0 ? -1 : tabIndex;
	for (size_t i = 0; i < slots.size() && i < static_cast<size_t>(CharmActiveCap); i++) {
		if (slots[i].tab == tab && slots[i].index == invListIndex)
			return true;
	}
	return false;
}

} // namespace devilution::oracool
