/**
 * @file oracool/hud_plate_skin.h
 *
 * GENERATED by tools/CutHudPlate.ps1 - do not edit. Change the numbers at the top of that script
 * and re-run it; the five PNGs it writes and these come from the same pass.
 *
 * The sixth bottom HUD (Oracool.MPQ/02-source-art/delivered-packs/oracool-hud-v6-sunken-wells,
 * hud-v6.png at exactly one third). Every number is in SCREEN pixels; the plate's rects are
 * PLATE-local, the orbs' are local to their own piece. The three pieces share one bottom edge and
 * butt together left to right: health cradle, plate, mana cradle.
 *
 * The wells are OPENINGS with a three-pixel inward shadow; the well rects are the openings, and
 * SkillWellNetSize (50) is what the shadow leaves inside them.
 */
#pragma once

#include "engine/point.hpp"
#include "engine/rectangle.hpp"
#include "engine/size.hpp"

namespace devilution::oracool::hud_skin {

constexpr Size PlateSize { 386, 108 };

/** The wells' openings - transparent, the spell plate drawn beneath - plate-local. */
constexpr Rectangle LmbWell { { 6, 46 }, { 56, 56 } };
constexpr Rectangle RmbWell { { 324, 46 }, { 56, 56 } };

/** The six belt cells: the painted raised floors, from the pack's manifest. */
constexpr int BeltCellX[6] = { 72, 114, 156, 198, 240, 282 };
constexpr int BeltCellY = 76;
constexpr Size BeltCellSize { 28, 28 };
/** Plate-local y of the belt bar's top edge - what the XP bar sits above. */
constexpr int BeltBarTop = 72;

constexpr Size HealthOrbSize { 116, 108 };
constexpr Size ManaOrbSize { 111, 108 };
constexpr Point HealthSphereCenter { 65, 52 };
constexpr Point ManaSphereCenter { 47, 53 };
constexpr int SphereRadius = 34;

} // namespace devilution::oracool::hud_skin