/**
 * @file oracool/hud_plate_skin.h
 *
 * GENERATED by tools/CutHudPlate.ps1 - do not edit. Change the measurements at the top of that
 * script and re-run it; the five PNGs it writes and these numbers come from the same pass.
 *
 * The fifth bottom HUD (Oracool.MPQ/02-source-art/delivered-packs/diablo-bottom-hud-v1, cut from
 * 02-raised-stone-slot-design.png with its checkerboard keyed out, at scale 0.288). Every
 * number is in SCREEN pixels; the plate's rects are PLATE-local, the orbs' are local to their own
 * piece. The three pieces share one bottom edge and butt together left to right: health cradle,
 * plate, mana cradle. The sphere centre and radius are measured from the painting's own spheres,
 * whose interiors are cut out of the cradles and shipped as the liquid files.
 */
#pragma once

#include "engine/point.hpp"
#include "engine/rectangle.hpp"
#include "engine/size.hpp"

namespace devilution::oracool::hud_skin {

constexpr Size PlateSize { 353, 110 };

/** The wells' openings - the flat stone inside the rim - plate-local. */
constexpr Rectangle LmbWell { { 10, 52 }, { 49, 48 } };
constexpr Rectangle RmbWell { { 299, 53 }, { 50, 48 } };

/** The six belt cells: the painting's holes by alpha where it has them, its painted openings by hand where not. */
constexpr int BeltCellX[6] = { 69, 108, 146, 184, 222, 260 };
constexpr int BeltCellY = 71;
constexpr Size BeltCellSize { 25, 28 };

constexpr Size HealthOrbSize { 101, 110 };
constexpr Size ManaOrbSize { 103, 110 };
constexpr Point HealthSphereCenter { 59, 48 };
constexpr Point ManaSphereCenter { 45, 48 };
constexpr int SphereRadius = 35;

} // namespace devilution::oracool::hud_skin