/**
 * @file oracool/hud_plate_skin.h
 *
 * GENERATED by tools/CutHudPlate.ps1 - do not edit. Change the measurements at the top of that
 * script and re-run it; the three PNGs it writes and these numbers come from the same pass.
 *
 * The fifth bottom HUD (Oracool.MPQ/02-source-art/delivered-packs/diablo-bottom-hud-v1, cut from
 * 04-raised-stone-wells-true-alpha-belt.png at scale 0.288). Every number is in SCREEN pixels; the
 * plate's rects are PLATE-local, the orbs' are local to their own piece. The three pieces share one
 * bottom edge and butt together left to right: health cradle, plate, mana cradle.
 */
#pragma once

#include "engine/point.hpp"
#include "engine/rectangle.hpp"
#include "engine/size.hpp"

namespace devilution::oracool::hud_skin {

constexpr Size PlateSize { 353, 109 };

/** The wells' openings - the flat stone inside the rim - plate-local. */
constexpr Rectangle LmbWell { { 10, 52 }, { 49, 48 } };
constexpr Rectangle RmbWell { { 299, 53 }, { 50, 48 } };

/** The six belt cells are the painting's transparent holes, found by alpha. */
constexpr int BeltCellX[6] = { 70, 109, 147, 185, 224, 262 };
constexpr int BeltCellY = 71;
constexpr Size BeltCellSize { 25, 27 };

constexpr Size HealthOrbSize { 101, 109 };
constexpr Size ManaOrbSize { 102, 109 };
constexpr Point HealthSphereCenter { 60, 50 };
constexpr Point ManaSphereCenter { 42, 50 };
constexpr int SphereRadius = 39;

} // namespace devilution::oracool::hud_skin