/**
 * @file oracool/item_sets.h
 *
 * The fifteen item sets, as data.
 *
 * Ninety-four named items across fifteen sets, each with a slot, a base type, requirements and a
 * handful of stats, plus 73 tiered set bonuses (2-piece through 6-piece). Delivered as JSON and
 * filed at Oracool.MPQ/02-source-art/item-sets.
 *
 * The tables live in item_sets_data.inc and are GENERATED by tools/GenItemSets.ps1 straight from
 * that JSON - see the note at the top of the script. Nothing here is hand-typed, which is the only
 * way ninety-four items stay in step with the content they came from.
 *
 * Stat keywords are resolved through oracool/item_set_stats.h on the way in. A keyword with no
 * channel in this engine contributes nothing rather than something approximate-and-unstated, so an
 * item's power list is only what the item really does. Two consequences worth knowing:
 *
 *   - An item can carry fewer powers than its design lists. Vhal's Girdle of Coals declares four
 *     stats and carries three; `potion_healing` has nowhere to go.
 *   - A whole bonus tier can be empty. "Cinderbrand", the four-piece of the Ashen Saint, is a single
 *     `proc:` and so does nothing at all yet. It is still NAMED, because a player who assembles four
 *     pieces should be told what they earned even while it is inert.
 *
 * 390 of the 540 declared stat lines survive the trip. The rest are listed in
 * oracool/item_set_stats.cpp with a note saying what building them would take.
 */
#pragma once

#include <cstddef>

#include "engine/size.hpp"
#include "itemdat.h"
#include "utils/stdcompat/string_view.hpp"

namespace devilution::oracool {

/** @brief One of the ninety-four items. */
struct SetItemDefinition {
	/** @brief Stable id from set-data.json, e.g. "SET_ASHEN_HELM". Never shown to a player. */
	const char *id;
	/** @brief Untranslated; run through _() at the point of display. */
	const char *name;
	/** @brief The design's slot word ("helm", "torso", "main_hand", ...), not an engine enum yet. */
	const char *slot;
	/** @brief The design's base item ("great_helm", "plate_mail", ...), not an engine enum yet. */
	const char *baseType;
	int requiredLevel;
	int requiredStrength;
	/** @brief 255 means indestructible - the engine's own DUR_INDESTRUCTIBLE sentinel. */
	int durability;
	/** @brief Inventory footprint in cells. */
	Size grid;
	/** @brief Weapons only; 0/0 on armour. */
	int damageMin;
	int damageMax;
	/** @brief Armour only; 0/0 on weapons. */
	int armorMin;
	int armorMax;
	/** @brief Only the stats this engine can actually apply. Unused slots are IPL_INVALID. */
	ItemPower powers[6];
};

/** @brief One rung of a set's bonus ladder - what wearing @ref pieces of it grants. */
struct SetBonusDefinition {
	int pieces;
	/** @brief Untranslated. Named even when it grants nothing yet. */
	const char *name;
	ItemPower powers[4];
};

struct ItemSetDefinition {
	const char *id;
	/** @brief Untranslated. */
	const char *name;
	int requiredLevel;
	/** @brief Index into ItemSetItems, and how many are this set's. */
	int firstItem;
	int itemCount;
	/** @brief Index into ItemSetBonuses, and how many rungs this set's ladder has. */
	int firstBonus;
	int bonusCount;
};

constexpr size_t ItemSetCount = 15;
constexpr size_t ItemSetItemCount = 94;
constexpr size_t ItemSetBonusCount = 73;

extern DVL_API_FOR_TEST const ItemSetDefinition ItemSets[ItemSetCount];
extern DVL_API_FOR_TEST const SetItemDefinition ItemSetItems[ItemSetItemCount];
extern DVL_API_FOR_TEST const SetBonusDefinition ItemSetBonuses[ItemSetBonusCount];

/** @brief The set @p itemId belongs to, or nullptr. */
const ItemSetDefinition *FindItemSetOwning(string_view itemId);

/** @brief The item with this id, or nullptr. */
const SetItemDefinition *FindSetItem(string_view itemId);

/**
 * @brief The highest bonus rung @p set grants for @p wornPieces, or nullptr below the first rung.
 *
 * The rungs are cumulative in Diablo II and are NOT here: a rung replaces the one below it rather
 * than stacking on it. That is the simpler reading of a ladder whose upper rungs already restate the
 * lower ones' stats, and it is what the delivered data describes - the Ashen Saint's five-piece
 * carries its own resistances rather than assuming the two-piece is still applied.
 */
const SetBonusDefinition *ActiveSetBonus(const ItemSetDefinition &set, int wornPieces);

/** @brief How many of @p set's stat lines actually do something - 0 means an entirely inert rung. */
int CountLivePowers(const ItemPower *powers, size_t count);

} // namespace devilution::oracool
