/**
 * @file oracool/item_sets.h
 *
 * The fifteen item sets, as data.
 *
 * Ninety-four named items across fifteen sets, each with a slot, a base type, requirements and a
 * handful of stats, plus 73 tiered set bonuses (2-piece through 6-piece). Delivered as JSON and
 * filed at Oracool.MPQ/02-source-art/item-sets.
 *
 * The tables live in item_sets_data.inc and are GENERATED by tools/GenItemSets.ps1 straight from
 * that JSON - see the note at the top of the script. Nothing here is hand-typed, which is the only
 * way ninety-four items stay in step with the content they came from.
 *
 * Stat keywords are resolved through oracool/item_set_stats.h on the way in. A keyword with no
 * channel in this engine contributes nothing rather than something approximate-and-unstated, so an
 * item's power list is only what the item really does. Two consequences worth knowing:
 *
 *   - An item can carry fewer powers than its design lists. Vhal's Girdle of Coals declares four
 *     stats and carries three; `potion_healing` has nowhere to go.
 *   - A whole bonus tier can be empty. "Cinderbrand", the four-piece of the Ashen Saint, is a single
 *     `proc:` and so does nothing at all yet. It is still NAMED, because a player who assembles four
 *     pieces should be told what they earned even while it is inert.
 *
 * 390 of the 540 declared stat lines survive the trip. The rest are listed in
 * oracool/item_set_stats.cpp with a note saying what building them would take.
 */
#pragma once

#include <cstddef>

#include "engine/size.hpp"
#include "itemdat.h"
#include "utils/stdcompat/string_view.hpp"

namespace devilution {

// Forward declarations rather than includes: items.h and player.h both pull in a great deal, and
// this header is included from itemdat-adjacent code where that would be circular.
struct Item;
struct Player;

namespace oracool {

struct ItemBonusTotals;

/** @brief One of the ninety-four items. */
struct SetItemDefinition {
	/** @brief Stable id from set-data.json, e.g. "SET_ASHEN_HELM". Never shown to a player. */
	const char *id;
	/** @brief Untranslated; run through _() at the point of display. */
	const char *name;
	/** @brief The design's slot word ("helm", "torso", "main_hand", ...), not an engine enum yet. */
	const char *slot;
	/** @brief The design's base item ("great_helm", "plate_mail", ...), not an engine enum yet. */
	const char *baseType;
	int requiredLevel;
	int requiredStrength;
	/** @brief 255 means indestructible - the engine's own DUR_INDESTRUCTIBLE sentinel. */
	int durability;
	/** @brief Inventory footprint in cells. */
	Size grid;
	/** @brief Weapons only; 0/0 on armour. */
	int damageMin;
	int damageMax;
	/** @brief Armour only; 0/0 on weapons. */
	int armorMin;
	int armorMax;
	/**
	 * @brief The item's own icon: an ICURS_ORACOOL_SET_* frame in data\inv\oracool_items.cel.
	 *
	 * Generated alongside the row, so the id, the CEL frame and the width/height tables all come out
	 * of one walk in one order. A CEL carries no names and no sizes - a frame's POSITION is the only
	 * thing tying it to an id - so any of those four drifting silently shifts every icon after it.
	 */
	int cursor;
	/** @brief Only the stats this engine can actually apply. Unused slots are IPL_INVALID. */
	ItemPower powers[6];
};

/** @brief One rung of a set's bonus ladder - what wearing @ref pieces of it grants. */
struct SetBonusDefinition {
	int pieces;
	/** @brief Untranslated. Named even when it grants nothing yet. */
	const char *name;
	ItemPower powers[4];
};

struct ItemSetDefinition {
	const char *id;
	/** @brief Untranslated. */
	const char *name;
	int requiredLevel;
	/** @brief Index into ItemSetItems, and how many are this set's. */
	int firstItem;
	int itemCount;
	/** @brief Index into ItemSetBonuses, and how many rungs this set's ladder has. */
	int firstBonus;
	int bonusCount;
};

constexpr size_t ItemSetCount = 15;
constexpr size_t ItemSetItemCount = 94;
constexpr size_t ItemSetBonusCount = 73;

extern DVL_API_FOR_TEST const ItemSetDefinition ItemSets[ItemSetCount];
extern DVL_API_FOR_TEST const SetItemDefinition ItemSetItems[ItemSetItemCount];
extern DVL_API_FOR_TEST const SetBonusDefinition ItemSetBonuses[ItemSetBonusCount];

/** @brief The set @p itemId belongs to, or nullptr. */
const ItemSetDefinition *FindItemSetOwning(string_view itemId);

/** @brief The item with this id, or nullptr. */
const SetItemDefinition *FindSetItem(string_view itemId);

/**
 * @brief The highest bonus rung @p set grants for @p wornPieces, or nullptr below the first rung.
 *
 * The rungs are cumulative in Diablo II and are NOT here: a rung replaces the one below it rather
 * than stacking on it. That is the simpler reading of a ladder whose upper rungs already restate the
 * lower ones' stats, and it is what the delivered data describes - the Ashen Saint's five-piece
 * carries its own resistances rather than assuming the two-piece is still applied.
 */
const SetBonusDefinition *ActiveSetBonus(const ItemSetDefinition &set, int wornPieces);

/** @brief How many of @p set's stat lines actually do something - 0 means an entirely inert rung. */
int CountLivePowers(const ItemPower *powers, size_t count);

/**
 * @brief The set item whose icon is @p cursor, or nullptr.
 *
 * The icon IS the identity. Every one of the ninety-four has a frame of its own
 * (ICURS_ORACOOL_SET_*), so a set piece needs no extra field on Item to be recognised later - which
 * means recognising them costs no save-format change at all. _iCurs is already packed, already
 * synced and already survives a round trip.
 */
const SetItemDefinition *FindSetItemByCursor(int cursor);

/** @brief Whether @p item is a piece of one of the fifteen sets. */
bool IsSetItem(const Item &item);

/**
 * @brief Turns @p item into @p def: name, icon, footprint, requirements, stats, and the Set tier.
 *
 * The caller supplies an item already initialised from a sensible BASE (InitializeItem with a base
 * index whose ILOC matches the definition's slot). This overrides the parts that make it the named
 * object rather than the base, and applies its powers through the engine's own SaveItemPower so a
 * set item's stats land in exactly the fields every other item's stats land in.
 */
void MakeSetItem(Item &item, const SetItemDefinition &def);

/** @brief The base item index whose equip location suits @p slot, or -1 if no slot matches. */
int BaseItemForSetSlot(string_view slot);

/**
 * @brief How many pieces of @p set the player is wearing, counting equipped slots only.
 *
 * Carried pieces do not count - a set bonus is for wearing the set.
 */
int WornSetPieces(const Player &player, const ItemSetDefinition &set);

/** @brief Whether @p player is wearing enough of any one set to have earned a rung. */
bool AnySetBonusActive(const Player &player);

/**
 * @brief Adds every earned set bonus to @p totals.
 *
 * Rides the bonus-provider seam from Phase 0.4, which was built with exactly this in mind - its
 * header names "three pieces worn?" as the condition hook's reason for existing.
 *
 * Every set is considered independently, so wearing four of one and two of another earns both
 * ladders' rungs. Within one set only the highest rung applies; see ActiveSetBonus.
 */
void ApplySetBonusesToTotals(const Player &player, ItemBonusTotals &totals);

} // namespace oracool
} // namespace devilution
