/**
 * @file oracool/levski_roar_skin.h
 *
 * GENERATED by tools/CutLevskiRoarSkin.ps1 - do not edit. Change the measurements at the top of
 * that script and re-run it; the art it writes and these numbers come from the same pass.
 *
 * The painted Levski's Roar window (Oracool.MPQ/02-source-art/delivered-packs/
 * oracool-levski-roar-skin), resampled to 509x637 - the scale at which its ~185px
 * painted grid cells become 3x the game's 28px item cell. Every rect below is in WINDOW pixels.
 *
 * State sheets whose lit plate was cut off in delivery, and so wear the plain plate for hover too:
 * transmute, basic, ethereal.
 */
#pragma once

#include "engine/point.hpp"
#include "engine/rectangle.hpp"
#include "engine/size.hpp"

namespace devilution::oracool::levski_skin {

constexpr Size WindowSize { 509, 637 };
constexpr int CellSize = 84;
constexpr Point GridOrigin { 51, 195 };

/** The ten plates, in ButtonIndex order. */
enum ButtonIndex : int {
	Close = 0,
	Transmute = 1,
	Recipes = 2,
	SalvageFirst = 3, // Basic; the seven salvage tiers follow in SalvageTier order
};
constexpr int ButtonCount = 10;

constexpr Rectangle ButtonRects[ButtonCount] = {
	{ { 443, 52 }, { 33, 31 } }, // close
	{ { 54, 532 }, { 232, 54 } }, // transmute
	{ { 308, 535 }, { 160, 50 } }, // recipes
	{ { 338, 213 }, { 128, 36 } }, // basic
	{ { 338, 255 }, { 128, 36 } }, // magic
	{ { 338, 296 }, { 128, 36 } }, // rare
	{ { 338, 338 }, { 128, 36 } }, // unique
	{ { 338, 380 }, { 128, 36 } }, // set
	{ { 338, 422 }, { 128, 36 } }, // primal
	{ { 338, 464 }, { 128, 36 } }, // ethereal
};

/** ui\ asset stem per button - levski_<stem>_hover.png and levski_<stem>_pressed.png. */
constexpr const char *ButtonStems[ButtonCount] = {
	"close",
	"transmute",
	"recipes",
	"basic",
	"magic",
	"rare",
	"unique",
	"set",
	"primal",
	"ethereal",
};

/** True where the hover file is the PLAIN plate (the lit one was cut off in delivery), so the game
 * has to mark hover some other way. */
constexpr bool HoverIsPlain[ButtonCount] = {
	false, // close
	true, // transmute
	false, // recipes
	true, // basic
	false, // magic
	false, // rare
	false, // unique
	false, // set
	false, // primal
	true, // ethereal
};

} // namespace devilution::oracool::levski_skin