/**
 * @file oracool/levski_roar_skin.h
 *
 * GENERATED by tools/CutLevskiRoarSkin.ps1 - do not edit. Change the measurements at the top of
 * that script and re-run it; the art it writes and these numbers come from the same pass.
 *
 * The painted Levski's Roar window (Oracool.MPQ/levskis roar.png, the user's own 261x241 painting),
 * resampled to 252x233 - the scale at which its painted grid cells (29 px pitch) become the
 * game's 28px item cell. The nine controls are GPT's icon-controls-v3 pack, 32x32 plates in a 3x3
 * block right of the grid; they are drawn by the game in all three states from
 * ui\levski_<stem>_{default,hover,pressed}.png, since the painting carries no plates for them. Every
 * rect below is in WINDOW pixels.
 */
#pragma once

#include "engine/point.hpp"
#include "engine/rectangle.hpp"
#include "engine/size.hpp"

namespace devilution::oracool::levski_skin {

constexpr Size WindowSize { 252, 233 };
constexpr int CellSize = 28;
constexpr int GridColumns = 3;
constexpr int GridRows = 4;
constexpr Point GridOrigin { 34, 89 };
/** The SALVAGE title's band over the 3x3 block: gold, 24px, shadowed, centred (levski_roar.cpp). */
constexpr Rectangle SalvageTitleRect { { 130, 78 }, { 102, 22 } };

/** The ten controls, in ButtonIndex order. */
enum ButtonIndex : int {
	Close = 0,
	Transmute = 1,
	Recipes = 2,
	SalvageFirst = 3, // White; the seven salvage tiers follow in SalvageTier order
};
constexpr int ButtonCount = 10;

constexpr Rectangle ButtonRects[ButtonCount] = {
	{ { 231, 32 }, { 18, 18 } }, // close
	{ { 165, 174 }, { 32, 32 } }, // transmute
	{ { 200, 174 }, { 32, 32 } }, // recipes
	{ { 130, 102 }, { 32, 32 } }, // white
	{ { 165, 102 }, { 32, 32 } }, // magic
	{ { 200, 102 }, { 32, 32 } }, // rare
	{ { 130, 138 }, { 32, 32 } }, // unique
	{ { 165, 138 }, { 32, 32 } }, // primal
	{ { 200, 138 }, { 32, 32 } }, // set
	{ { 130, 174 }, { 32, 32 } }, // ethereal
};

/** ui\ asset stem per button - levski_<stem>_default.png, _hover.png and _pressed.png. The close button has none. */
constexpr const char *ButtonStems[ButtonCount] = {
	"close",
	"transmute",
	"recipes",
	"white",
	"magic",
	"rare",
	"unique",
	"primal",
	"set",
	"ethereal",
};

/** True where the hover file, if any, is the PLAIN plate, so the game has to mark hover itself. */
constexpr bool HoverIsPlain[ButtonCount] = {
	false, // close
	false, // transmute
	false, // recipes
	false, // white
	false, // magic
	false, // rare
	false, // unique
	false, // primal
	false, // set
	false, // ethereal
};

} // namespace devilution::oracool::levski_skin