/**
 * @file oracool/levski_roar_skin.h
 *
 * GENERATED by tools/CutLevskiRoarSkin.ps1 - do not edit. Change the measurements at the top of
 * that script and re-run it; the art it writes and these numbers come from the same pass.
 *
 * The painted Levski's Roar window (Oracool.MPQ/levskis roar.png, the user's own 320x352 painting),
 * shipped 1:1 with every control painted in at rest. The game lays ui\levski_<stem>_hover.png or
 * _pressed.png over a control while the cursor is on it or the press flash runs; there is no
 * default file, the painting is the default. The grid is painted at GridPitch; the game's item cell
 * is CellSize. Every rect below is in WINDOW pixels.
 */
#pragma once

#include "engine/point.hpp"
#include "engine/rectangle.hpp"
#include "engine/size.hpp"

namespace devilution::oracool::levski_skin {

constexpr Size WindowSize { 320, 352 };
constexpr int CellSize = 28;
/** The painted grid's centre-to-centre pitch; the item cell sits inside it. */
constexpr int GridPitch = 29;
constexpr int GridColumns = 3;
constexpr int GridRows = 4;
constexpr Point GridOrigin { 45, 111 };
/** No code-drawn title: SALVAGE is painted on its stone plate. Zero-sized, and the window skips it. */
constexpr Rectangle SalvageTitleRect { { 0, 0 }, { 0, 0 } };

/** The ten controls, in ButtonIndex order. */
enum ButtonIndex : int {
	Close = 0,
	Transmute = 1,
	Recipes = 2,
	SalvageFirst = 3, // White; the seven salvage tiers follow in SalvageTier order
};
constexpr int ButtonCount = 10;

constexpr Rectangle ButtonRects[ButtonCount] = {
	{ { 299, 3 }, { 18, 18 } }, // close
	{ { 57, 251 }, { 60, 60 } }, // transmute
	{ { 229, 258 }, { 36, 36 } }, // recipes
	{ { 170, 138 }, { 36, 36 } }, // white
	{ { 229, 138 }, { 36, 36 } }, // magic
	{ { 170, 178 }, { 36, 36 } }, // rare
	{ { 229, 178 }, { 36, 36 } }, // unique
	{ { 170, 218 }, { 36, 36 } }, // primal
	{ { 229, 218 }, { 36, 36 } }, // set
	{ { 170, 258 }, { 36, 36 } }, // ethereal
};

/** ui\ asset stem per button - levski_<stem>_hover.png and _pressed.png. The close button has none. */
constexpr const char *ButtonStems[ButtonCount] = {
	"close",
	"transmute",
	"recipes",
	"white",
	"magic",
	"rare",
	"unique",
	"primal",
	"set",
	"ethereal",
};

/** True where the hover file, if any, is the PLAIN plate, so the game has to mark hover itself. */
constexpr bool HoverIsPlain[ButtonCount] = {
	false, // close
	false, // transmute
	false, // recipes
	false, // white
	false, // magic
	false, // rare
	false, // unique
	false, // primal
	false, // set
	false, // ethereal
};

} // namespace devilution::oracool::levski_skin