#include "oracool/mystic_orbs.h"

#include <fmt/format.h>

#include "items.h"
#include "player.h"
#include "utils/language.h"

namespace devilution::oracool {

namespace {

struct MysticOrbData {
	_item_indexes idx;
	ItemPower power;
	const char *line;
};

/**
 * @brief The eight orbs. GENERATED by tools/GenMysticOrbs.ps1 - do not edit by hand.
 *
 * param1 == param2 on every row, deliberately: SaveItemPower rolls a range between them, and an orb
 * that rolled would be an affix wearing a different name.
 */
constexpr MysticOrbData Orbs[] = {
#include "oracool/mystic_orbs_powers.inc"
};

constexpr size_t OrbCount = sizeof(Orbs) / sizeof(Orbs[0]);

const MysticOrbData *FindOrb(int idx)
{
	for (const MysticOrbData &orb : Orbs) {
		if (orb.idx == idx)
			return &orb;
	}
	return nullptr;
}

} // namespace

int FirstMysticOrbIdx() { return IDI_ORACOOL_ORB_MIGHT; }
int LastMysticOrbIdx() { return IDI_ORACOOL_ORB_AVARICE; }

bool IsMysticOrbIdx(int idx)
{
	return idx >= FirstMysticOrbIdx() && idx <= LastMysticOrbIdx();
}

ItemPower MysticOrbPower(int orbIdx)
{
	const MysticOrbData *orb = FindOrb(orbIdx);
	return orb != nullptr ? orb->power : ItemPower { IPL_INVALID, 0, 0 };
}

const char *MysticOrbLine(int orbIdx)
{
	const MysticOrbData *orb = FindOrb(orbIdx);
	return orb != nullptr ? orb->line : "";
}

bool CanReceiveMysticOrb(const Item &target)
{
	if (target.isEmpty())
		return false;
	// GEAR only. An orb on a rune would be a stat nothing reads, and an orb on a potion is a stat
	// that vanishes when it is drunk.
	if (target._iClass != ICLASS_WEAPON && target._iClass != ICLASS_ARMOR)
		return false;
	if (target._iClass == ICLASS_QUEST)
		return false;
	// The socketable families are ICLASS_MISC and so are already excluded above, but they are named
	// here as well because "an orb cannot go into a jewel" is a rule worth being able to find.
	if (IsMysticOrbIdx(target.IDidx) || IsOracoolGemIdx(target.IDidx) || IsOracoolRuneIdx(target.IDidx)
	    || IsOracoolJewelIdx(target.IDidx) || IsOracoolSalvageIdx(target.IDidx))
		return false;
	return target._iOracoolOrbCount < MaxOrbsPerItem;
}

bool TryApplyMysticOrb(const Player &player, Item &target, const Item &held)
{
	if (held.isEmpty() || !IsMysticOrbIdx(held.IDidx))
		return false;
	if (!CanReceiveMysticOrb(target))
		return false;

	const ItemPower power = MysticOrbPower(held.IDidx);
	if (power.type == IPL_INVALID)
		return false;

	// Through ApplyItemPower rather than by touching the stat fields directly - the same door the
	// fifteen item sets use, and for the same reason: it is what guarantees an orb's +3 Strength is
	// the identical +3 Strength an affix grants, in the same field with the same sign.
	ApplyItemPower(player, target, power);
	target._iOracoolOrbCount++;
	return true;
}

std::string MysticOrbCountLine(const Item &item)
{
	// Shown on anything that HAS taken an orb, and on anything that COULD - a player needs to know
	// how much room is left before they spend, and an item silently at its cap is the one thing
	// this line exists to prevent.
	if (item._iOracoolOrbCount == 0 && !CanReceiveMysticOrb(item))
		return {};
	return fmt::format(fmt::runtime(_("Mystic Orbs: {:d} / {:d}")),
	    item._iOracoolOrbCount, MaxOrbsPerItem);
}

} // namespace devilution::oracool
