#include "oracool/named_encounters.h"

#include "diablo.h"
#include "items.h"
#include "levels/gendung.h"
#include "monster.h"
#include "multi.h"
#include "oracool/endgame_boss.h"
#include "oracool/event_log.h"
#include "oracool/oracool.h"
#include "player.h"
#include "utils/language.h"
#include "utils/str_cat.hpp"

namespace devilution::oracool {

namespace {

struct EncounterItems {
	NamedEncounter encounter;
	_item_indexes map;
	_item_indexes reward;
};

/** GENERATED by tools/GenEncounterItems.ps1 - do not edit by hand. */
constexpr EncounterItems Items_[] = {
#include "oracool/encounter_items_table.inc"
};

/**
 * @brief The place and the fight, per encounter.
 *
 * The arena levels are NOT authored for this - they are PvP rooms with no monster spawn points - so
 * the monster TYPE is named here and loaded explicitly. That is the same thing every quest set
 * level does; see the Warlord and Lazarus branches of InitMonsters.
 *
 * The types climb with the encounter, and the tileset each arena loads with is fixed rather than
 * inferred: setlvltype has to be right BEFORE StartNewLvl or the level draws in the wrong art, and
 * the /arena command setting it explicitly is the tell.
 */
struct EncounterPlace {
	_setlevels level;
	dungeon_type dungeon;
	_monster_id monster;
	const char *name;
};

constexpr EncounterPlace Places[] = {
	{ SL_ARENA_CHURCH, DTYPE_CATHEDRAL, MT_WSKELAX, "The Sunken Chapel" },
	{ SL_ARENA_CIRCLE_OF_LIFE, DTYPE_CATACOMBS, MT_NGOATMC, "The Ring of Mourning" },
	{ SL_ARENA_HELL, DTYPE_HELL, MT_HORNED, "The Ember Vault" },
};

static_assert(sizeof(Places) / sizeof(Places[0]) == static_cast<size_t>(NamedEncounterCount),
    "every encounter needs a place, a tileset and a monster type");
static_assert(sizeof(Items_) / sizeof(Items_[0]) == static_cast<size_t>(NamedEncounterCount),
    "every encounter needs a map to open it and a charm to pay for it");

size_t IndexOf(NamedEncounter encounter)
{
	return static_cast<size_t>(encounter);
}

} // namespace

const char *NamedEncounterName(NamedEncounter encounter)
{
	return Places[IndexOf(encounter)].name;
}

_setlevels NamedEncounterLevel(NamedEncounter encounter)
{
	return Places[IndexOf(encounter)].level;
}

dungeon_type NamedEncounterDungeon(NamedEncounter encounter)
{
	return Places[IndexOf(encounter)].dungeon;
}

_monster_id NamedEncounterMonster(NamedEncounter encounter)
{
	return Places[IndexOf(encounter)].monster;
}

int NamedEncounterMapItem(NamedEncounter encounter)
{
	return Items_[IndexOf(encounter)].map;
}

int NamedEncounterReward(NamedEncounter encounter)
{
	return Items_[IndexOf(encounter)].reward;
}

bool EncounterForMapItem(int mapIdx, NamedEncounter &out)
{
	for (const EncounterItems &row : Items_) {
		if (row.map == mapIdx) {
			out = row.encounter;
			return true;
		}
	}
	return false;
}

bool CurrentNamedEncounter(NamedEncounter &out)
{
	if (!setlevel)
		return false;
	for (int i = 0; i < NamedEncounterCount; i++) {
		const auto encounter = static_cast<NamedEncounter>(i);
		if (NamedEncounterLevel(encounter) == setlvlnum) {
			out = encounter;
			return true;
		}
	}
	return false;
}

bool EnterNamedEncounter(Player &player, NamedEncounter encounter)
{
	if (!IsSinglePlayer())
		return false;
	// From TOWN only. The arena command allows arena-to-arena travel; this deliberately does not -
	// the map is consumed on use, and hopping between encounters without passing through town would
	// make it possible to be in one with no way back if anything ever went wrong with the exit.
	if (!player.isOnLevel(0))
		return false;

	// BEFORE StartNewLvl, not after. The /arena command does the same and that is the tell: the
	// level loads its tileset from this, so setting it afterwards draws the room in the wrong art.
	setlvltype = NamedEncounterDungeon(encounter);
	StartNewLvl(player, WM_DIABSETLVL, NamedEncounterLevel(encounter));
	return true;
}

bool IsNamedEncounterBoss(const Monster &monster)
{
	NamedEncounter encounter;
	if (!CurrentNamedEncounter(encounter))
		return false;
	// The encounter floor holds exactly one Dread boss and its escort, so "the boss of this
	// encounter" is "the Dread monster on this floor" - there is nothing else it could be.
	return IsEndgameBoss(monster);
}

void AwardNamedEncounter(const Monster &monster)
{
	NamedEncounter encounter;
	if (!CurrentNamedEncounter(encounter))
		return;
	if (!IsEndgameBoss(monster))
		return;
	if (ActiveItemCount >= MAXITEMS)
		return;

	// GUARANTEED, which is the whole point of a named encounter - the map said what it pays and a
	// roll here would make that a lie. The map is already spent by the time this runs.
	//
	// Through SpawnQuestItem rather than by hand: the placement helpers it uses are file-local to
	// items.cpp, and this is the public door that already means "put exactly this item on the floor
	// here". randarea 0 keeps it at the guardian's feet, which is where a player will look.
	SpawnQuestItem(static_cast<_item_indexes>(NamedEncounterReward(encounter)),
	    monster.position.tile, /*randarea=*/0, /*selflag=*/0, /*sendmsg=*/true);

	LogEvent(StrCat(_(NamedEncounterName(encounter)), " is cleared."));
}

} // namespace devilution::oracool
