#include "oracool/named_encounters.h"

#include "diablo.h"
#include "items.h"
#include "levels/gendung.h"
#include "monster.h"
#include "multi.h"
#include "engine/random.hpp"
#include "oracool/endgame_boss.h"
#include "oracool/event_log.h"
#include "oracool/oracool.h"
#include "player.h"
#include "utils/language.h"
#include "utils/str_cat.hpp"

namespace devilution::oracool {

namespace {

struct EncounterItems {
	NamedEncounter encounter;
	_item_indexes map;
	_item_indexes reward;
};

/** GENERATED by tools/GenEncounterItems.ps1 - do not edit by hand. */
constexpr EncounterItems Items_[] = {
#include "oracool/encounter_items_table.inc"
};

/**
 * @brief The place and the fight, per encounter.
 *
 * The arena levels are NOT authored for this - they are PvP rooms with no monster spawn points - so
 * the monster TYPE is named here and loaded explicitly. That is the same thing every quest set
 * level does; see the Warlord and Lazarus branches of InitMonsters.
 *
 * The types climb with the encounter, and the tileset each arena loads with is fixed rather than
 * inferred: setlvltype has to be right BEFORE StartNewLvl or the level draws in the wrong art, and
 * the /arena command setting it explicitly is the tell.
 */
struct EncounterPlace {
	_setlevels level;
	dungeon_type dungeon;
	_monster_id monster;
	/**
	 * @brief The dungeon floor this arena counts as, for the area-level ladder.
	 *
	 * Audit finding, 2026-08-26. CurrentAreaLevel switches on setlvlnum and these three were not in
	 * it, so all of them fell through to its `floor = 1` default - the deliberate "an unknown place
	 * should be the LEAST rewarding thing on the ladder" case. Which is the right default and the
	 * wrong answer here: an endgame encounter guarded by a Dread boss was paying floor-1 loot and
	 * showing floor-1 depth on the HUD.
	 *
	 * Chosen to sit at the end of each arena's own tileset - Cathedral 1-4, Catacombs 5-8, Hell
	 * 13-16 - so the room's art and its difficulty agree, and the three climb the way the header
	 * says they do.
	 */
	int floor;
	const char *name;
};

constexpr EncounterPlace Places[] = {
	{ SL_ARENA_CHURCH, DTYPE_CATHEDRAL, MT_WSKELAX, 4, "The Sunken Chapel" },
	{ SL_ARENA_CIRCLE_OF_LIFE, DTYPE_CATACOMBS, MT_NGOATMC, 8, "The Ring of Mourning" },
	{ SL_ARENA_HELL, DTYPE_HELL, MT_HORNED, 16, "The Ember Vault" },
};

static_assert(sizeof(Places) / sizeof(Places[0]) == static_cast<size_t>(NamedEncounterCount),
    "every encounter needs a place, a tileset and a monster type");
static_assert(sizeof(Items_) / sizeof(Items_[0]) == static_cast<size_t>(NamedEncounterCount),
    "every encounter needs a map to open it and a charm to pay for it");

size_t IndexOf(NamedEncounter encounter)
{
	return static_cast<size_t>(encounter);
}

/**
 * @brief Frees one ground-item slot by discarding the least valuable thing lying about.
 *
 * Only ever called when the floor is at MAXITEMS and a guaranteed reward has nowhere to land.
 * Ordinary quality only: a unique, a set piece or another quest item on the ground is somebody
 * else's promise and must not be dropped to keep this one.
 */
void MakeRoomForGuaranteedReward()
{
	for (int i = ActiveItemCount - 1; i >= 0; i--) {
		const int ii = ActiveItems[i];
		const Item &candidate = Items[ii];
		if (candidate._iMagical != ITEM_QUALITY_NORMAL)
			continue;
		if (candidate._iCreateInfo == 0 && candidate._iIdentified)
			continue; // quest-placed items carry no create info; leave them alone
		DeleteItem(i);
		return;
	}
}

} // namespace

const char *NamedEncounterName(NamedEncounter encounter)
{
	return Places[IndexOf(encounter)].name;
}

_setlevels NamedEncounterLevel(NamedEncounter encounter)
{
	return Places[IndexOf(encounter)].level;
}

dungeon_type NamedEncounterDungeon(NamedEncounter encounter)
{
	return Places[IndexOf(encounter)].dungeon;
}

_monster_id NamedEncounterMonster(NamedEncounter encounter)
{
	return Places[IndexOf(encounter)].monster;
}

bool NamedEncounterFloorForSetLevel(_setlevels level, int &floor)
{
	for (const EncounterPlace &place : Places) {
		if (place.level == level) {
			floor = place.floor;
			return true;
		}
	}
	return false;
}

int NamedEncounterMapItem(NamedEncounter encounter)
{
	return Items_[IndexOf(encounter)].map;
}

int NamedEncounterReward(NamedEncounter encounter)
{
	return Items_[IndexOf(encounter)].reward;
}

bool EncounterForMapItem(int mapIdx, NamedEncounter &out)
{
	for (const EncounterItems &row : Items_) {
		if (row.map == mapIdx) {
			out = row.encounter;
			return true;
		}
	}
	return false;
}

void TrySpawnSealedMap(const Monster &monster, bool sendmsg)
{
	// Single-player only, like every other Oracool drop family: the compact multiplayer item pack
	// cannot recreate an item that is not in the seeded pool, and a Sealed Map deliberately is not.
	if (!IsSinglePlayer())
		return;
	if (!IsEndgameBoss(monster))
		return;
	// A map dropped inside an encounter would let a player chain arenas without passing through
	// town, which EnterNamedEncounter already refuses for its own reasons. Refused at the source
	// too, so the two cannot disagree.
	if (setlevel)
		return;
	if (ActiveItemCount >= MAXITEMS)
		return;

	// A quarter of Dread bosses. They are guaranteed from the middle of the area ladder onward
	// (BossGuaranteedAreaLevel), so roughly one a floor at depth - a certain drop would bury the
	// player in maps and make the encounters routine rather than a destination. The map is the
	// pacing mechanism this feature has instead of a cooldown, which is exactly why the rate is a
	// design number and not an afterthought.
	constexpr int MapDropPercent = 25;
	if (GenerateRnd(100) >= MapDropPercent)
		return;

	// Uniform across the three rather than chosen by depth. Depth-gating reads well until you
	// notice it makes the Sunken Chapel's charm unobtainable the moment a character out-levels the
	// shallow floors - and all three charms are meant to be gettable, because the three-charm cap
	// is supposed to be a decision.
	const auto encounter = static_cast<NamedEncounter>(GenerateRnd(NamedEncounterCount));
	SpawnQuestItem(static_cast<_item_indexes>(NamedEncounterMapItem(encounter)),
	    monster.position.tile, /*randarea=*/0, /*selflag=*/0, sendmsg);
}

bool CurrentNamedEncounter(NamedEncounter &out)
{
	if (!setlevel)
		return false;
	for (int i = 0; i < NamedEncounterCount; i++) {
		const auto encounter = static_cast<NamedEncounter>(i);
		if (NamedEncounterLevel(encounter) == setlvlnum) {
			out = encounter;
			return true;
		}
	}
	return false;
}

bool EnterNamedEncounter(Player &player, NamedEncounter encounter)
{
	if (!IsSinglePlayer())
		return false;
	// From TOWN only. The arena command allows arena-to-arena travel; this deliberately does not -
	// the map is consumed on use, and hopping between encounters without passing through town would
	// make it possible to be in one with no way back if anything ever went wrong with the exit.
	if (!player.isOnLevel(0))
		return false;

	// A named encounter is always a FRESH instance. Audit finding, 2026-08-26: leaving an arena
	// runs SaveLevel, which sets _pSLvlVisited[setlvlnum], and LoadGameLevel then takes its
	// LoadLevel() branch on re-entry instead of generating - so the second Sealed Map opened a room
	// containing the corpse of the boss you already killed, and was consumed for it.
	//
	// Clearing the visited flag is the whole fix: that branch is the only thing that distinguishes
	// "return to a level you have been to" from "generate one". Ordinary dungeon floors want the
	// remembering; an arena is a one-use room and wants the opposite.
	//
	// The stale saved level stays in the archive and is simply never read. Deleting it would mean
	// reaching into the save writer from here for no benefit.
	const _setlevels level = NamedEncounterLevel(encounter);
	player._pSLvlVisited[level] = false;

	// BEFORE StartNewLvl, not after. The /arena command does the same and that is the tell: the
	// level loads its tileset from this, so setting it afterwards draws the room in the wrong art.
	setlvltype = NamedEncounterDungeon(encounter);
	StartNewLvl(player, WM_DIABSETLVL, level);
	return true;
}

bool IsNamedEncounterBoss(const Monster &monster)
{
	NamedEncounter encounter;
	if (!CurrentNamedEncounter(encounter))
		return false;
	// The encounter floor holds exactly one Dread boss and its escort, so "the boss of this
	// encounter" is "the Dread monster on this floor" - there is nothing else it could be.
	return IsEndgameBoss(monster);
}

void AwardNamedEncounter(const Monster &monster)
{
	NamedEncounter encounter;
	if (!CurrentNamedEncounter(encounter))
		return;
	if (!IsEndgameBoss(monster))
		return;

	// "Guaranteed" has to survive a full floor. Audit finding, 2026-08-26: this used to return
	// silently at the item cap, and the boss's ORDINARY loot is spawned first - so the one drop the
	// map promised was the one drop that could be crowded out by junk.
	//
	// Room is made rather than the reward abandoned. An arena holds one boss and its escort, so
	// reaching 127 ground items here is close to impossible; that is precisely why it must not be
	// the case that quietly loses the payout.
	if (ActiveItemCount >= MAXITEMS)
		MakeRoomForGuaranteedReward();
	if (ActiveItemCount >= MAXITEMS) {
		LogEvent(std::string(_("The ground is too littered for the reward to fall - clear some space.")),
		    UiFlags::ColorRed);
		return;
	}

	// GUARANTEED, which is the whole point of a named encounter - the map said what it pays and a
	// roll here would make that a lie. The map is already spent by the time this runs.
	//
	// Through SpawnQuestItem rather than by hand: the placement helpers it uses are file-local to
	// items.cpp, and this is the public door that already means "put exactly this item on the floor
	// here". randarea 0 keeps it at the guardian's feet, which is where a player will look.
	SpawnQuestItem(static_cast<_item_indexes>(NamedEncounterReward(encounter)),
	    monster.position.tile, /*randarea=*/0, /*selflag=*/0, /*sendmsg=*/true);

	LogEvent(StrCat(_(NamedEncounterName(encounter)), " is cleared."));
}

} // namespace devilution::oracool
