#include "oracool/runewords.h"

#include <cctype>
#include <cstring>

#include <fmt/format.h>

#include "items.h"
#include "oracool/gems.h"
#include "oracool/stat_sheet.h"
#include "utils/language.h"
#include "utils/utf8.hpp"

namespace devilution::oracool {

namespace {

// The pool: 309 words across the ten non-jewelry slots. GENERATED by tools/GenRunewords.ps1 from a
// scheme rather than hand-authored, for the reason recorded there - the fiftieth hand-written word
// stops agreeing with the fifth, and nobody notices until the balance is wrong.
constexpr RunewordDefinition Runewords[] = {
#include "oracool/runewords_data.inc"
};
constexpr size_t RunewordTableSize = sizeof(Runewords) / sizeof(Runewords[0]);

const char *HostName(RunewordHost host)
{
	switch (host) {
	case RunewordHost::Weapon:
		return N_("weapons");
	case RunewordHost::Shield:
		return N_("shields");
	case RunewordHost::Body:
		return N_("body armor");
	case RunewordHost::Helm:
		return N_("helms");
	case RunewordHost::Shoulders:
		return N_("shoulders");
	case RunewordHost::Bracers:
		return N_("bracers");
	case RunewordHost::Gloves:
		return N_("gloves");
	case RunewordHost::Belt:
		return N_("belts");
	case RunewordHost::Legs:
		return N_("legs");
	case RunewordHost::Boots:
		return N_("boots");
	default:
		return "";
	}
}

} // namespace

RunewordHost RunewordHostForItemType(ItemType type)
{
	switch (type) {
	case ItemType::Sword:
	case ItemType::Axe:
	case ItemType::Mace:
	case ItemType::Bow:
	case ItemType::Staff:
		return RunewordHost::Weapon;
	case ItemType::Shield:
		return RunewordHost::Shield;
	case ItemType::LightArmor:
	case ItemType::MediumArmor:
	case ItemType::HeavyArmor:
		return RunewordHost::Body;
	case ItemType::Helm:
		return RunewordHost::Helm;
	case ItemType::Shoulders:
		return RunewordHost::Shoulders;
	case ItemType::Bracers:
		return RunewordHost::Bracers;
	case ItemType::Gloves:
		return RunewordHost::Gloves;
	case ItemType::Belt:
		return RunewordHost::Belt;
	case ItemType::Legs:
		return RunewordHost::Legs;
	case ItemType::Boots:
		return RunewordHost::Boots;
	default:
		return RunewordHost::None;
	}
}

size_t RunewordCount() { return RunewordTableSize; }

const RunewordDefinition *RunewordAt(size_t index)
{
	return index < RunewordTableSize ? &Runewords[index] : nullptr;
}

const RunewordDefinition *GetActiveRuneword(const Item &item)
{
	if (item.isEmpty() || item._iSocketCount == 0)
		return nullptr;
	// Sockets v2: the host is the SLOT, not the three-way gem category - a belt word and a helm
	// word are different things even though both are "armour" to a gem.
	const RunewordHost host = RunewordHostForItemType(item._itype);
	if (host == RunewordHost::None)
		return nullptr;
	for (const RunewordDefinition &word : Runewords) {
		if (static_cast<RunewordHost>(word.host) != host)
			continue;
		if (item._iSocketCount != word.runeCount || item.socketedCount() != word.runeCount)
			continue;
		bool matches = true;
		for (int i = 0; i < word.runeCount; i++) {
			if (item._iSocketed[i] != word.runes[i]) {
				matches = false;
				break;
			}
		}
		if (matches)
			return &word;
	}
	return nullptr;
}

void ApplyRunewordToTotals(const RunewordDefinition &word, ItemBonusTotals &totals)
{
	totals.bonusDamage += word.bonusDamagePercent;
	totals.damageMod += word.damageMod;
	totals.bonusToHit += word.toHit;
	totals.fireResist += word.allResists;
	totals.lightningResist += word.allResists;
	totals.magicResist += word.allResists;
	totals.bonusArmor += word.bonusAc;
	totals.spellLevelAdd += word.spellLevels;
	totals.mana += word.mana << 6;
	totals.hitPoints += word.hitPoints << 6;
	// The second half (2026-09-05), through the same channels the runes' socket effects use.
	totals.flags |= word.flags;
	totals.strength += word.strength;
	totals.dexterity += word.dexterity;
	totals.magic += word.magic;
	totals.vitality += word.vitality;
	totals.magicFind += word.magicFind;
	totals.goldFind += word.goldFind;
	totals.getHit -= word.damageReduction;
	totals.lightRadius += word.lightRadius;
	totals.fireResist += word.fireResist;
	totals.lightningResist += word.lightningResist;
	totals.magicResist += word.magicResist;
}

std::string RuneTeachingLines(uint16_t runeIdx)
{
	// The runes teach their own words - that is the one improvement this fork made on D2, where
	// the recipes lived on a wiki. With 309 words a popular rune belongs to dozens of them, so the
	// list is capped and the remainder counted: an item panel that runs off the screen teaches
	// nothing at all.
	//
	// Cut from 6 to 3 on 2026-08-20, when the rune's own per-host effects moved above this list.
	// Those three lines are what the panel is FOR - the recipes are the bonus - and at six words
	// plus a remainder the panel already spanned most of the screen on a common rune like El.
	constexpr int MaxTaughtWords = 3;
	std::string lines;
	int shown = 0;
	int found = 0;
	for (const RunewordDefinition &word : Runewords) {
		bool contains = false;
		for (int i = 0; i < word.runeCount; i++) {
			if (word.runes[i] == runeIdx)
				contains = true;
		}
		if (!contains)
			continue;
		found++;
		if (shown >= MaxTaughtWords)
			continue;
		std::string sequence;
		for (int i = 0; i < word.runeCount; i++) {
			if (i > 0)
				sequence += ' ';
			// "El Rune" -> the bare rune name reads better in a formula.
			sequence += _(AllItemsList[word.runes[i]].iName);
		}
		if (!lines.empty())
			lines += '\n';
		lines += fmt::format(fmt::runtime(_("Runeword '{:s}': {:s}, in {:s}")),
		    _(word.name), sequence, _(HostName(static_cast<RunewordHost>(word.host))));
		shown++;
	}
	if (found > shown) {
		if (!lines.empty())
			lines += '\n';
		lines += fmt::format(fmt::runtime(_("...and {:d} more runewords")), found - shown);
	}
	return lines;
}

bool TryCompleteRuneword(Item &item)
{
	const RunewordDefinition *word = GetActiveRuneword(item);
	if (word == nullptr)
		return false;
	// The item takes the word's name - the one persisted piece, and it rides the name field every
	// save format already carries. The base name stays visible in the description's own lines.
	CopyUtf8(item._iIName, std::string(_(word->name)), sizeof(item._iIName));
	item._iIdentified = true;
	return true;
}

std::vector<std::string> RunewordBonusLines(const RunewordDefinition &word)
{
	std::vector<std::string> lines;
	const auto line = [&lines](const char *label, int value, const char *suffix = "") {
		if (value != 0)
			lines.push_back(fmt::format(fmt::runtime(_("{:s} {:s}{:d}{:s}")), _(label), value > 0 ? "+" : "", value, suffix));
	};
	line(N_("Damage"), word.bonusDamagePercent, "%");
	line(N_("Damage"), word.damageMod);
	line(N_("To Hit"), word.toHit, "%");
	line(N_("All Resistances"), word.allResists, "%");
	line(N_("Fire Resistance"), word.fireResist, "%");
	line(N_("Lightning Resistance"), word.lightningResist, "%");
	line(N_("Magic Resistance"), word.magicResist, "%");
	line(N_("Armor"), word.bonusAc);
	line(N_("Spell Levels"), word.spellLevels);
	line(N_("Mana"), word.mana);
	line(N_("Life"), word.hitPoints);
	line(N_("Strength"), word.strength);
	line(N_("Dexterity"), word.dexterity);
	line(N_("Magic"), word.magic);
	line(N_("Vitality"), word.vitality);
	line(N_("Magic Find"), word.magicFind, "%");
	line(N_("Gold Find"), word.goldFind, "%");
	line(N_("Damage Reduced"), word.damageReduction);
	line(N_("Light Radius"), word.lightRadius);
	// The flags in the socket effects' own words ("faster attack, life steal"), capitalised as a line.
	if (word.flags != ItemSpecialEffect::None) {
		std::string text = FlagText(word.flags);
		if (!text.empty()) {
			text[0] = static_cast<char>(std::toupper(static_cast<unsigned char>(text[0])));
			lines.push_back(std::move(text));
		}
	}
	return lines;
}

SocketHost RunewordSocketHost(RunewordHost host)
{
	switch (host) {
	case RunewordHost::Weapon:
		return SocketHost::Weapon;
	case RunewordHost::Shield:
		return SocketHost::Shield;
	default:
		return SocketHost::Armor;
	}
}

} // namespace devilution::oracool
